### ISSUE TITLE
1.6.2 install: "Failed to complete patch task"

### ISSUE THREAD

**Issue by mattbrictson** [sparklemotion/nokogiri#1095]
1.6.1 installs fine, but 1.6.2 fails while patching. I'm on Mac OS X Mavericks.

```
$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
```

```
$ gem install nokogiri -v '1.6.2'
Building native extensions.  This could take a while...
Building nokogiri using packaged libraries.
Building libxml2-2.8.0 for nokogiri with the following patches applied:
    - 0001-Fix-parser-local-buffers-size-problems.patch
    - 0002-Fix-entities-local-buffers-size-problems.patch
    - 0003-Fix-an-error-in-previous-commit.patch
    - 0004-Fix-potential-out-of-bound-access.patch
    - 0005-Detect-excessive-entities-expansion-upon-replacement.patch
    - 0006-Do-not-fetch-external-parsed-entities.patch
    - 0007-Enforce-XML_PARSER_EOF-state-handling-through-the-pa.patch
    - 0008-Improve-handling-of-xmlStopParser.patch
    - 0009-Fix-a-couple-of-return-without-value.patch
    - 0010-Keep-non-significant-blanks-node-in-HTML-parser.patch
    - 0011-Do-not-fetch-external-parameter-entities.patch
************************************************************************
IMPORTANT!  Nokogiri builds and uses a packaged version of libxml2.

[snip]

Running 'patch' for libxml2 2.8.0... ERROR, review 'tmp/x86_64-apple-darwin13.1.0/ports/libxml2/2.8.0/patch.log' to see what happened.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/mbrictson/.rbenv/versions/2.1.2/bin/ruby
    --help
    --clean
    --use-system-libraries
    --enable-static
    --disable-static
    --with-zlib-dir
    --without-zlib-dir
    --with-zlib-include
    --without-zlib-include=${zlib-dir}/include
    --with-zlib-lib
    --without-zlib-lib=${zlib-dir}/lib
    --enable-cross-build
    --disable-cross-build
/Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:278:in `block in execute': Failed to complete patch task (RuntimeError)
    from /Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:270:in `chdir'
    from /Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:270:in `execute'
    from /Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:47:in `block in patch'
    from /Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:44:in `each'
    from /Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:44:in `patch'
    from /Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mini_portile-0.5.3/lib/mini_portile.rb:107:in `cook'
    from extconf.rb:247:in `block in process_recipe'
    from extconf.rb:176:in `tap'
    from extconf.rb:176:in `process_recipe'
    from extconf.rb:364:in `<main>'
```

```
$ cat tmp/x86_64-apple-darwin13.1.0/ports/libxml2/2.8.0/patch.log
/Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.2/ports/patches/libxml2/0010-Keep-non-significant-blanks-node-in-HTML-parser.patch:170: trailing whitespace.
<html>
/Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.2/ports/patches/libxml2/0010-Keep-non-significant-blanks-node-in-HTML-parser.patch:171: trailing whitespace.
<body bgcolor="#FFFFFF">
/Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.2/ports/patches/libxml2/0010-Keep-non-significant-blanks-node-in-HTML-parser.patch:172: trailing whitespace.
                <a href="mailto:katherine@cbfanc.org,website@bis.doc.gov?subject=South%20San%20Francisco%20BIS%20Seminar%20-%20October%2016th"></a><br>
/Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.2/ports/patches/libxml2/0010-Keep-non-significant-blanks-node-in-HTML-parser.patch:173: trailing whitespace.
</body>
/Users/mbrictson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.2/ports/patches/libxml2/0010-Keep-non-significant-blanks-node-in-HTML-parser.patch:245: trailing whitespace.
<title>BP6.com #1 online resource for the BP6 Mobo....</title>
error: patch failed: result/HTML/attrents.html:1
error: result/HTML/attrents.html: patch does not apply
error: patch failed: result/HTML/doc3.htm:1
error: result/HTML/doc3.htm: patch does not apply
error: patch failed: result/HTML/test3.html:1
error: result/HTML/test3.html: patch does not apply
error: patch failed: result/HTML/wired.html:3
error: result/HTML/wired.html: patch does not apply
```

**Comment by emaildanwilson** [comment]
annoying... I just hit this too. appears that mini_portile doesn't check for it's patch dependency at all.
