### ISSUE TITLE
segfault using canonicalization with dubious arguments

### ISSUE THREAD

**Issue by Phrogz** [sparklemotion/nokogiri#1122]
~~~
Rammy:Desktop phrogz$ uname -a
Darwin Rammy 13.2.0 Darwin Kernel Version 13.2.0: Thu Apr 17 23:03:13 PDT 2014; root:xnu-2422.100.13~1/RELEASE_X86_64 x86_64

Rammy:Desktop phrogz$ cat tmp.rb
require 'nokogiri'
p RUBY_DESCRIPTION, Nokogiri::VERSION
doc = Nokogiri.XML('<r xmlns="http://foo" xmlns:b="http://bar" x="y"><!-- hi --></r>')
puts doc.canonicalize(1,nil,1){ |a,_| 1 unless a.is_a?(Nokogiri::XML::Namespace) && a.href=="http://bar" }
puts doc.canonicalize(1,1,1){ |a,_| 1 unless a.is_a?(Nokogiri::XML::Namespace) && a.href=="http://bar" }

Rammy:Desktop phrogz$ ruby tmp.rb
"ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin12.3.0]"
"1.6.1"
<r xmlns="http://foo" x="y"><!-- hi --></r>
tmp.rb:5: [BUG] Segmentation fault
ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin12.3.0]

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0014 b:0014 l:000013 d:000013 CFUNC  :canonicalize
c:0003 p:0100 s:0008 b:0007 l:0013f8 d:002270 EVAL   tmp.rb:5
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:0013f8 d:0013f8 TOP   

-- Ruby level backtrace information ----------------------------------------
tmp.rb:5:in `<main>'
tmp.rb:5:in `canonicalize'

-- C level backtrace information -------------------------------------------

   See Crash Report log file under ~/Library/Logs/CrashReporter or
   /Library/Logs/CrashReporter, for the more detail of.

-- Other runtime information -----------------------------------------------

* Loaded script: tmp.rb

* Loaded features:

    0 enumerator.so
    1 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/x86_64-darwin12.3.0/enc/encdb.bundle
    2 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/x86_64-darwin12.3.0/enc/trans/transdb.bundle
    3 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/x86_64-darwin12.3.0/rbconfig.rb
    4 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/compatibility.rb
    5 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/defaults.rb
    6 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/deprecate.rb
    7 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/errors.rb
    8 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/version.rb
    9 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/requirement.rb
   10 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/platform.rb
   11 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/basic_specification.rb
   12 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/stub_specification.rb
   13 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/util/stringio.rb
   14 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb
   15 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/exceptions.rb
   16 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb
   17 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/thread.rb
   18 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/monitor.rb
   19 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb
   20 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems.rb
   21 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/path_support.rb
   22 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb
   23 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/extensions/x86_64-darwin-12/1.9.1/nokogiri-1.6.1/nokogiri/nokogiri.bundle
   24 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/version.rb
   25 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/syntax_error.rb
   26 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/pp/node.rb
   27 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/pp/character_data.rb
   28 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/pp.rb
   29 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/parse_options.rb
   30 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/sax/document.rb
   31 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/sax/parser_context.rb
   32 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/sax/parser.rb
   33 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/sax/push_parser.rb
   34 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/sax.rb
   35 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/x86_64-darwin12.3.0/stringio.bundle
   36 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/node/save_options.rb
   37 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/node.rb
   38 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/attribute_decl.rb
   39 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/element_decl.rb
   40 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/element_content.rb
   41 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/character_data.rb
   42 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/namespace.rb
   43 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/attr.rb
   44 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/dtd.rb
   45 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/cdata.rb
   46 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/text.rb
   47 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/document.rb
   48 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/document_fragment.rb
   49 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/processing_instruction.rb
   50 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/node_set.rb
   51 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/syntax_error.rb
   52 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/xpath/syntax_error.rb
   53 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/xpath.rb
   54 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/xpath_context.rb
   55 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/builder.rb
   56 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/reader.rb
   57 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/notation.rb
   58 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/entity_decl.rb
   59 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/schema.rb
   60 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml/relax_ng.rb
   61 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xml.rb
   62 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xslt/stylesheet.rb
   63 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/xslt.rb
   64 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/html/entity_lookup.rb
   65 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/html/document.rb
   66 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/html/document_fragment.rb
   67 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/html/sax/parser_context.rb
   68 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/html/sax/parser.rb
   69 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/html/sax/push_parser.rb
   70 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/html/element_description.rb
   71 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/html/element_description_defaults.rb
   72 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/html.rb
   73 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/decorators/slop.rb
   74 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/css/node.rb
   75 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/css/xpath_visitor.rb
   76 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/x86_64-darwin12.3.0/racc/cparse.bundle
   77 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/racc/parser.rb
   78 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/css/parser_extras.rb
   79 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/css/parser.rb
   80 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/x86_64-darwin12.3.0/strscan.bundle
   81 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/css/tokenizer.rb
   82 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/css/syntax_error.rb
   83 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/css.rb
   84 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri/html/builder.rb
   85 /Users/phrogz/.rvm/gems/ruby-1.9.3-p392/gems/nokogiri-1.6.1/lib/nokogiri.rb
   86 /Users/phrogz/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/x86_64-darwin12.3.0/enc/trans/single_byte.bundle

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
~~~

**Comment by flavorjones** [comment]
Looks like this was fixed by @larskanis in 324f7ce.
