### ISSUE TITLE
segfault in poorly formed HTML for 1.6.2

### ISSUE THREAD

**Issue by tmgardner** [sparklemotion/nokogiri#1126]
I see there's another 1.6.2 segfault reported, I'm not sure if it's the same issue; I've worked this to a minimal reproducer:

```
$ uname -a
Darwin new-host-7.home 13.2.0 Darwin Kernel Version 13.2.0: Thu Apr 17 23:03:13 PDT 2014; root:xnu-2422.100.13~1/RELEASE_X86_64 x86_64
$ cat tmp.rb 
require 'nokogiri'
p RUBY_DESCRIPTION, Nokogiri::VERSION
Nokogiri::HTML("<html></html><!DOCTYPE html>\n<html></html>".force_encoding("ASCII-8BIT"))
$ ruby tmp.rb
"ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-darwin13.1.0]"
"1.6.2"
/Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/sax/push_parser.rb:47: [BUG] Segmentation fault
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-darwin13.1.0]

-- Control frame information -----------------------------------------------
c:0008 p:---- s:0039 b:0039 l:000038 d:000038 CFUNC  :native_write
c:0007 p:0019 s:0034 b:0034 l:000033 d:000033 METHOD /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/sax/push_parser.rb:47
c:0006 p:0213 s:0029 b:0029 l:000028 d:000028 METHOD /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/document.rb:268
c:0005 p:0346 s:0022 b:0022 l:000021 d:000021 METHOD /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/document.rb:201
c:0004 p:0050 s:0014 b:0014 l:000013 d:000013 METHOD /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html.rb:15
c:0003 p:0063 s:0006 b:0006 l:001158 d:0024d8 EVAL   tmp.rb:3
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:001158 d:001158 TOP   

-- Ruby level backtrace information ----------------------------------------
tmp.rb:3:in `<main>'
/Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html.rb:15:in `HTML'
/Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/document.rb:201:in `parse'
/Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/document.rb:268:in `detect_encoding'
/Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/sax/push_parser.rb:47:in `write'
/Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/sax/push_parser.rb:47:in `native_write'

-- C level backtrace information -------------------------------------------

   See Crash Report log file under ~/Library/Logs/CrashReporter or
   /Library/Logs/CrashReporter, for the more detail of.

-- Other runtime information -----------------------------------------------

* Loaded script: tmp.rb

* Loaded features:

    0 enumerator.so
    1 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/x86_64-darwin13.1.0/enc/encdb.bundle
    2 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/x86_64-darwin13.1.0/enc/trans/transdb.bundle
    3 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/x86_64-darwin13.1.0/rbconfig.rb
    4 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/compatibility.rb
    5 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/defaults.rb
    6 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/deprecate.rb
    7 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/errors.rb
    8 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/version.rb
    9 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/requirement.rb
   10 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/platform.rb
   11 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/basic_specification.rb
   12 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/stub_specification.rb
   13 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/util/stringio.rb
   14 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb
   15 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/exceptions.rb
   16 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb
   17 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/thread.rb
   18 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/monitor.rb
   19 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb
   20 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems.rb
   21 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/path_support.rb
   22 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb
   23 /Users/todd/.rvm/gems/ruby-1.9.3-p484/extensions/x86_64-darwin-13/1.9.1/nokogiri-1.6.2/nokogiri/nokogiri.bundle
   24 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/version.rb
   25 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/syntax_error.rb
   26 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/pp/node.rb
   27 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/pp/character_data.rb
   28 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/pp.rb
   29 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/parse_options.rb
   30 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/sax/document.rb
   31 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/sax/parser_context.rb
   32 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/sax/parser.rb
   33 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/sax/push_parser.rb
   34 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/sax.rb
   35 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/x86_64-darwin13.1.0/stringio.bundle
   36 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/node/save_options.rb
   37 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/node.rb
   38 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/attribute_decl.rb
   39 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/element_decl.rb
   40 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/element_content.rb
   41 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/character_data.rb
   42 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/namespace.rb
   43 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/attr.rb
   44 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/dtd.rb
   45 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/cdata.rb
   46 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/text.rb
   47 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/document.rb
   48 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/document_fragment.rb
   49 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/processing_instruction.rb
   50 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/node_set.rb
   51 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/syntax_error.rb
   52 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/xpath/syntax_error.rb
   53 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/xpath.rb
   54 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/xpath_context.rb
   55 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/builder.rb
   56 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/reader.rb
   57 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/notation.rb
   58 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/entity_decl.rb
   59 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/schema.rb
   60 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml/relax_ng.rb
   61 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xml.rb
   62 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xslt/stylesheet.rb
   63 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/xslt.rb
   64 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/entity_lookup.rb
   65 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/document.rb
   66 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/document_fragment.rb
   67 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/sax/parser_context.rb
   68 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/sax/parser.rb
   69 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/sax/push_parser.rb
   70 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/element_description.rb
   71 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/element_description_defaults.rb
   72 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html.rb
   73 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/decorators/slop.rb
   74 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/css/node.rb
   75 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/css/xpath_visitor.rb
   76 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/x86_64-darwin13.1.0/racc/cparse.bundle
   77 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/racc/parser.rb
   78 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/css/parser_extras.rb
   79 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/css/parser.rb
   80 /Users/todd/.rvm/rubies/ruby-1.9.3-p484/lib/ruby/1.9.1/x86_64-darwin13.1.0/strscan.bundle
   81 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/css/tokenizer.rb
   82 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/css/syntax_error.rb
   83 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/css.rb
   84 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri/html/builder.rb
   85 /Users/todd/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.2/lib/nokogiri.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
```

**Comment by libc** [comment]
This is no longer an issue in master/1.6.6.3. So can be closed

**Comment by jvshahid** [comment]
Thanks @libc. Added the test case to master to make sure we don't have a regression in the future.
