### ISSUE TITLE
Problem with ruby 2.1.2 and nokogiri 1.6.2.1 

### ISSUE THREAD

**Issue by zabolotnov87** [sparklemotion/nokogiri#1184]
Hi,

I'm trying to install nokogiri 1.6.2.1 on Red Hat 

```
Linux version 2.6.32-431.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Fri Nov 22 03:15:09 UTC 2013)
```

with ruby 2.1.2 and I'm getting 

```
Building nokogiri using packaged libraries.                                                                                                                                   [22/68]
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    /opt/ruby/versions/2.1.2/bin/ruby extconf.rb
Building nokogiri using packaged libraries.
checking for iconv.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/ruby/versions/2.1.2/bin/ruby
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build
/opt/ruby/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
from /opt/ruby/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:587:in `try_cpp'
        from /opt/ruby/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:1067:in `block in have_header'
        from /opt/ruby/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
        from /opt/ruby/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /opt/ruby/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /opt/ruby/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
        from /opt/ruby/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from /opt/ruby/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
        from /opt/ruby/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
        from /opt/ruby/versions/2.1.2/lib/ruby/2.1.0/mkmf.rb:1066:in `have_header'
        from extconf.rb:103:in `have_iconv?'
        from extconf.rb:148:in `block (2 levels) in iconv_prefix'
        from extconf.rb:90:in `preserving_globals'
        from extconf.rb:143:in `block in iconv_prefix'
        from extconf.rb:120:in `each_iconv_idir'
        from extconf.rb:137:in `iconv_prefix'
        from extconf.rb:424:in `block in <main>'
        from extconf.rb:161:in `block in process_recipe'
        from extconf.rb:154:in `tap'
        from extconf.rb:154:in `process_recipe'
        from extconf.rb:419:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /opt/ruby/versions/2.1.2/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.2.1 for inspection.
Results logged to /opt/ruby/versions/2.1.2/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/nokogiri-1.6.2.1/gem_make.out
```

mkmf.log:

```
"gcc -o conftest -I/opt/ruby/versions/2.1.2/include/ruby-2.1.0/x86_64-linux -I/opt/ruby/versions/2.1.2/include/ruby-2.1.0/ruby/backward -I/opt/ruby/versions/2.1.2/include/ruby-2.1.0 -I. -I/usr/include    -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -mtune=generic -Wall -fno-strict-aliasing  -g -DXP_UNIX -Wall -Wcast-qual -Wwrite-strings -Wconversion -Wmissing-noreturn -Winline conftest.c  -L. -L/opt/ruby/versions/2.1.2/lib -Wl,-R/opt/ruby/versions/2.1.2/lib -L/usr/lib -Wl,-R/usr/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic  -m64   -Wl,-R -Wl,/opt/ruby/versions/2.1.2/lib -L/opt/ruby/versions/2.1.2/lib -lruby-static  -lpthread -lrt -lgmp -ldl -lcrypt -lm   -lc "
/usr/bin/ld: cannot find -lgmp
collect2: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

This problem happens with ruby 2.1.2. There is no problem with ruby 2.0.0-p247: nokogiri is installed successfully.

**Comment by flavorjones** [comment]
See related rvm issue https://github.com/rvm/rvm/issues/3509
