### ISSUE TITLE
Nokogiri 1.6.6.1 won't build under Ruby 1.9.3p547

### ISSUE THREAD

**Issue by QuinnyPig** [sparklemotion/nokogiri#1230]
1.6.5 is fine, this is new behavior in 1.6.6.1. And yes, I know this version of Ruby is ancient and probably unsupported. :-)
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/bin/ruby -r ./siteconf20150122-30107-10e8dej.rb extconf.rb
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... yes
Building nokogiri using packaged libraries.
checking for gzdopen() in -lz... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/bin/ruby
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build
/Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:619:in `try_func'
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:845:in `block in have_library'
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:254:in `open'
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:254:in `open'
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
	from /Users/cquinn/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/mkmf.rb:840:in `have_library'
	from extconf.rb:466:in `block in <main>'
	from extconf.rb:102:in `preserving_globals'
	from extconf.rb:465:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/cquinn/.rvm/gems/ruby-1.9.3-p547/gems/nokogiri-1.6.6.1 for inspection.
Results logged to /Users/cquinn/.rvm/gems/ruby-1.9.3-p547/extensions/x86_64-darwin-14/1.9.1/nokogiri-1.6.6.1/gem_make.out
```

**Comment by flavorjones** [comment]
What kind of system are you on? I need more information in order to diagnose the issue.

**Comment by flavorjones** [comment]
We've managed to reproduce an issue with Nokogiri 1.6.6.1 on OSX running Ruby 1.9.3:

> https://travis-ci.org/sparklemotion/nokogiri

Hang in there, working on it.

**Comment by flavorjones** [comment]
Sorry - more specific build:

> https://travis-ci.org/sparklemotion/nokogiri/builds/48077910

**Comment by QuinnyPig** [comment]
Glorious.

I'm able to reproduce this on multiple machines, all running OS X Yosemite latest (10.10.1).

**Comment by flavorjones** [comment]
OK, got a fix. About to cut 1.6.6.2. See 5f8fa1795b312ae3ca894b7a58e1aba3d31bce4e

Huge headdesk here. Sigh.

**Comment by flavorjones** [comment]
![miss-piggy-headdesk](https://cloud.githubusercontent.com/assets/8207/5880046/0e052e0a-a303-11e4-9279-a0a04326ff70.gif)

**Comment by flavorjones** [comment]
1.6.6.2 up on rubygems. closing.
