### ISSUE TITLE
Error to match LIBXML_PARSER_VERSION

### ISSUE THREAD

**Issue by hallison** [sparklemotion/nokogiri#1368]
I try install Redmine executing:

```
bundle exec rake db:migrate
```

```
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/version.rb:3: warning: already initialized constant Nokogiri::VERSION
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/version.rb:3: warning: previous definition of VERSION was here
rake aborted!
NoMethodError: undefined method `collect' for nil:NilClass
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/version.rb:16:in `loaded_parser_version'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/version.rb:40:in `warnings'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/version.rb:93:in `<class:VersionInfo>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/version.rb:5:in `<module:Nokogiri>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/version.rb:1:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri.rb:31:in `require'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri.rb:31:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/loofah-2.0.3/lib/loofah.rb:3:in `require'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/loofah-2.0.3/lib/loofah.rb:3:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-html-sanitizer-1.0.2/lib/rails-html-sanitizer.rb:2:in `require'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rails-html-sanitizer-1.0.2/lib/rails-html-sanitizer.rb:2:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/sanitize_helper.rb:3:in `require'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/sanitize_helper.rb:3:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/text_helper.rb:32:in `<module:TextHelper>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/text_helper.rb:29:in `<module:Helpers>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/text_helper.rb:6:in `<module:ActionView>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/text_helper.rb:4:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/form_tag_helper.rb:18:in `<module:FormTagHelper>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/form_tag_helper.rb:14:in `<module:Helpers>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/form_tag_helper.rb:8:in `<module:ActionView>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/form_tag_helper.rb:6:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/form_helper.rb:4:in `require'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers/form_helper.rb:4:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers.rb:50:in `<module:Helpers>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers.rb:4:in `<module:ActionView>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/actionview-4.2.4/lib/action_view/helpers.rb:3:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/legacy_asset_tag_helper.rb:7:in `<module:LegacyAssetTagHelper>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/legacy_asset_tag_helper.rb:6:in `<module:Rails>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/legacy_asset_tag_helper.rb:4:in `<module:Sprockets>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/legacy_asset_tag_helper.rb:3:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:45:in `require'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:45:in `<module:Helper>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:7:in `<module:Rails>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:6:in `<module:Sprockets>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:5:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/railtie.rb:6:in `require'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/sprockets-rails-2.3.3/lib/sprockets/railtie.rb:6:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/all.rb:13:in `require'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/all.rb:13:in `block in <top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/all.rb:11:in `each'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/all.rb:11:in `<top (required)>'
/home/hallison/coding/vendors/redmine/config/application.rb:3:in `require'
/home/hallison/coding/vendors/redmine/config/application.rb:3:in `<top (required)>'
/home/hallison/coding/vendors/redmine/Rakefile:5:in `require'
/home/hallison/coding/vendors/redmine/Rakefile:5:in `<top (required)>'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/hallison/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/hallison/.gem/ruby/2.1.6/bin/rake:23:in `load'
/home/hallison/.gem/ruby/2.1.6/bin/rake:23:in `<main>'
```

LibXML information:

```
Loaded plugins: product-id, security, subscription-manager
Installed Packages
Name        : libxml2
Arch        : s390x
Version     : 2.7.6
Release     : 8.el6_3.4
Size        : 1.9 M
Repo        : installed
From repo   : anaconda-RedHatEnterpriseLinux-201301301450.s390x
Summary     : Library providing XML and HTML support
URL         : http://xmlsoft.org/
License     : MIT
Description : This library allows to manipulate XML files. It includes support
            : to read, modify and write XML and HTML files. There is DTDs
            : support this includes parsing and validation even with complex
            : DtDs, either at parse time or later once the document has been
            : modified. The output can be a simple SAX stream or and in-memory
            : DOM like representations. In this case one can use the built-in
            : XPath and XPointer implementation to select subnodes or ranges. A
            : flexible Input/Output mechanism is available, with existing HTTP
            : and FTP modules and combined to an URI library.

Available Packages
Name        : libxml2
Arch        : s390
Version     : 2.7.6
Release     : 8.el6_3.4
Size        : 756 k
Repo        : rhel-6-local
Summary     : Library providing XML and HTML support
URL         : http://xmlsoft.org/
License     : MIT
Description : This library allows to manipulate XML files. It includes support
            : to read, modify and write XML and HTML files. There is DTDs
            : support this includes parsing and validation even with complex
            : DtDs, either at parse time or later once the document has been
            : modified. The output can be a simple SAX stream or and in-memory
            : DOM like representations. In this case one can use the built-in
            : XPath and XPointer implementation to select subnodes or ranges. A
            : flexible Input/Output mechanism is available, with existing HTTP
            : and FTP modules and combined to an URI library.
```

Thanks.

**Comment by flavorjones** [comment]
@hallison - Thanks for asking this question.

It's not clear what's going on from the information you've provided. Can you help me reproduce this?

* What's the output from `nokogiri -v`?
* How did you install nokogiri? Did you pass any flags to bundler or to the `gem` command?

Thanks.

**Comment by flavorjones** [comment]
Closing, pending more information from OP as requested.
