### ISSUE TITLE
investigate odd rubinius memory management error

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1386]
See this build: https://travis-ci.org/sparklemotion/nokogiri/jobs/93868440

```
  1) Error:
test_slice_waaaaaay_off_the_end(Nokogiri::XML::TestNodeSet):
ArgumentError: Data object has already been freed
    /home/travis/build/sparklemotion/nokogiri/lib/nokogiri/xml/document.rb:82:in `create_element'
    /home/travis/build/sparklemotion/nokogiri/lib/nokogiri/xml/builder.rb:359:in `div (method_missing)'
    /home/travis/build/sparklemotion/nokogiri/test/xml/test_node_set.rb:576:in `test_slice_waaaaaay_off_the_end'
    kernel/common/integer.rb:196:in `times'
    /home/travis/build/sparklemotion/nokogiri/test/xml/test_node_set.rb:576:in `test_slice_waaaaaay_off_the_end'
```

**Comment by flavorjones** [comment]
Ah, crap, rerunning the Travis build overwrote the same job number. WTH? Anyway, there's the relevant log snippet.

**Comment by flavorjones** [comment]
Just saw this again with rbx-2:

```
  1) Error:
test_gt_string_arg(Nokogiri::XML::TestNodeSet):
ArgumentError: Data object has already been freed
    /home/travis/build/sparklemotion/nokogiri/lib/nokogiri/xml/node_set.rb:186:in `each'
    kernel/common/enumerable.rb:321:in `inject'
    /home/travis/build/sparklemotion/nokogiri/lib/nokogiri/xml/node_set.rb:90:in `xpath'
    /home/travis/build/sparklemotion/nokogiri/lib/nokogiri/xml/node_set.rb:99:in `>'
    /home/travis/build/sparklemotion/nokogiri/test/xml/test_node_set.rb:323:in `test_gt_string_arg'
    /home/travis/.rvm/gems/rbx-2/gems/minitest-2.2.2/lib/minitest/unit.rb:942:in `run'
    /home/travis/.rvm/gems/rbx-2/gems/minitest-2.2.2/lib/minitest/unit.rb:781:in `_run_suite'
    kernel/bootstrap/array.rb:97:in `map'
    /home/travis/.rvm/gems/rbx-2/gems/minitest-2.2.2/lib/minitest/unit.rb:774:in `_run_suite'
    /home/travis/.rvm/gems/rbx-2/gems/minitest-2.2.2/lib/minitest/unit.rb:764:in `_run_suites'
    kernel/bootstrap/array.rb:97:in `map'
    /home/travis/.rvm/gems/rbx-2/gems/minitest-2.2.2/lib/minitest/unit.rb:764:in `_run_suites'
    /home/travis/.rvm/gems/rbx-2/gems/minitest-2.2.2/lib/minitest/unit.rb:740:in `_run_anything'
    /home/travis/.rvm/gems/rbx-2/gems/minitest-2.2.2/lib/minitest/unit.rb:903:in `run_tests'
    /home/travis/.rvm/gems/rbx-2/gems/minitest-2.2.2/lib/minitest/unit.rb:890:in `_run'
    kernel/bootstrap/array.rb:76:in `each'
    /home/travis/.rvm/gems/rbx-2/gems/minitest-2.2.2/lib/minitest/unit.rb:889:in `_run'
    /home/travis/.rvm/gems/rbx-2/gems/minitest-2.2.2/lib/minitest/unit.rb:878:in `run'
    /home/travis/.rvm/gems/rbx-2/gems/minitest-2.2.2/lib/minitest/unit.rb:658:in `autorun'
    kernel/bootstrap/proc.rb:20:in `call'
    kernel/loader.rb:706:in `run_at_exits'
    kernel/loader.rb:736:in `epilogue'
    kernel/loader.rb:850:in `main'
```

**Comment by flavorjones** [comment]
rbx-3 seems fine. going to close this.
