### ISSUE TITLE
install issue on ubuntu 14.04

### ISSUE THREAD

**Issue by gidden** [sparklemotion/nokogiri#1449]
Hi all. Perhaps this is a well known easy fix, but I am having trouble on Ubuntu 14.04 when using nokogiri for a Jekyll plugin. I tried

```
$ gem install nokogiri
Fetching: mini_portile2-2.0.0.gem (100%)                                                                                                                                                                            
Successfully installed mini_portile2-2.0.0
Fetching: nokogiri-1.6.7.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.7.2
Parsing documentation for mini_portile2-2.0.0                                                                                                                                                                       
Installing ri documentation for mini_portile2-2.0.0
Parsing documentation for nokogiri-1.6.7.2
unable to convert "\xD0" from ASCII-8BIT to UTF-8 for /home/gidden/.rvm/gems/ruby-2.0.0-p643/extensions/x86_64-linux/2.0.0/nokogiri-1.6.7.2/nokogiri/nokogiri.so, skipping
unable to convert "\xD0" from ASCII-8BIT to UTF-8 for lib/nokogiri/nokogiri.so, skipping
Installing ri documentation for nokogiri-1.6.7.2
2 gems installed
```

which seemed fine. But then when trying to run the plugin as described, I got
the following error:

```
$ make serve
jekyll serve -w -P 4050
Configuration file: /home/gidden/work/labnb/_config.yml                                                                                                                                                             
/home/gidden/work/labnb/_plugins/tocGenerator.rb:1:in `require': cannot load such file -- nokogiri (LoadError)                                                                                                      
from /home/gidden/work/labnb/_plugins/tocGenerator.rb:1:in `<top (required)>'
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:75:in `require'                                                                                                          
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'                                                                         
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `each'                                                                                                             
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'                                                                                    
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `each'                                                                                                             
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'                                                                                            
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'                                                                                                                 
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'                                                                            
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'                                                                                                 
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'                                                                                                                
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'                                                                                                                   
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/bin/jekyll:23:in `load'
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/bin/jekyll:23:in `<main>'                                                                                                                                               
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
from /home/gidden/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
make: *** [serve] Error 1
```

Note that I tried sudo apt-getting all the packages mentioned in the install notes. Any thoughts?

**Comment by flavorjones** [comment]
Hi,

The first set of messages, "unable to convert...", are warnings related to installing the documentation, not errors related to installing nokogiri. If you run `gem install nokogiri --no-ri --no-rdoc` you should see those messages go away.

The second problem tells me that nokogiri isn't on your load path. This could be because you're not using bundler, or you're using a gemset, or something else. I'd advise that you try creating a Gemfile for your project, and `bundle exec jekyll serve`.

i'm going to close this, as I'm pretty sure it's not actionable by the Nokogiri core team; but if you find new information, please feel free to respond and we can reopen.

**Comment by gidden** [comment]
Thanks for the tips @flavorjones, it is indeed something messed up with my Ruby environment.
