### ISSUE TITLE
StackOverflowError using 1.6.7.2-java 

### ISSUE THREAD

**Issue by jeremyhaile** [sparklemotion/nokogiri#1458]
We are receiving regular StackOverflowErrors that are crashing our server when parsing websites using Nokogiri 1.6.7.2-java (the latest) and running a multi-threaded puma rails environment.

The stack trace is always the same - lots of stabilzeAttrValue lines and then a lot of xerces isNormalized lines before it eventually overflows.

I assume this is coming from a line in our code where we call `page = Nokogiri::HTML(response.body)` although the bottom of the trace is always cut off in our logs.

I am working on reproducing it, but wanted to go ahead and open an issue in case anyone has other ideas on how to diagnose, solve, or workaround this issue.

```
java.lang.StackOverflowError: null
       <snip lots more isNormalized lines/>        
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.NodeImpl.isNormalized(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.AttributeMap.setNamedItem(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.DeferredElementImpl.synchronizeData(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.dom.ElementImpl.hasAttributes(Unknown Source) ~[xercesImpl.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:135) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
        at nokogiri.HtmlDocument.stabilzeAttrValue(HtmlDocument.java:150) ~[nokogiri.jar:na]
       <snip lots more stabilzeAttrValue lines/>
```

**Comment by jeremyhaile** [comment]
I figured this out. Apparently I was trying to parse an mp4 file with Nokogiri. 

I'm not sure whether this should be considered a bug since I don't think it should StackOverflow in any case...but I'm going to close this issue.

**Comment by jeremyhaile** [comment]
For reference, here is the URL I was able to reproduce with: http://vb.hudl.com/p-dl/38794001-2548cc5b-3a5a-44df-acac-c1f4385bee97_2.mp4
