### ISSUE TITLE
SIGSEGV on ruby 2.1.8 with reproducible code

### ISSUE THREAD

**Issue by brodock** [sparklemotion/nokogiri#1477]
I understand that the code below is wrong, as Attr constructor expects a document instead of an element, but it should not crash the MRI itself and should be handled correctly (maybe throw an exception).

``` ruby
document = Nokogiri::XML::Document.new
element = Nokogiri::XML::Element.new('use', document)
attr = Nokogiri::XML::Attr.new(element, 'xlink:href')
```

Output: 

```
irb(main):001:0> require 'nokogiri'
=> true
irb(main):002:0> document = Nokogiri::XML::Document.new
=> #<Nokogiri::XML::Document:0x3ff48a01958c name="document">
irb(main):003:0> element = Nokogiri::XML::Element.new('use', document)
=> #<Nokogiri::XML::Element:0x3ff48a49f548 name="use">
irb(main):004:0> attr = Nokogiri::XML::Attr.new(element, 'xlink:href')
(irb):4: [BUG] Segmentation fault at 0x00000000000040
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-darwin15.0]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

-- Control frame information -----------------------------------------------
c:0019 p:---- s:0078 e:000077 CFUNC  :new
c:0018 p:0019 s:0073 E:0017b0 EVAL   (irb):4 [FINISH]
c:0017 p:---- s:0070 e:000069 CFUNC  :eval
c:0016 p:0024 s:0063 e:000062 METHOD /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/workspace.rb:86
c:0015 p:0025 s:0056 e:000054 METHOD /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/context.rb:380
c:0014 p:0022 s:0050 e:000049 BLOCK  /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:492
c:0013 p:0040 s:0042 e:000041 METHOD /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:624
c:0012 p:0009 s:0037 e:000036 BLOCK  /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:489
c:0011 p:0118 s:0033 e:000032 BLOCK  /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/ruby-lex.rb:247 [FINISH]
c:0010 p:---- s:0030 e:000029 CFUNC  :loop
c:0009 p:0007 s:0027 e:000026 BLOCK  /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/ruby-lex.rb:233 [FINISH]
c:0008 p:---- s:0025 e:000024 CFUNC  :catch
c:0007 p:0015 s:0021 e:000020 METHOD /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/ruby-lex.rb:232
c:0006 p:0030 s:0018 E:000148 METHOD /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:488
c:0005 p:0008 s:0015 e:000014 BLOCK  /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:397 [FINISH]
c:0004 p:---- s:0013 e:000012 CFUNC  :catch
c:0003 p:0143 s:0009 E:000428 METHOD /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:396
c:0002 p:0021 s:0004 E:001038 EVAL   /Users/brodock/.rvm/rubies/ruby-2.1.8/bin/irb:11 [FINISH]
c:0001 p:0000 s:0002 E:001d78 TOP    [FINISH]

/Users/brodock/.rvm/rubies/ruby-2.1.8/bin/irb:11:in `<main>'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:396:in `start'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:396:in `catch'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:397:in `block in start'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:488:in `eval_input'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `each_top_level_statement'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `catch'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `loop'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/ruby-lex.rb:247:in `block (2 levels) in each_top_level_statement'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:489:in `block in eval_input'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:624:in `signal_status'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb:492:in `block (2 levels) in eval_input'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/context.rb:380:in `evaluate'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/workspace.rb:86:in `evaluate'
/Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/workspace.rb:86:in `eval'
(irb):4:in `irb_binding'
(irb):4:in `new'

-- C level backtrace information -------------------------------------------
0   libruby.2.1.0.dylib                 0x00000001067c2fda rb_vm_bugreport + 138
1   libruby.2.1.0.dylib                 0x00000001066768df report_bug + 303
2   libruby.2.1.0.dylib                 0x00000001066767a4 rb_bug + 180
3   libruby.2.1.0.dylib                 0x0000000106744ebc sigsegv + 156
4   libsystem_platform.dylib            0x00007fff98b9c52a _sigtramp + 26
5   nokogiri.bundle                     0x0000000106ec1cb1 xmlDictLookup + 113
6   ???                                 0x00007fff595cf0b0 0x0 + 140734692651184

-- Other runtime information -----------------------------------------------

* Loaded script: irb

* Loaded features:

    0 enumerator.so
    1 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/x86_64-darwin15.0/enc/encdb.bundle
    2 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/x86_64-darwin15.0/enc/trans/transdb.bundle
    3 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/x86_64-darwin15.0/rbconfig.rb
    4 thread.rb
    5 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/x86_64-darwin15.0/thread.bundle
    6 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/compatibility.rb
    7 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/defaults.rb
    8 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/deprecate.rb
    9 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/errors.rb
   10 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/version.rb
   11 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/requirement.rb
   12 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/platform.rb
   13 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/basic_specification.rb
   14 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/stub_specification.rb
   15 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/util/list.rb
   16 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/x86_64-darwin15.0/stringio.bundle
   17 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb
   18 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/exceptions.rb
   19 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb
   20 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/monitor.rb
   21 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb
   22 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems.rb
   23 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/e2mmap.rb
   24 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/init.rb
   25 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/workspace.rb
   26 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/inspector.rb
   27 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/context.rb
   28 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/extend-command.rb
   29 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/output-method.rb
   30 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/notifier.rb
   31 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/slex.rb
   32 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/ruby-token.rb
   33 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/ruby-lex.rb
   34 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/src_encoding.rb
   35 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/magic-file.rb
   36 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/x86_64-darwin15.0/readline.bundle
   37 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/input-method.rb
   38 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb/locale.rb
   39 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/irb.rb
   40 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/path_support.rb
   41 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb
   42 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/nokogiri.bundle
   43 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/version.rb
   44 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/syntax_error.rb
   45 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/pp/node.rb
   46 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/pp/character_data.rb
   47 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/pp.rb
   48 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/parse_options.rb
   49 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/sax/document.rb
   50 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/sax/parser_context.rb
   51 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/sax/parser.rb
   52 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/sax/push_parser.rb
   53 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/sax.rb
   54 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/searchable.rb
   55 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node/save_options.rb
   56 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node.rb
   57 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/attribute_decl.rb
   58 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/element_decl.rb
   59 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/element_content.rb
   60 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/character_data.rb
   61 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/namespace.rb
   62 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/attr.rb
   63 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/dtd.rb
   64 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/cdata.rb
   65 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/text.rb
   66 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/document.rb
   67 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/document_fragment.rb
   68 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/processing_instruction.rb
   69 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/node_set.rb
   70 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/syntax_error.rb
   71 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/xpath/syntax_error.rb
   72 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/xpath.rb
   73 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/xpath_context.rb
   74 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/builder.rb
   75 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/reader.rb
   76 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/notation.rb
   77 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/entity_decl.rb
   78 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/schema.rb
   79 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml/relax_ng.rb
   80 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xml.rb
   81 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xslt/stylesheet.rb
   82 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/xslt.rb
   83 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/html/entity_lookup.rb
   84 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/html/document.rb
   85 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/html/document_fragment.rb
   86 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/html/sax/parser_context.rb
   87 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/html/sax/parser.rb
   88 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/html/sax/push_parser.rb
   89 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/html/element_description.rb
   90 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/html/element_description_defaults.rb
   91 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/html.rb
   92 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/decorators/slop.rb
   93 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/css/node.rb
   94 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/css/xpath_visitor.rb
   95 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/x86_64-darwin15.0/racc/cparse.bundle
   96 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/racc/parser.rb
   97 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/css/parser_extras.rb
   98 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/css/parser.rb
   99 /Users/brodock/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/x86_64-darwin15.0/strscan.bundle
  100 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/css/tokenizer.rb
  101 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/css/syntax_error.rb
  102 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/css.rb
  103 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri/html/builder.rb
  104 /Users/brodock/.rvm/gems/ruby-2.1.8/gems/nokogiri-1.6.7.2/lib/nokogiri.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html
```

**Comment by flavorjones** [comment]
Thanks for reporting for this! We'll take a look.
