### ISSUE TITLE
infrequent libxml-ruby segfault

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1481]
Still seeing segfaults once in a while due to libxml-ruby conflicts ...

Running Nokogiri 1.6.8.rc3 with libxml-ruby 2.8.0:

```
$ bundle exec rake test:libxml-ruby

install -c tmp/x86_64-linux/nokogiri/2.3.0/nokogiri.so lib/nokogiri/nokogiri.so
cp tmp/x86_64-linux/nokogiri/2.3.0/nokogiri.so tmp/x86_64-linux/stage/lib/nokogiri/nokogiri.so
/home/flavorjones/code/oss/nokogiri/Rakefile:322: --- running tests with libxml-ruby loaded ---
/home/flavorjones/.rvm/rubies/ruby-2.3.0/bin/ruby -w -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/test_convert_xpath.rb"; require "test/test_soap4r_sax.rb"; require "test/test_memory_leak.rb"; require "test/xml/test_dtd.rb"; require "test/xml/test_parse_options.rb"; require "test/xml/test_document.rb"; require "test/xml/test_namespace.rb"; require "test/xml/test_schema.rb"; require "test/xml/test_element_content.rb"; require "test/xml/test_attr.rb"; require "test/xml/test_c14n.rb"; require "test/xml/test_node_encoding.rb"; require "test/xml/test_builder.rb"; require "test/xml/test_entity_reference.rb"; require "test/xml/test_document_fragment.rb"; require "test/xml/test_unparented_node.rb"; require "test/xml/sax/test_parser.rb"; require "test/xml/sax/test_push_parser.rb"; require "test/xml/sax/test_parser_context.rb"; require "test/xml/test_attribute_decl.rb"; require "test/xml/test_comment.rb"; require "test/xml/test_node_attributes.rb"; require "test/xml/test_cdata.rb"; require "test/xml/test_node_inheritance.rb"; require "test/xml/test_reader_encoding.rb"; require "test/xml/node/test_save_options.rb"; require "test/xml/node/test_subclass.rb"; require "test/xml/test_xpath.rb"; require "test/xml/test_reader.rb"; require "test/xml/test_node.rb"; require "test/xml/test_text.rb"; require "test/xml/test_element_decl.rb"; require "test/xml/test_relax_ng.rb"; require "test/xml/test_processing_instruction.rb"; require "test/xml/test_node_set.rb"; require "test/xml/test_xinclude.rb"; require "test/xml/test_node_reparenting.rb"; require "test/xml/test_dtd_encoding.rb"; require "test/xml/test_syntax_error.rb"; require "test/xml/test_entity_decl.rb"; require "test/xml/test_document_encoding.rb"; require "test/test_encoding_handler.rb"; require "test/test_nokogiri.rb"; require "test/decorators/test_slop.rb"; require "test/xslt/test_exception_handling.rb"; require "test/xslt/test_custom_functions.rb"; require "test/html/test_document.rb"; require "test/html/test_node_encoding.rb"; require "test/html/test_element_description.rb"; require "test/html/test_builder.rb"; require "test/html/test_document_fragment.rb"; require "test/html/sax/test_parser.rb"; require "test/html/sax/test_push_parser.rb"; require "test/html/sax/test_parser_context.rb"; require "test/html/test_node.rb"; require "test/html/test_document_encoding.rb"; require "test/html/test_named_characters.rb"; require "test/namespaces/test_namespaces_aliased_default.rb"; require "test/namespaces/test_namespaces_in_builder_doc.rb"; require "test/namespaces/test_namespaces_in_cloned_doc.rb"; require "test/namespaces/test_additional_namespaces_in_builder_doc.rb"; require "test/namespaces/test_namespaces_in_created_doc.rb"; require "test/namespaces/test_namespaces_in_parsed_doc.rb"; require "test/namespaces/test_namespaces_preservation.rb"; require "test/test_xslt_transforms.rb"; require "test/css/test_xpath_visitor.rb"; require "test/css/test_tokenizer.rb"; require "test/css/test_parser.rb"; require "test/css/test_nthiness.rb"; require "test/test_css_cache.rb"' -- 
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/libxml-ruby-2.8.0/lib/libxml/schema/type.rb:8: warning: method redefined; discarding old annotation
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/libxml-ruby-2.8.0/lib/libxml/schema/element.rb:18: warning: method redefined; discarding old annotation
/home/flavorjones/code/oss/nokogiri/test/helper.rb:12: loaded libxml-ruby '2.8.0'
/home/flavorjones/code/oss/nokogiri/test/helper.rb:15: version info: {"warnings"=>[], "nokogiri"=>"1.6.8.rc3", "ruby"=>{"version"=>"2.3.0", "platform"=>"x86_64-linux", "description"=>"ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]", "engine"=>"ruby"}, "libxml"=>{"binding"=>"extension", "source"=>"packaged", "libxml2_path"=>"/home/flavorjones/code/oss/nokogiri/ports/x86_64-pc-linux-gnu/libxml2/2.9.4", "libxslt_path"=>"/home/flavorjones/code/oss/nokogiri/ports/x86_64-pc-linux-gnu/libxslt/1.1.29", "libxml2_patches"=>[], "libxslt_patches"=>[], "compiled"=>"2.9.4", "loaded"=>"2.9.4"}}
Run options: --seed 37722

# Running:

...................................................................................................................../home/flavorjones/code/oss/nokogiri/lib/nokogiri/xml/pp/node.rb:8: [BUG] Segmentation fault at 0x00000000000018
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0029 p:---- s:0121 e:000120 CFUNC  :prefix
c:0028 p:0012 s:0118 e:000117 BLOCK  /home/flavorjones/code/oss/nokogiri/lib/nokogiri/xml/pp/node.rb:8 [FINISH]
c:0027 p:---- s:0114 e:000113 CFUNC  :reject
c:0026 p:0012 s:0111 e:000110 METHOD /home/flavorjones/code/oss/nokogiri/lib/nokogiri/xml/pp/node.rb:6
c:0025 p:0009 s:0107 e:000106 BLOCK  /home/flavorjones/code/oss/nokogiri/test/namespaces/test_namespaces_in_parsed_doc.rb:75 [FINISH]
c:0024 p:---- s:0104 e:000103 CFUNC  :each
c:0023 p:0088 s:0101 e:000100 METHOD /home/flavorjones/code/oss/nokogiri/test/namespaces/test_namespaces_in_parsed_doc.rb:74
c:0022 p:0029 s:0096 e:000095 BLOCK  /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:108
c:0021 p:0006 s:0094 e:000093 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:205
c:0020 p:0009 s:0090 e:000089 BLOCK  /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:105
c:0019 p:0020 s:0088 e:000087 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:256
c:0018 p:0009 s:0084 e:000083 BLOCK  /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:104
c:0017 p:0037 s:0082 e:000081 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:331
c:0016 p:0041 s:0075 E:002688 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:276
c:0015 p:0009 s:0069 E:0006d0 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:103
c:0014 p:0014 s:0066 e:000065 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:778
c:0013 p:0020 s:0060 e:000058 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:305
c:0012 p:0014 s:0053 e:000052 BLOCK  /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:293 [FINISH]
c:0011 p:---- s:0050 e:000049 CFUNC  :each
c:0010 p:0010 s:0047 e:000046 BLOCK  /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:292
c:0009 p:0037 s:0045 e:000044 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:331
c:0008 p:0024 s:0038 E:000ea8 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:318
c:0007 p:0085 s:0032 E:0008e0 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:291
c:0006 p:0013 s:0025 e:000024 BLOCK  /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:152 [FINISH]
c:0005 p:---- s:0022 e:000021 CFUNC  :map
c:0004 p:0042 s:0019 e:000018 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:152
c:0003 p:0158 s:0011 e:000010 METHOD /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:129
c:0002 p:0071 s:0005 E:0026c8 BLOCK  /home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:56 [FINISH]
c:0001 p:0000 s:0002 E:001d20 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:56:in `block in autorun'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:129:in `run'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:152:in `__run'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:152:in `map'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:152:in `block in __run'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:291:in `run'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:318:in `with_info_handler'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:331:in `on_signal'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:292:in `block in run'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:292:in `each'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:293:in `block (2 levels) in run'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:305:in `run_one_method'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:778:in `run_one_method'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:103:in `run'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:276:in `with_info_handler'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest.rb:331:in `on_signal'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:104:in `block in run'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:256:in `time_it'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:105:in `block (2 levels) in run'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:205:in `capture_exceptions'
/home/flavorjones/.rvm/gems/ruby-2.3.0/gems/minitest-5.8.4/lib/minitest/test.rb:108:in `block (3 levels) in run'
/home/flavorjones/code/oss/nokogiri/test/namespaces/test_namespaces_in_parsed_doc.rb:74:in `test_namespaces_under_memory_pressure_issue1155'
/home/flavorjones/code/oss/nokogiri/test/namespaces/test_namespaces_in_parsed_doc.rb:74:in `each'
/home/flavorjones/code/oss/nokogiri/test/namespaces/test_namespaces_in_parsed_doc.rb:75:in `block in test_namespaces_under_memory_pressure_issue1155'
/home/flavorjones/code/oss/nokogiri/lib/nokogiri/xml/pp/node.rb:6:in `inspect'
/home/flavorjones/code/oss/nokogiri/lib/nokogiri/xml/pp/node.rb:6:in `reject'
/home/flavorjones/code/oss/nokogiri/lib/nokogiri/xml/pp/node.rb:8:in `block in inspect'
/home/flavorjones/code/oss/nokogiri/lib/nokogiri/xml/pp/node.rb:8:in `prefix'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f47dfc716e7 RBP: 0x00007f47e42aa910 RSP: 0x00007ffe4dce8f70
 RAX: 0x0000000000000000 RBX: 0x0000000000000000 RCX: 0x00007f47e41ab3c8
 RDX: 0x000000000000000c RDI: 0x00000000015b4b58 RSI: 0x000000000000000c
  R8: 0x00007ffe4dce90c0  R9: 0x0000000000000001 R10: 0x0000000000000000
 R11: 0x0000000000000003 R12: 0x00000000019e62f0 R13: 0x0000000000000000
 R14: 0x00000000011a2920 R15: 0x00000000015b4b58 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_vm_bugreport+0x51f) [0x7f47e3db44cf] vm_dump.c:688
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_bug_context+0xd0) [0x7f47e3c3d770] error.c:435
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(sigsegv+0x3e) [0x7f47e3d1d0de] signal.c:890
/lib/x86_64-linux-gnu/libc.so.6 [0x7f47e382fcb0]
/home/flavorjones/code/oss/nokogiri/lib/nokogiri/nokogiri.so(prefix+0x17) [0x7f47dfc716e7] /home/flavorjones/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/ruby/ruby.h:1393
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_call_cfunc+0xf6) [0x7f47e3d9b806] vm_insnhelper.c:1638
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_call_method+0xe3) [0x7f47e3db2a63] vm_insnhelper.c:2172
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_call_opt_send+0x1d4) [0x7f47e3db3124] vm_insnhelper.c:1846
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_exec_core+0x20f9) [0x7f47e3da6519] insns.def:995
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_exec+0x81) [0x7f47e3daa091] vm.c:1645
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_yield+0x21f) [0x7f47e3dab5af] vm.c:966
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_ary_reject+0x44) [0x7f47e3bf5f84] array.c:3163
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_call_cfunc+0xf6) [0x7f47e3d9b806] vm_insnhelper.c:1638
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_exec_core+0x2026) [0x7f47e3da6446] insns.def:964
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_exec+0x81) [0x7f47e3daa091] vm.c:1645
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_yield+0x21f) [0x7f47e3dab5af] vm.c:966
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_ary_each+0x3d) [0x7f47e3bef44d] array.c:1815
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_call_cfunc+0xf6) [0x7f47e3d9b806] vm_insnhelper.c:1638
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_call_method+0xe3) [0x7f47e3db2a63] vm_insnhelper.c:2172
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_exec_core+0x2026) [0x7f47e3da6446] insns.def:964
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_exec+0x81) [0x7f47e3daa091] vm.c:1645
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_yield+0x21f) [0x7f47e3dab5af] vm.c:966
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_ary_each+0x3d) [0x7f47e3bef44d] array.c:1815
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_call_cfunc+0xf6) [0x7f47e3d9b806] vm_insnhelper.c:1638
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_exec_core+0x2026) [0x7f47e3da6446] insns.def:964
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_exec+0x81) [0x7f47e3daa091] vm.c:1645
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_yield+0x21f) [0x7f47e3dab5af] vm.c:966
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_ary_collect+0x4d) [0x7f47e3bf619d] array.c:2733
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_call_cfunc+0xf6) [0x7f47e3d9b806] vm_insnhelper.c:1638
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_call_method+0xe3) [0x7f47e3db2a63] vm_insnhelper.c:2172
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_exec_core+0x2026) [0x7f47e3da6446] insns.def:964
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_exec+0x81) [0x7f47e3daa091] vm.c:1645
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(invoke_block_from_c_0+0x161) [0x7f47e3daabd1] vm.c:966
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(vm_invoke_proc+0xb8) [0x7f47e3daaca8] vm.c:991
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_proc_call+0x42) [0x7f47e3c4d1c2] proc.c:814
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(rb_exec_end_proc+0x13b) [0x7f47e3c475ab] eval_jump.c:107
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(ruby_finalize_0+0x88) [0x7f47e3c476f8] eval.c:121
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(ruby_cleanup+0x234) [0x7f47e3c47ad4] eval.c:180
/home/flavorjones/.rvm/rubies/ruby-2.3.0/lib/libruby.so.2.3(ruby_run_node+0x23) [0x7f47e3c47ee3] eval.c:301
/home/flavorjones/.rvm/rubies/ruby-2.3.0/bin/ruby(main+0x4b) [0x40089b] main.c:36
```

**Comment by flavorjones** [comment]
Haven't seen this in a long time. See https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri/jobs/ruby-libxmlruby-system and https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri/jobs/ruby-libxmlruby-vendored.

Closing.
