### ISSUE TITLE
Build nokogiri on Windows 7

### ISSUE THREAD

**Issue by gwang** [sparklemotion/nokogiri#1489]
I have a need to install Nokogiri on a custom build of ruby 2.3.0, which has DevKit installed. I am following instructions on [this page](http://www.mlte.de/ruby-win7) to install nokogiri, but always failed because of nokogiri cannot locate the needed libs such `libiconv`.  I am suspecting that the `--with-*-dir` options are ignore, or could it be that my libs aren't installed correctly. Please help!

```
c:\usr\local.2013\bin\gem install nokogiri --platform=ruby --version=1.6.1 -N -- --with-iconv-dir=C:\usr\libiconv --with-xml2-dir=C:\usr\libxml2 --with-xslt-dir=C:\usr\libxslt

Fetching: mini_portile-0.5.3.gem (100%)
Successfully installed mini_portile-0.5.3
Fetching: nokogiri-1.6.1.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '--with-iconv-dir=C:\usr\libiconv --with-xml2-dir=C:\usr\libxml2 --
with-xslt-dir=C:\usr\libxslt'
This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: c:/usr/local.2013/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.1/ext/nokogiri
c:/usr/local.2013/bin/ruby.exe -r ./siteconf20160615-14048-115a6mf.rb extconf.rb --with-iconv-dir=C:
\usr\libiconv --with-xml2-dir=C:\usr\libxml2 --with-xslt-dir=C:\usr\libxslt
checking for libxml/parser.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --srcdir=.
        --curdir
        --ruby=c:/usr/local.2013/bin/ruby
        --with-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --with-iconv-dir
        --with-iconv-include
        --without-iconv-include=${iconv-dir}/include
        --with-iconv-lib
        --without-iconv-lib=${iconv-dir}/lib
        --with-xml2-dir
        --with-xml2-include
        --without-xml2-include=${xml2-dir}/include
        --with-xml2-lib
        --without-xml2-lib=${xml2-dir}/lib
        --with-xslt-dir
        --with-xslt-include
        --without-xslt-include=${xslt-dir}/include
        --with-xslt-lib
        --without-xslt-lib=${xslt-dir}/lib
        --with-libxslt-config
        --without-libxslt-config
        --with-pkg-config
        --without-pkg-config
        --with-libxml-2.0-config
        --without-libxml-2.0-config
        --with-pkg-config
        --without-pkg-config
        --with-libiconv-config
        --without-libiconv-config
        --with-pkg-config
        --without-pkg-config
c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executa
ble file. (RuntimeError)
You have to install development tools first.
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:571:in `block in try_compile'
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:524:in `with_werror'
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:571:in `try_compile'
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:1144:in `block in find_header'
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from c:/usr/local.2013/lib/ruby/2.3.0/mkmf.rb:1143:in `find_header'
        from extconf.rb:166:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  c:/usr/local.2013/lib/ruby/gems/2.3.0/extensions/x64-mswin64-120/2.3.0/nokogiri-1.6.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in c:/usr/local.2013/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.1 for ins
pection.
Results logged to c:/usr/local.2013/lib/ruby/gems/2.3.0/extensions/x64-mswin64-120/2.3.0/nokogiri-1.
6.1/gem_make.out
```
the `mkmf.log` file is below:

```
"cl -nologo -Feconftest -Ic:/usr/local.2013/include/ruby-2.3.0/x64-mswin64_120 -Ic:/usr/local.2013/include/ruby-2.3.0/ruby/backward -Ic:/usr/local.2013/include/ruby-2.3.0 -I. -Ic:/usr/local.2013/include/ruby-2.3.0  -D_WIN32_WINNT=0x0600   -MD -Zi -W2 -wd4100 -wd4127 -wd4210 -wd4214 -wd4255 -wd4574  -wd4668 -wd4710 -wd4711 -wd4820 -wd4996  -we4028 -we4142 -O2sy-  -Zm600  conftest.c   x64-msvcr120-ruby230.lib  user32.lib advapi32.lib shell32.lib ws2_32.lib iphlpapi.lib imagehlp.lib shlwapi.lib    -link -incremental:no -debug -opt:ref -opt:icf   -libpath:. -libpath:c:/usr/local.2013/lib "
conftest.c
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #ifndef WIN32_LEAN_AND_MEAN
 4: #define WIN32_LEAN_AND_MEAN
 5: #endif /* WIN32_LEAN_AND_MEAN */
 6: #ifndef WIN32
 7: #define WIN32
 8: #endif /* WIN32 */
 9: #include <winsock2.h>
10: #include <ws2tcpip.h>
11: #include <windows.h>
12: int main(int argc, char **argv)
13: {
14:   return 0;
15: }
/* end */

"cl -nologo -Ic:/usr/local.2013/include/ruby-2.3.0/x64-mswin64_120 -Ic:/usr/local.2013/include/ruby-2.3.0/ruby/backward -Ic:/usr/local.2013/include/ruby-2.3.0 -I.  -D_WIN32_WINNT=0x0600   -MD -Zi -W2 -wd4100 -wd4127 -wd4210 -wd4214 -wd4255 -wd4574  -wd4668 -wd4710 -wd4711 -wd4820 -wd4996  -we4028 -we4142 -O2sy-  -Zm600    -WX -c conftest.c"
conftest.c
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #ifndef WIN32_LEAN_AND_MEAN
 4: #define WIN32_LEAN_AND_MEAN
 5: #endif /* WIN32_LEAN_AND_MEAN */
 6: #ifndef WIN32
 7: #define WIN32
 8: #endif /* WIN32 */
 9: #include <winsock2.h>
10: #include <ws2tcpip.h>
11: #include <windows.h>
12: int main() {return 0;}
/* end */

package configuration for libexslt is not found
have_package: checking for libexslt... -------------------- no

--------------------

have_func: checking for xmlParseDoc() in libxml/parser.h... -------------------- no

"cl -nologo -Feconftest -Ic:/usr/local.2013/include/ruby-2.3.0/x64-mswin64_120 -Ic:/usr/local.2013/include/ruby-2.3.0/ruby/backward -Ic:/usr/local.2013/include/ruby-2.3.0 -I. -Ic:/usr/local.2013/include/ruby-2.3.0 -IC:/usr/libxslt/include -IC:/usr/libxml2/include -IC:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/include  -D_WIN32_WINNT=0x0600   -MD -Zi -W2 -wd4100 -wd4127 -wd4210 -wd4214 -wd4255 -wd4574  -wd4668 -wd4710 -wd4711 -wd4820 -wd4996  -we4028 -we4142 -O2sy-  -Zm600  -DXP_WIN -DXP_WIN32 -DUSE_INCLUDED_VASPRINTF conftest.c   x64-msvcr120-ruby230.lib  user32.lib advapi32.lib shell32.lib ws2_32.lib iphlpapi.lib imagehlp.lib shlwapi.lib    -link -incremental:no -debug -opt:ref -opt:icf   -libpath:. -libpath:c:/usr/local.2013/lib -libpath:C:/usr/libxslt/lib -libpath:C:/usr/libxml2/lib -libpath:C:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/lib "
conftest.c
C:\usr\libxml2\include\libxml/encoding.h(28) : fatal error C1083: Cannot open include file: 'iconv.h': No such file or directory
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #ifndef WIN32_LEAN_AND_MEAN
 4: #define WIN32_LEAN_AND_MEAN
 5: #endif /* WIN32_LEAN_AND_MEAN */
 6: #ifndef WIN32
 7: #define WIN32
 8: #endif /* WIN32 */
 9: #include <winsock2.h>
10: #include <ws2tcpip.h>
11: #include <windows.h>
12: #include <libxml/parser.h>
13: 
14: /*top*/
15: extern int t(void);
16: int main(int argc, char **argv)
17: {
18:   if (argc > 1000000) {
19:     printf("%p", &t);
20:   }
21: 
22:   return 0;
23: }
24: int t(void) { void ((*volatile p)()); p = (void ((*)()))xmlParseDoc; return !p; }
/* end */

"cl -nologo -Feconftest -Ic:/usr/local.2013/include/ruby-2.3.0/x64-mswin64_120 -Ic:/usr/local.2013/include/ruby-2.3.0/ruby/backward -Ic:/usr/local.2013/include/ruby-2.3.0 -I. -Ic:/usr/local.2013/include/ruby-2.3.0 -IC:/usr/libxslt/include -IC:/usr/libxml2/include -IC:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/include  -D_WIN32_WINNT=0x0600   -MD -Zi -W2 -wd4100 -wd4127 -wd4210 -wd4214 -wd4255 -wd4574  -wd4668 -wd4710 -wd4711 -wd4820 -wd4996  -we4028 -we4142 -O2sy-  -Zm600  -DXP_WIN -DXP_WIN32 -DUSE_INCLUDED_VASPRINTF conftest.c   x64-msvcr120-ruby230.lib  user32.lib advapi32.lib shell32.lib ws2_32.lib iphlpapi.lib imagehlp.lib shlwapi.lib    -link -incremental:no -debug -opt:ref -opt:icf   -libpath:. -libpath:c:/usr/local.2013/lib -libpath:C:/usr/libxslt/lib -libpath:C:/usr/libxml2/lib -libpath:C:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/lib "
conftest.c
C:\usr\libxml2\include\libxml/encoding.h(28) : fatal error C1083: Cannot open include file: 'iconv.h': No such file or directory
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #ifndef WIN32_LEAN_AND_MEAN
 4: #define WIN32_LEAN_AND_MEAN
 5: #endif /* WIN32_LEAN_AND_MEAN */
 6: #ifndef WIN32
 7: #define WIN32
 8: #endif /* WIN32 */
 9: #include <winsock2.h>
10: #include <ws2tcpip.h>
11: #include <windows.h>
12: #include <libxml/parser.h>
13: 
14: /*top*/
15: extern int t(void);
16: int main(int argc, char **argv)
17: {
18:   if (argc > 1000000) {
19:     printf("%p", &t);
20:   }
21: 
22:   return 0;
23: }
24: extern void xmlParseDoc();
25: int t(void) { xmlParseDoc(); return 0; }
/* end */

--------------------

have_library: checking for xmlParseDoc() in xml2.lib... -------------------- no

"cl -nologo -Feconftest -Ic:/usr/local.2013/include/ruby-2.3.0/x64-mswin64_120 -Ic:/usr/local.2013/include/ruby-2.3.0/ruby/backward -Ic:/usr/local.2013/include/ruby-2.3.0 -I. -Ic:/usr/local.2013/include/ruby-2.3.0 -IC:/usr/libxslt/include -IC:/usr/libxml2/include -IC:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/include  -D_WIN32_WINNT=0x0600   -MD -Zi -W2 -wd4100 -wd4127 -wd4210 -wd4214 -wd4255 -wd4574  -wd4668 -wd4710 -wd4711 -wd4820 -wd4996  -we4028 -we4142 -O2sy-  -Zm600  -DXP_WIN -DXP_WIN32 -DUSE_INCLUDED_VASPRINTF conftest.c   x64-msvcr120-ruby230.lib xml2.lib  user32.lib advapi32.lib shell32.lib ws2_32.lib iphlpapi.lib imagehlp.lib shlwapi.lib    -link -incremental:no -debug -opt:ref -opt:icf   -libpath:. -libpath:c:/usr/local.2013/lib -libpath:C:/usr/libxslt/lib -libpath:C:/usr/libxml2/lib -libpath:C:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/lib "
conftest.c
C:\usr\libxml2\include\libxml/encoding.h(28) : fatal error C1083: Cannot open include file: 'iconv.h': No such file or directory
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #ifndef WIN32_LEAN_AND_MEAN
 4: #define WIN32_LEAN_AND_MEAN
 5: #endif /* WIN32_LEAN_AND_MEAN */
 6: #ifndef WIN32
 7: #define WIN32
 8: #endif /* WIN32 */
 9: #include <winsock2.h>
10: #include <ws2tcpip.h>
11: #include <windows.h>
12: #include <libxml/parser.h>
13: 
14: /*top*/
15: extern int t(void);
16: int main(int argc, char **argv)
17: {
18:   if (argc > 1000000) {
19:     printf("%p", &t);
20:   }
21: 
22:   return 0;
23: }
24: int t(void) { void ((*volatile p)()); p = (void ((*)()))xmlParseDoc; return !p; }
/* end */

"cl -nologo -Feconftest -Ic:/usr/local.2013/include/ruby-2.3.0/x64-mswin64_120 -Ic:/usr/local.2013/include/ruby-2.3.0/ruby/backward -Ic:/usr/local.2013/include/ruby-2.3.0 -I. -Ic:/usr/local.2013/include/ruby-2.3.0 -IC:/usr/libxslt/include -IC:/usr/libxml2/include -IC:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/include  -D_WIN32_WINNT=0x0600   -MD -Zi -W2 -wd4100 -wd4127 -wd4210 -wd4214 -wd4255 -wd4574  -wd4668 -wd4710 -wd4711 -wd4820 -wd4996  -we4028 -we4142 -O2sy-  -Zm600  -DXP_WIN -DXP_WIN32 -DUSE_INCLUDED_VASPRINTF conftest.c   x64-msvcr120-ruby230.lib xml2.lib  user32.lib advapi32.lib shell32.lib ws2_32.lib iphlpapi.lib imagehlp.lib shlwapi.lib    -link -incremental:no -debug -opt:ref -opt:icf   -libpath:. -libpath:c:/usr/local.2013/lib -libpath:C:/usr/libxslt/lib -libpath:C:/usr/libxml2/lib -libpath:C:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/lib "
conftest.c
C:\usr\libxml2\include\libxml/encoding.h(28) : fatal error C1083: Cannot open include file: 'iconv.h': No such file or directory
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #ifndef WIN32_LEAN_AND_MEAN
 4: #define WIN32_LEAN_AND_MEAN
 5: #endif /* WIN32_LEAN_AND_MEAN */
 6: #ifndef WIN32
 7: #define WIN32
 8: #endif /* WIN32 */
 9: #include <winsock2.h>
10: #include <ws2tcpip.h>
11: #include <windows.h>
12: #include <libxml/parser.h>
13: 
14: /*top*/
15: extern int t(void);
16: int main(int argc, char **argv)
17: {
18:   if (argc > 1000000) {
19:     printf("%p", &t);
20:   }
21: 
22:   return 0;
23: }
24: extern void xmlParseDoc();
25: int t(void) { xmlParseDoc(); return 0; }
/* end */

--------------------

have_library: checking for xmlParseDoc() in libxml2.lib... -------------------- no

"cl -nologo -Feconftest -Ic:/usr/local.2013/include/ruby-2.3.0/x64-mswin64_120 -Ic:/usr/local.2013/include/ruby-2.3.0/ruby/backward -Ic:/usr/local.2013/include/ruby-2.3.0 -I. -Ic:/usr/local.2013/include/ruby-2.3.0 -IC:/usr/libxslt/include -IC:/usr/libxml2/include -IC:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/include  -D_WIN32_WINNT=0x0600   -MD -Zi -W2 -wd4100 -wd4127 -wd4210 -wd4214 -wd4255 -wd4574  -wd4668 -wd4710 -wd4711 -wd4820 -wd4996  -we4028 -we4142 -O2sy-  -Zm600  -DXP_WIN -DXP_WIN32 -DUSE_INCLUDED_VASPRINTF conftest.c   x64-msvcr120-ruby230.lib libxml2.lib  user32.lib advapi32.lib shell32.lib ws2_32.lib iphlpapi.lib imagehlp.lib shlwapi.lib    -link -incremental:no -debug -opt:ref -opt:icf   -libpath:. -libpath:c:/usr/local.2013/lib -libpath:C:/usr/libxslt/lib -libpath:C:/usr/libxml2/lib -libpath:C:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/lib "
conftest.c
C:\usr\libxml2\include\libxml/encoding.h(28) : fatal error C1083: Cannot open include file: 'iconv.h': No such file or directory
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #ifndef WIN32_LEAN_AND_MEAN
 4: #define WIN32_LEAN_AND_MEAN
 5: #endif /* WIN32_LEAN_AND_MEAN */
 6: #ifndef WIN32
 7: #define WIN32
 8: #endif /* WIN32 */
 9: #include <winsock2.h>
10: #include <ws2tcpip.h>
11: #include <windows.h>
12: #include <libxml/parser.h>
13: 
14: /*top*/
15: extern int t(void);
16: int main(int argc, char **argv)
17: {
18:   if (argc > 1000000) {
19:     printf("%p", &t);
20:   }
21: 
22:   return 0;
23: }
24: int t(void) { void ((*volatile p)()); p = (void ((*)()))xmlParseDoc; return !p; }
/* end */

"cl -nologo -Feconftest -Ic:/usr/local.2013/include/ruby-2.3.0/x64-mswin64_120 -Ic:/usr/local.2013/include/ruby-2.3.0/ruby/backward -Ic:/usr/local.2013/include/ruby-2.3.0 -I. -Ic:/usr/local.2013/include/ruby-2.3.0 -IC:/usr/libxslt/include -IC:/usr/libxml2/include -IC:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/include  -D_WIN32_WINNT=0x0600   -MD -Zi -W2 -wd4100 -wd4127 -wd4210 -wd4214 -wd4255 -wd4574  -wd4668 -wd4710 -wd4711 -wd4820 -wd4996  -we4028 -we4142 -O2sy-  -Zm600  -DXP_WIN -DXP_WIN32 -DUSE_INCLUDED_VASPRINTF conftest.c   x64-msvcr120-ruby230.lib libxml2.lib  user32.lib advapi32.lib shell32.lib ws2_32.lib iphlpapi.lib imagehlp.lib shlwapi.lib    -link -incremental:no -debug -opt:ref -opt:icf   -libpath:. -libpath:c:/usr/local.2013/lib -libpath:C:/usr/libxslt/lib -libpath:C:/usr/libxml2/lib -libpath:C:/dev/learning/ruby-2.3.1/gang/zlib-1.2.8.bin/lib "
conftest.c
C:\usr\libxml2\include\libxml/encoding.h(28) : fatal error C1083: Cannot open include file: 'iconv.h': No such file or directory
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #ifndef WIN32_LEAN_AND_MEAN
 4: #define WIN32_LEAN_AND_MEAN
 5: #endif /* WIN32_LEAN_AND_MEAN */
 6: #ifndef WIN32
 7: #define WIN32
 8: #endif /* WIN32 */
 9: #include <winsock2.h>
10: #include <ws2tcpip.h>
11: #include <windows.h>
12: #include <libxml/parser.h>
13: 
14: /*top*/
15: extern int t(void);
16: int main(int argc, char **argv)
17: {
18:   if (argc > 1000000) {
19:     printf("%p", &t);
20:   }
21: 
22:   return 0;
23: }
24: extern void xmlParseDoc();
25: int t(void) { xmlParseDoc(); return 0; }
/* end */

--------------------

```

**Comment by larskanis** [comment]
In contrast to the linked tutorial page, which makes use of Mingw and the RubyInstaller, your're using a Ruby version compiled with Microsoft Visual Studio 2013. We currently do not support Visual Studio.

You're also using an older nokogiri version which didn't compile on Windows even with Mingw. We happily receive pull requests that add support for Microsoft Visual Studio, but we can not give too much support.

However you could use the stock RubyInstaller-2.3 and nokogiri-1.6.8. This should work out of the box.

**Comment by flavorjones** [comment]
Per @larskanis's comments above, I'm going to close this issue. Please let us know if we can help in any other way.
