### ISSUE TITLE
Install fails on Windows 10

### ISSUE THREAD

**Issue by prestonvanloon** [sparklemotion/nokogiri#1550]
**Have you tried following [the installation tutorial][tutorial]?**
yes

**What is the output of `gem install`?**

```
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    C:/Ruby21-x64/bin/ruby.exe extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby21-x64/bin/ruby
        --help
        --clean
C:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:571:in `block in try_compile'
        from C:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:522:in `with_werror'
        from C:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:571:in `try_compile'
        from extconf.rb:139:in `nokogiri_try_compile'
        from extconf.rb:163:in `block in add_cflags'
        from C:/Ruby21-x64/lib/ruby/2.1.0/mkmf.rb:621:in `with_cflags'
        from extconf.rb:162:in `add_cflags'
        from extconf.rb:415:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.8.1 for inspection.
Results logged to C:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/nokogiri-1.6.8.1/gem_make.out
```

**What are the contents of the `mkmf.log` file?**

```
"x86_64-w64-mingw32-gcc -o conftest.exe -IC:/Ruby21-x64/include/ruby-2.1.0/x64-mingw32 -IC:/Ruby21-x64/include/ruby-2.1.0/ruby/backward -IC:/Ruby21-x64/include/ruby-2.1.0 -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration  conftest.c  -L. -LC:/Ruby21-x64/lib -L.      -lx64-msvcrt-ruby210  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi   "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

```

**What operating system are you using?**
Windows 10

**Comment by flavorjones** [comment]
This output indicates something unexpected about your developer tools. What version of devkit do you have installed?

**Comment by larskanis** [comment]
Seems like the DevKit isn't installed correctly. It should usually call
"gcc" instead of "x86_64-w64-mingw32-gcc".

On the other hand rubygems should install the binary gem on Windows, with
no need for the DevKit. Possibly you need to update rubygems or ruby, so
that it works.

**Comment by larskanis** [comment]
Closed by response timeout.
