### ISSUE TITLE
nogogiri build fail on armhf

### ISSUE THREAD

**Issue by lacroutelacroute** [sparklemotion/nokogiri#1588]
## If you're having trouble installing Nokogiri ...
build fail on armhf nogogiri

**Have you tried following [the installation tutorial][tutorial]?**
http://www.nokogiri.org/tutorials/installing_nokogiri.html#ubuntu___debian

**What is the output of `gem install`?**
```
:/opt/msf-devel/metasploit-framework$ sudo bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Warning: the running version of Bundler (1.13.6) is older than the version that created the lockfile (1.13.7). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies.......................
Using rake 12.0.0
Using i18n 0.7.0
Using json 1.8.6
Using minitest 5.10.1
Using thread_safe 0.3.5
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 1.6.5
Using arel 6.0.4
Using public_suffix 2.0.5
Using ffi 1.9.17
Using contracts 0.14.0
Using gherkin 4.0.0
Using cucumber-wire 0.0.1
Using diff-lcs 1.3
Using multi_json 1.12.1
Using multi_test 0.1.2
Using rspec-support 3.5.0
Using thor 0.19.4
Using bcrypt 3.1.11
Using bit-struct 0.15.0
Using mime-types-data 3.2016.0521
Using coderay 1.1.1
Using docile 1.1.5
Using multipart-post 2.0.0
Using filesize 0.1.1
Using fivemat 1.3.2
Using rkelly-remix 0.0.7
Using metasm 1.0.2
Using pg 0.19.0
Using pg_array_parser 0.0.9
Using rubyntlm 0.6.1
Using rubyzip 1.2.0
Using metasploit-payloads 1.2.9
Using metasploit_payloads-mettle 0.1.6
Using msgpack 1.0.2
Using nessus_rest 0.1.6
Using net-ssh 4.0.1
Using network_interface 0.0.1
Using openssl-ccm 1.2.1
Using openvas-omp 0.0.4
Using pcaprub 0.12.4
Using patch_finder 1.0.2
Using rb-readline 0.5.3
Using redcarpet 3.4.0
Using rex-text 0.2.11
Using rex-core 0.1.6
Using rex-struct2 0.1.0
Using rex-java 0.1.3
Using rex-registry 0.1.1
Using robots 0.10.1
Using sqlite3 1.3.13
Using sshkey 1.8.0
Using windows_error 0.1.0
Using method_source 0.8.2
Using slop 3.6.0
Using simplecov-html 0.10.0
Using timecop 0.8.1
Using yard 0.9.8
Using bundler 1.13.6
Using tzinfo 1.2.2
Installing nokogiri 1.7.0.1 with native extensions
Using rack-test 0.6.3
Using addressable 2.5.0
Using childprocess 0.5.9
Using cucumber-core 1.5.0
Using rspec-expectations 3.5.0
Using rspec-core 3.5.4
Using rspec-mocks 3.5.0
Using mime-types 3.1
Using faraday 0.11.0
Using jsobfu 0.4.2
Using packetfu 1.1.11
Using rex-arch 0.1.4
Using rex-mime 0.1.3
Using rex-ole 0.1.4
Using rex-random_identifier 0.1.1
Using rex-zip 0.1.1
Using rex-rop_builder 0.1.1
Using rex-socket 0.1.3
Using pry 0.10.4
Using simplecov 0.12.0
Using activesupport 4.2.7.1
Using tzinfo-data 1.2016.10
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.7.0.1/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20170124-4301-1nh713p.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.1.0
checking for gzdopen() in -lz... yes
checking for iconv... yes
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxml2-2.9.4.

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
Extracting libxml2-2.9.4.tar.gz into
tmp/arm-unknown-linux-gnueabihf/ports/libxml2/2.9.4... OK
Running 'configure' for libxml2 2.9.4... OK
Running 'compile' for libxml2 2.9.4... ERROR, review
'/var/lib/gems/2.3.0/gems/nokogiri-1.7.0.1/ext/nokogiri/tmp/arm-unknown-linux-gnueabihf/ports/libxml2/2.9.4/compile.log'
to see what happened. Last lines are:
========================================================================
  CC       schematron.lo
  CC       xzlib.lo
  CCLD     libxml2.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       testdso.lo
  CCLD     testdso.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       xmllint.o
  CCLD     xmllint
/usr/bin/ld:./.libs/libxml2.a: file format not recognized; treating as linker
script
/usr/bin/ld:./.libs/libxml2.a:1: syntax error
collect2: error: ld returned 1 exit status
Makefile:1117: recipe for target 'xmllint' failed
make[2]: *** [xmllint] Error 1
make[2]: Leaving directory
'/var/lib/gems/2.3.0/gems/nokogiri-1.7.0.1/ext/nokogiri/tmp/arm-unknown-linux-gnueabihf/ports/libxml2/2.9.4/libxml2-2.9.4'
Makefile:1440: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory
'/var/lib/gems/2.3.0/gems/nokogiri-1.7.0.1/ext/nokogiri/tmp/arm-unknown-linux-gnueabihf/ports/libxml2/2.9.4/libxml2-2.9.4'
Makefile:859: recipe for target 'all' failed
make: *** [all] Error 2
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build
/var/lib/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:366:in
`block in execute': Failed to complete compile task (RuntimeError)
from
/var/lib/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in
`chdir'
from
/var/lib/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:337:in
`execute'
from
/var/lib/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:111:in
`compile'
from
/var/lib/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:150:in
`cook'
	from extconf.rb:364:in `block (2 levels) in process_recipe'
	from extconf.rb:257:in `block in chdir_for_build'
	from extconf.rb:256:in `chdir'
	from extconf.rb:256:in `chdir_for_build'
	from extconf.rb:363:in `block in process_recipe'
	from extconf.rb:262:in `tap'
	from extconf.rb:262:in `process_recipe'
	from extconf.rb:547:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

  /var/lib/gems/2.3.0/extensions/arm-linux/2.3.0/nokogiri-1.7.0.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.7.0.1 for
inspection.
Results logged to
/var/lib/gems/2.3.0/extensions/arm-linux/2.3.0/nokogiri-1.7.0.1/gem_make.out

An error occurred while installing nokogiri (1.7.0.1), and Bundler
cannot continue.
Make sure that `gem install nokogiri -v '1.7.0.1'` succeeds before bundling.
```

**What are the contents of the `mkmf.log` file?**
```
cat  /var/lib/gems/2.3.0/extensions/arm-linux/2.3.0/nokogiri-1.7.0.1/mkmf.log
"gcc -o conftest -I/usr/include/arm-linux-gnueabihf/ruby-2.3.0 -I/usr/include/ruby-2.3.0/ruby/backward -I/usr/include/ruby-2.3.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64  -g -O2 -fdebug-prefix-map=/build/ruby2.3-aeoxw8/ruby2.3-2.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC  conftest.c  -L. -L/usr/lib/arm-linux-gnueabihf -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby-2.3  -lpthread -lgmp -ldl -lcrypt -lm   -lc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -I/usr/include/arm-linux-gnueabihf/ruby-2.3.0 -I/usr/include/ruby-2.3.0/ruby/backward -I/usr/include/ruby-2.3.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64  -g -O2 -fdebug-prefix-map=/build/ruby2.3-aeoxw8/ruby2.3-2.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC    -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main() {return 0;}
/* end */

have_library: checking for gzdopen() in -lz... -------------------- yes

"gcc -o conftest -I/usr/include/arm-linux-gnueabihf/ruby-2.3.0 -I/usr/include/ruby-2.3.0/ruby/backward -I/usr/include/ruby-2.3.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64  -g -O2 -fdebug-prefix-map=/build/ruby2.3-aeoxw8/ruby2.3-2.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC  -g -DXP_UNIX -Wall -Wcast-qual -Wwrite-strings -Wconversion -Wmissing-noreturn -Winline conftest.c  -L. -L/usr/lib/arm-linux-gnueabihf -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby-2.3 -lz  -lpthread -lgmp -ldl -lcrypt -lm   -lc "
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <zlib.h>
 4: 
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     printf("%p", &t);
11:   }
12: 
13:   return 0;
14: }
15: int t(void) { void ((*volatile p)()); p = (void ((*)()))gzdopen; return !p; }
/* end */

--------------------

have_iconv?: checking for iconv... -------------------- yes

"gcc -o conftest -I/usr/include/arm-linux-gnueabihf/ruby-2.3.0 -I/usr/include/ruby-2.3.0/ruby/backward -I/usr/include/ruby-2.3.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64  -g -O2 -fdebug-prefix-map=/build/ruby2.3-aeoxw8/ruby2.3-2.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC  -g -DXP_UNIX -Wall -Wcast-qual -Wwrite-strings -Wconversion -Wmissing-noreturn -Winline conftest.c  -L. -L/usr/lib/arm-linux-gnueabihf -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby-2.3  -lpthread -lgmp -ldl -lcrypt -lm   -lc "
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <stdlib.h>
 4: #include <iconv.h>
 5: 
 6: int main(void)
 7: {
 8:     iconv_t cd = iconv_open("", "");
 9:     iconv(cd, NULL, NULL, NULL, NULL);
10:     return EXIT_SUCCESS;
11: }
/* end */

--------------------
```

**What operating system are you using?**
kali rolling on armhf
tried to install metasploit from scratch

## If this isn't an installation issue ...

**What problems are you experiencing?**

**What's the output from `nokogiri -v`?**
~$ sudo nokogiri -v
# Nokogiri (1.6.8.1)
    ---
    warnings: []
    nokogiri: 1.6.8.1
    ruby:
      version: 2.3.3
      platform: arm-linux-gnueabihf
      description: ruby 2.3.3p222 (2016-11-21) [arm-linux-gnueabihf]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.4
      loaded: 2.9.4

**Can you provide a self-contained script that reproduces what you're seeing?**

[tutorial]: http://www.nokogiri.org/tutorials/installing_nokogiri.html

**Comment by lacroutelacroute** [comment]
my install is realised on a telephone android with chrooted install

**Comment by flavorjones** [comment]
Hi,

This portion of the log indicates that something serious is broken:

```
/usr/bin/ld:./.libs/libxml2.a: file format not recognized; treating as linker
script
/usr/bin/ld:./.libs/libxml2.a:1: syntax error
collect2: error: ld returned 1 exit status
```

Have you considered installing libxml2 and libxslt on this device and using the system libraries?

**Comment by flavorjones** [comment]
Also, please consider trying to get libxml2 to compile and install; the upstream libxml2 build scripts may not support your architecture.

**Comment by lacroutelacroute** [comment]
The librairies were already installed but construction fail
native metasploit kalilinux is installed but the up to date version i can not get it

**Comment by flavorjones** [comment]
@lacroutelacroute I'm not sure I understand. How can I help?

**Comment by lacroutelacroute** [comment]
build on armhf android chrooted install is not possible

**Comment by flavorjones** [comment]
OK, it seems you're not able to explain how I can help, and so I'm going to go ahead and close this ticket. Sorry I couldn't be of any assistance!
