### ISSUE TITLE
Doesn't build in Docker Ruby 2.4.3 image

### ISSUE THREAD

**Issue by bloomdido** [sparklemotion/nokogiri#1732]
**What is the output of `gem install`?**
```
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/nokogiri-1.8.2/ext/nokogiri
/usr/local/bin/ruby -r ./siteconf20180305-7-1fctl3m.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/usr/local/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:523:in `with_werror'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:630:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:410:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/2.4.0/nokogiri-1.8.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/nokogiri-1.8.2 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.4.0/nokogiri-1.8.2/gem_make.out
```

**What are the contents of the `mkmf.log` file?**
```
::::::::::::::
/usr/local/bundle/extensions/x86_64-linux/2.4.0/nokogiri-1.8.2/mkmf.log
::::::::::::::
"gcc -o conftest -I/usr/local/include/ruby-2.4.0/x86_64-linux -I/usr/local/include/ruby-2.4.0/ruby/backward -I/usr/local/include/ruby-2.4.0 -I.    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format  -fPIC  conftest.c  -L. -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lruby  -lpthread -ldl -lcrypt -lm   -lc "
gcc: internal compiler error: Segmentation fault (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**What operating system are you using?**
```
FROM ruby:2.4.3

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  patch \
  ruby-dev \
  zlib1g-dev \
  liblzma-dev

RUN gem install nokogiri
```

**Comment by bloomdido** [comment]
Same Dockerfile builds fine if based on `ruby:2.4.0`, `ruby:2.4.1`, or `ruby:2.4.2`.

**Comment by flavorjones** [comment]
As discussed via email, this appears to be an issue in how the docker image is built, as nothing Nokogiri is doing in build scripts would cause or prevent a segfault in the compiler.

Can I ask that you reach out to the docker image maintainer?

**Comment by bloomdido** [comment]
Must have been a corrupt Docker image.
