### ISSUE TITLE
LoadError: cannot load such file -- nokogiri/2.4/nokogiri

### ISSUE THREAD

**Issue by roberts1000** [sparklemotion/nokogiri#1769]
nokogiri 1.8.3 is throwing `LoadError: cannot load such file -- nokogiri/2.4/nokogiri` when I try and start a Rails server on a dummy app inside my gem.  I'm using Ruby 2.4.4.  nokogiri 1.8.2 works fine.
 
```
Caused by:
    LoadError: cannot load such file -- nokogiri/2.4/nokogiri
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/nokogiri-1.8.3/lib/nokogiri.rb:30:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/nokogiri-1.8.3/lib/nokogiri.rb:30:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/loofah-2.2.2/lib/loofah.rb:3:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/loofah-2.2.2/lib/loofah.rb:3:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/rails-html-sanitizer-1.0.4/lib/rails-html-sanitizer.rb:2:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/rails-html-sanitizer-1.0.4/lib/rails-html-sanitizer.rb:2:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/sanitize_helper.rb:4:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/sanitize_helper.rb:4:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/text_helper.rb:34:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/text_helper.rb:34:in `<module:TextHelper>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/text_helper.rb:31:in `<module:Helpers>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/text_helper.rb:8:in `<module:ActionView>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/text_helper.rb:6:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_tag_helper.rb:20:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_tag_helper.rb:20:in `<module:FormTagHelper>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_tag_helper.rb:16:in `<module:Helpers>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_tag_helper.rb:10:in `<module:ActionView>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_tag_helper.rb:8:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_helper.rb:6:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_helper.rb:6:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers.rb:54:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers.rb:54:in `<module:Helpers>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers.rb:6:in `<module:ActionView>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers.rb:5:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/sprockets-rails-3.2.1/lib/sprockets/rails/context.rb:1:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/sprockets-rails-3.2.1/lib/sprockets/rails/context.rb:1:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:7:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:7:in `<top (required)>'
    /home/vagrant/Projects/my_gem/spec/dummy/config/application.rb:13:in `require'
    /home/vagrant/Projects/my_gem/spec/dummy/config/application.rb:13:in `<top (required)>'
    /home/vagrant/Projects/my_gem/spec/dummy/Rakefile:4:in `require_relative'
    /home/vagrant/Projects/my_gem/spec/dummy/Rakefile:4:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/tasks/engine.rake:5:in `load'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/tasks/engine.rake:5:in `block (2 levels) in <top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/tasks/engine.rake:4:in `block in <top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/tasks/engine.rake:88:in `<top (required)>'
    /home/vagrant/Projects/my_gem/Rakefile:8:in `load'
    /home/vagrant/Projects/my_gem/Rakefile:8:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
    Tasks: TOP => load_app
    (See full trace by running task with --trace)
```

I'm also seeing the following error at the same time:

```
    rake aborted!
    LoadError: /home/vagrant/.rvm/gems/ruby-2.4.4/gems/nokogiri-1.8.3/lib/nokogiri/nokogiri.so: file too short - /home/vagrant/.rvm/gems/ruby-2.4.4/gems/nokogiri-1.8.3/lib/nokogiri/nokogiri.so
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/nokogiri-1.8.3/lib/nokogiri.rb:32:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/nokogiri-1.8.3/lib/nokogiri.rb:32:in `rescue in <top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/nokogiri-1.8.3/lib/nokogiri.rb:28:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/loofah-2.2.2/lib/loofah.rb:3:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/loofah-2.2.2/lib/loofah.rb:3:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/rails-html-sanitizer-1.0.4/lib/rails-html-sanitizer.rb:2:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/rails-html-sanitizer-1.0.4/lib/rails-html-sanitizer.rb:2:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/sanitize_helper.rb:4:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/sanitize_helper.rb:4:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/text_helper.rb:34:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/text_helper.rb:34:in `<module:TextHelper>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/text_helper.rb:31:in `<module:Helpers>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/text_helper.rb:8:in `<module:ActionView>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/text_helper.rb:6:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_tag_helper.rb:20:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_tag_helper.rb:20:in `<module:FormTagHelper>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_tag_helper.rb:16:in `<module:Helpers>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_tag_helper.rb:10:in `<module:ActionView>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_tag_helper.rb:8:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_helper.rb:6:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers/form_helper.rb:6:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers.rb:54:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers.rb:54:in `<module:Helpers>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers.rb:6:in `<module:ActionView>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionview-5.2.0/lib/action_view/helpers.rb:5:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/sprockets-rails-3.2.1/lib/sprockets/rails/context.rb:1:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/sprockets-rails-3.2.1/lib/sprockets/rails/context.rb:1:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:7:in `require'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:7:in `<top (required)>'
    /home/vagrant/Projects/my_gem/spec/dummy/config/application.rb:13:in `require'
    /home/vagrant/Projects/my_gem/spec/dummy/config/application.rb:13:in `<top (required)>'
    /home/vagrant/Projects/my_gem/spec/dummy/Rakefile:4:in `require_relative'
    /home/vagrant/Projects/my_gem/spec/dummy/Rakefile:4:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/tasks/engine.rake:5:in `load'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/tasks/engine.rake:5:in `block (2 levels) in <top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/tasks/engine.rake:4:in `block in <top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/railties-5.2.0/lib/rails/tasks/engine.rake:88:in `<top (required)>'
    /home/vagrant/Projects/my_gem/Rakefile:8:in `load'
    /home/vagrant/Projects/my_gem/Rakefile:8:in `<top (required)>'
    /home/vagrant/.rvm/gems/ruby-2.4.4/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
```

**Comment by roberts1000** [comment]
I deleted all gems from my rvm gemset and then did a full `bundle`.  It's working now.
