### ISSUE TITLE
Installation - gcc error on option "-Wsuggest-attribute=noreturn"

### ISSUE THREAD

**Issue by tibbon** [sparklemotion/nokogiri#1781]
## If you're having trouble installing Nokogiri ...

I've tried most of the things in the [Installing Nokogiri](http://www.nokogiri.org/tutorials/installing_nokogiri.html) documentation, which I'll demonstrate below. 

This is on one of our CI systems, not on a developer laptop. First, some system information:

```
$ uname -r
4.4.0-119-generic
$ uname -v
#143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018
$ uname -m
x86_64
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

**What is the output of `gem install nokogiri`?**

```
$ gem install nokogiri

Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /home/u1216/.gem/gems/nokogiri-1.8.4/ext/nokogiri
/home/tddium/.rbenv/versions/2.5.1/bin/ruby -r ./siteconf20180731-2404-yp7j9c.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/tddium/.rbenv/versions/2.5.1/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `block in try_compile'
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:521:in `with_werror'
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:632:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:410:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/u1216/.gem/extensions/x86_64-linux/2.5.0/nokogiri-1.8.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/u1216/.gem/gems/nokogiri-1.8.4 for inspection.
Results logged to /home/u1216/.gem/extensions/x86_64-linux/2.5.0/nokogiri-1.8.4/gem_make.out
```

**What are the contents of the `mkmf.log` file?**

```
$ cat /home/u1216/.gem/extensions/x86_64-linux/2.5.0/nokogiri-1.8.4/mkmf.log

"gcc -o conftest -I/home/tddium/.rbenv/versions/2.5.1/include/ruby-2.5.0/x86_64-linux -I/home/tddium/.rbenv/versions/2.5.1/include/ruby-2.5.0/ruby/backward -I/home/tddium/.rbenv/versions/2.5.1/include/ruby-2.5.0 -I. -I/home/tddium/.rbenv/versions/2.5.1/include    -O3 -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn  -fPIC  conftest.c  -L. -L/home/tddium/.rbenv/versions/2.5.1/lib -Wl,-rpath,/home/tddium/.rbenv/versions/2.5.1/lib -L. -L/home/tddium/.rbenv/versions/2.5.1/lib  -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/tddium/.rbenv/versions/2.5.1/lib -L/home/tddium/.rbenv/versions/2.5.1/lib -lruby  -lpthread -lrt -lgmp -ldl -lcrypt -lm   -lc "
cc1: error: unrecognized command line option "-Wsuggest-attribute=noreturn"
cc1: warning: unrecognized command line option "-Wno-self-assign"
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand"
cc1: warning: unrecognized command line option "-Wno-parentheses-equality"
cc1: warning: unrecognized command line option "-Wno-tautological-compare"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**What operating system are you using?**
Ubuntu 12.04 (Our CI provides this and we cannot update)

** More Steps Tried, as per instructions ** 

Installed recommended packages: 
```
sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
liblzma-dev is already the newest version.
zlib1g-dev is already the newest version.
build-essential is already the newest version.
patch is already the newest version.
The following package was automatically installed and is no longer required:
  libxmlrpc-core-c3
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  ruby-dev
0 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
Need to get 4,572 B of archives.
After this operation, 32.8 kB of additional disk space will be used.
Do you want to continue [Y/n]? y
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ precise/main ruby-dev all 4.8 [4,572 B]
Fetched 4,572 B in 0s (201 kB/s)
Selecting previously unselected package ruby-dev.
(Reading database ... 270126 files and directories currently installed.)
Unpacking ruby-dev (from .../archives/ruby-dev_4.8_all.deb) ...
Setting up ruby-dev (4.8) ...
```

Tried installing Nokogiri again:
```
gem install nokogiri
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /home/u1216/.gem/gems/nokogiri-1.8.4/ext/nokogiri
/home/tddium/.rbenv/versions/2.5.1/bin/ruby -r ./siteconf20180731-2509-6va9kr.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/tddium/.rbenv/versions/2.5.1/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `block in try_compile'
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:521:in `with_werror'
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:632:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:410:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/u1216/.gem/extensions/x86_64-linux/2.5.0/nokogiri-1.8.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/u1216/.gem/gems/nokogiri-1.8.4 for inspection.
Results logged to /home/u1216/.gem/extensions/x86_64-linux/2.5.0/nokogiri-1.8.4/gem_make.out
```

Tried with system libs:
```
gem install nokogiri -- --use-system-libraries

Building native extensions with: '--use-system-libraries'
This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /home/u1216/.gem/gems/nokogiri-1.8.4/ext/nokogiri
/home/tddium/.rbenv/versions/2.5.1/bin/ruby -r ./siteconf20180731-2541-1hc5bds.rb extconf.rb --use-system-libraries
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/tddium/.rbenv/versions/2.5.1/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `block in try_compile'
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:521:in `with_werror'
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /home/tddium/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:632:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:410:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/u1216/.gem/extensions/x86_64-linux/2.5.0/nokogiri-1.8.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/u1216/.gem/gems/nokogiri-1.8.4 for inspection.
Results logged to /home/u1216/.gem/extensions/x86_64-linux/2.5.0/nokogiri-1.8.4/gem_make.out
```

It seems someone had a similar problem here on SO, but without a solution: https://stackoverflow.com/questions/44435842/how-to-install-nokogiri-with-rails-on-ubuntu-16-04

**Comment by tibbon** [comment]
Same errors when I do: `gem install nokogiri -- --use-system-libraries --with-xml2-include=/usr/include/libxml2`

**Comment by tibbon** [comment]
Oh... maybe it's my GCC version?!?!

```
gcc --version
gcc-4.5 (Ubuntu/Linaro 4.5.3-12ubuntu2) 4.5.3
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

That's pretty old; does it support that flag?

**Comment by flavorjones** [comment]
@tibbon sorry you ran into this. We could (and probably should) check for GCC version, but to be honest I wasn't even aware we had done something that was not backwards-compatible with older GCC versions.

Are you on a vanilla 12.04? (This might be a good time to mention, as you probably already know, that 12.04 was end-of-lifed ("EOLed") in April 2017, so in the interest of maintaining a secure platform you may want to consider upgrading.)

**Comment by ekremkaraca** [comment]
I had similar issue while trying to upgrade the gem to the version 1.9.1. For me, gcc version is 5.5:

```shell
❯ gcc --version # Ruby version is 2.5.3
gcc (Homebrew gcc 5.5.0_4) 5.5.0 
```

**Comment by flavorjones** [comment]
@tibbon I'm curious if your version of Ruby was compiled with a different/newer version of GCC?

I ask because it looks like those compiler flags come from `RbConfig::CONFIG["cflags"]`. Unless you're using a different compiler, it doesn't make sense to me that gcc would exit-with-error when seeing that option.

**Comment by flavorjones** [comment]
@tibbon I asked my previous question because, if your Ruby was compiled with the same GCC flags then Nokogiri shouldn't need to sanity-check your version of GCC.

I'd like to close this, under the assumption that Ruby and Nokogiri were compiled with different versions of GCC on your system. Please let me know if that's not the case.

**Comment by flavorjones** [comment]
Closing.

**Comment by simongareste** [comment]
Hi,

Sorry to reopen this, but I may help troubleshooting this, as I'm facing the same issue and I would like to find at least a workaround, if not a fix.

Ruby is installed via snap (on ubuntu 14.04). Because of this, it's quite probable that the gcc version is not the same, however I have no idea how to check this.

```
$>ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
$>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.5.0-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --with-as=/usr/bin/x86_64-linux-gnu-as --with-ld=/usr/bin/x86_64-linux-gnu-ld --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=gcc4-compatible --disable-libstdcxx-dual-abi --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.5.0 20181026 (Ubuntu 6.5.0-2ubuntu1~14.04.1)
```

Given that ruby is installed via snap, I don't have the option to install ruby-dev. I found through various threads that the following packages would help:

```
sudo apt install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev
```

However being on an old distrib, libgdbm5 is not available. It did helped a bit though, I think, as now I only have the following flags missing (and I believe I had more previously:

```
cat   /home/user/project/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/nokogiri-1.10.7/mkmf.log
"gcc -o conftest -I/snap/ruby/160/include/ruby-2.6.0/x86_64-linux -I/snap/ruby/160/include/ruby-2.6.0/ruby/backward -I/snap/ruby/160/include/ruby-2.6.0 -I.    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC  conftest.c  -L. -L/snap/ruby/160/lib -Wl,-rpath,/snap/ruby/160/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/snap/ruby/160/lib -L/snap/ruby/160/lib -lruby  -lm   -lc "
gcc: error: unrecognized command line option ‘-Wrestrict’
gcc: error: unrecognized command line option ‘-Wimplicit-fallthrough=0’; did you mean ‘-Wno-fallthrough’?
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

Question is, how could I use the same gcc for both? Maybe you are not the best person to ask, as I guess this is more a snap issue, but right now I'm a bit stuck, so any help would be appreciated a lot!
