### ISSUE TITLE
Problem installing v.1.8.5 on ubuntu 16.04 with ruby 2.5.1 (rbenv)

### ISSUE THREAD

**Issue by fabioperrella** [sparklemotion/nokogiri#1817]
**Have you tried following [the installation tutorial][tutorial]?**

yes

**What is the output of `gem install`?**

```
$ gem install nokogiri -v '1.8.5' -- --use-system-libraries
Building native extensions with: '--use-system-libraries'
This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /home/fabio/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5/ext/nokogiri
/home/fabio/.rbenv/versions/2.5.1/bin/ruby -r ./siteconf20181106-18912-itnqgt.rb extconf.rb --use-system-libraries
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/fabio/.rbenv/versions/2.5.1/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/home/fabio/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/fabio/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `block in try_compile'
	from /home/fabio/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:521:in `with_werror'
	from /home/fabio/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /home/fabio/.rbenv/versions/2.5.1/lib/ruby/2.5.0/mkmf.rb:632:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:410:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/fabio/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0-static/nokogiri-1.8.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/fabio/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.5 for inspection.
Results logged to /home/fabio/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0-static/nokogiri-1.8.5/gem_make.out
```

**What are the contents of the `mkmf.log` file?**

```
$ cat /home/fabio/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0-static/nokogiri-1.8.5/mkmf.log
"gcc -o conftest -I/home/fabio/.rbenv/versions/2.5.1/include/ruby-2.5.0/x86_64-linux -I/home/fabio/.rbenv/versions/2.5.1/include/ruby-2.5.0/ruby/backward -I/home/fabio/.rbenv/versions/2.5.1/include/ruby-2.5.0 -I. -I/home/fabio/.rbenv/versions/2.5.1/include    -O3 -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wmisleading-indentation -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wduplicated-cond -Wno-maybe-uninitialized  conftest.c  -L. -L/home/fabio/.rbenv/versions/2.5.1/lib -Wl,-rpath,/home/fabio/.rbenv/versions/2.5.1/lib -L. -L/home/fabio/.rbenv/versions/2.5.1/lib  -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/fabio/.rbenv/versions/2.5.1/lib -L/home/fabio/.rbenv/versions/2.5.1/lib -lruby-static  -lpthread -ldl -lcrypt -lm   -lc "
gcc: error: unrecognized command line option ‘-Wmisleading-indentation’
gcc: error: unrecognized command line option ‘-Wduplicated-cond’
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**What operating system are you using?**

```
$ cat /etc/issue
Ubuntu 16.04.5 LTS \n \l
```

**Comment**

This seems to be similar to the issue https://github.com/sparklemotion/nokogiri/issues/1805 but my gcc seems to be correct:
```
 $ `gcc -print-prog-name=cc1plus` -v
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/5/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/5
 /usr/include/x86_64-linux-gnu/c++/5
 /usr/include/c++/5/backward
 /usr/lib/gcc/x86_64-linux-gnu/5/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
 /usr/include
End of search list.
^C
```

**Comment by pietromaj** [comment]
Same here. but ruby 2.4.3

**Comment by flavorjones** [comment]
It would also be good to check the compiler args your ruby was built with, which you can output with this command:

```sh
ruby -r rbconfig -e 'puts RbConfig::CONFIG["configure_args"]'
```

So to sum up what additional info would be helpful:

- output of `gcc -v`
- description of how you built your ruby, or where it was installed from (e.g., rbenv, rvm, from source, via apt)
- output of ruby configure args

Thanks!

**Comment by fabioperrella** [comment]
@flavorjones replying to your questions:

> Can you also tell me how you built your ruby, or where you got it from?

I installed from rbenv:
```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
$ rbenv version
2.5.1
```
> It would also be good to check the compiler args
```
$ ruby -r rbconfig -e 'puts RbConfig::CONFIG["configure_args"]'
 '--prefix=/home/fabio/.rbenv/versions/2.5.1' 'LDFLAGS=-L/home/fabio/.rbenv/versions/2.5.1/lib ' 'CPPFLAGS=-I/home/fabio/.rbenv/versions/2.5.1/include '
```

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 
```

Is there anything more I can help you to debug it?

**Comment by flavorjones** [comment]
OK, I think I've got the answer. Looking at Ruby's `configure.ac` file:

https://github.com/ruby/ruby/blob/trunk/configure.ac#L506-L513

and notably commit https://github.com/ruby/ruby/commit/20685cd introduces the flags you're having issues with.

I'll also point out that because CI is running these tests on Xenial using the same gcc compiler (5.4.0), that this is something that appears to be specific to the version of Ruby you're using.

Is it possible that you downloaded a binary version of Ruby, one which was compiled with a more recent version of GCC? I have no idea how rbenv works (does it always build from source?).

My point being that you should see similar problems if you try to compile other gems with C extensions, like `bcrypt`. Can you check if you have similar problems with that gem?

**Comment by flavorjones** [comment]
See this stackoverflow post that seems related to what you're seeing:

https://stackoverflow.com/questions/50541061/gem-install-bcrypt-gcc-error-on-ubuntu-16-04/

**Comment by fabioperrella** [comment]
@flavorjones you were totally right! 

I had the same problem installing the gem `bcrypt`, then I tried a different approach removing the ruby 2.5.1 that I had in my pc and installing the version 2.5.3 (with rbenv), and it worked! I installed nokogiri 1.8.5 and everything is all right!

So the problem was with ruby 2.5.1 installed with rbenv.

Really thank you for your attention!

**Comment by flavorjones** [comment]
Excellent, I'm glad you were able to get it working. Thanks for closing the loop on this ticket.
