### ISSUE TITLE
Installation fails on any folder path that contains spaces in the path

### ISSUE THREAD

**Issue by clive-hetzner** [sparklemotion/nokogiri#1891]
**Describe the bug**

Installation fails within any folder containing a space in the folder name.

**To Reproduce**

Gemfile:
```ruby
source 'https://rubygems.org'
gem 'nokogiri'
```

% bundle install --path "./Bundles Here/"

**Expected behavior**

nokogiri installs

**Actual Behaviour**

```
========================================================================
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-recursive
Making install in include
Making install in libxml
make[4]: Nothing to be done for `install-exec-am'.
/usr/local/bin/gmkdir -p '/Users/clivec/tmp/test-nokogiri/Bundles
Here/ruby/2.3.0/gems/nokogiri-1.10.2/ports/x86_64-apple-darwin17.5.0/libxml2/2.9.9/include/libxml2/libxml'
/usr/local/bin/ginstall -c -m 644 SAX.h entities.h encoding.h parser.h parserInternals.h xmlerror.h HTMLparser.h HTMLtree.h debugXML.h
tree.h list.h hash.h xpath.h xpathInternals.h xpointer.h xinclude.h xmlIO.h xmlmemory.h nanohttp.h nanoftp.h uri.h valid.h xlink.h
xmlversion.h DOCBparser.h catalog.h threads.h globals.h c14n.h xmlautomata.h xmlregexp.h xmlmodule.h xmlschemas.h schemasInternals.h
xmlschemastypes.h xmlstring.h xmlunicode.h xmlreader.h relaxng.h dict.h '/Users/clivec/tmp/test-nokogiri/Bundles
Here/ruby/2.3.0/gems/nokogiri-1.10.2/ports/x86_64-apple-darwin17.5.0/libxml2/2.9.9/include/libxml2/libxml'
/usr/local/bin/ginstall -c -m 644 SAX2.h xmlexports.h xmlwriter.h chvalid.h pattern.h xmlsave.h schematron.h
'/Users/clivec/tmp/test-nokogiri/Bundles
Here/ruby/2.3.0/gems/nokogiri-1.10.2/ports/x86_64-apple-darwin17.5.0/libxml2/2.9.9/include/libxml2/libxml'
make[4]: Nothing to be done for `install-exec-am'.
make[4]: Nothing to be done for `install-data-am'.
Making install in .
/usr/local/bin/gmkdir -p '/Users/clivec/tmp/test-nokogiri/Bundles
Here/ruby/2.3.0/gems/nokogiri-1.10.2/ports/x86_64-apple-darwin17.5.0/libxml2/2.9.9/lib'
/bin/sh ./libtool   --mode=install /usr/local/bin/ginstall -c   libxml2.la '/Users/clivec/tmp/test-nokogiri/Bundles
Here/ruby/2.3.0/gems/nokogiri-1.10.2/ports/x86_64-apple-darwin17.5.0/libxml2/2.9.9/lib'
libtool: install: /usr/local/bin/ginstall -c .libs/libxml2.lai /Users/clivec/tmp/test-nokogiri/Bundles
Here/ruby/2.3.0/gems/nokogiri-1.10.2/ports/x86_64-apple-darwin17.5.0/libxml2/2.9.9/lib/libxml2.la
ginstall: target 'Here/ruby/2.3.0/gems/nokogiri-1.10.2/ports/x86_64-apple-darwin17.5.0/libxml2/2.9.9/lib/libxml2.la' is not a directory
make[3]: *** [install-libLTLIBRARIES] Error 1
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/clivec/.rvm/rubies/ruby-2.3.1/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build
/Users/clivec/tmp/test-nokogiri/Bundles Here/ruby/2.3.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:402:in `block in
execute': Failed to complete install task (RuntimeError)
	from /Users/clivec/tmp/test-nokogiri/Bundles Here/ruby/2.3.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in `chdir'
from /Users/clivec/tmp/test-nokogiri/Bundles Here/ruby/2.3.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:373:in
`execute'
from /Users/clivec/tmp/test-nokogiri/Bundles Here/ruby/2.3.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:120:in
`install'
	from /Users/clivec/tmp/test-nokogiri/Bundles Here/ruby/2.3.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:155:in `cook'
	from extconf.rb:365:in `block (2 levels) in process_recipe'
	from extconf.rb:257:in `block in chdir_for_build'
	from extconf.rb:256:in `chdir'
	from extconf.rb:256:in `chdir_for_build'
	from extconf.rb:364:in `block in process_recipe'
	from extconf.rb:262:in `tap'
	from extconf.rb:262:in `process_recipe'
	from extconf.rb:557:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/clivec/tmp/test-nokogiri/Bundles Here/ruby/2.3.0/extensions/x86_64-darwin-17/2.3.0/nokogiri-1.10.2/mkmf.log

extconf failed, exit code 1

```

**Comment by flavorjones** [comment]
Hi! Thanks for asking this question. This is actually an issue with libxml2's tooling, which uses `libtool` and a `Makefile` that don't support spaces. Prior issues around this include #1407, #1289, and #1175.

You should be able to work around this by installing with the "systems library" option, using your distro's libxml2 and libxslt. Check out https://nokogiri.org/tutorials/installing_nokogiri.html for help with that.

Given that this is an upstream issue with libxml2 and its toolchain, I'm going to close this issue. I'm sorry we can't be of more help.
