### ISSUE TITLE
can't installing nokogiri

### ISSUE THREAD

**Issue by zarszz** [sparklemotion/nokogiri#1904]
can't install nokogiri with command `gem install nokogiri` and when i trying creating new ruby projects, throwing errors in nekogiri installing

***environment***
```
Operating System = Ubuntu 18.04
Ruby Version = 2.5.3
Installing method = RVM
```

**error throwed in terminal**
````
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /home/<username>/.rvm/gems/ruby-2.5.3/gems/nokogiri-1.10.3/ext/nokogiri
/home/<username>/.rvm/rubies/ruby-2.5.3/bin/ruby -I /home/<username>/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0 -r ./siteconf20190510-25015-1762b56.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/<username>/.rvm/rubies/ruby-2.5.3/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/home/<username>/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/<username>/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/mkmf.rb:574:in `block in try_compile'
	from /home/<username>/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/mkmf.rb:521:in `with_werror'
	from /home/<username>/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/mkmf.rb:574:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /home/<username>/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/mkmf.rb:632:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/<username>/.rvm/gems/ruby-2.5.3/extensions/x86_64-linux/2.5.0/nokogiri-1.10.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/<username>/.rvm/gems/ruby-2.5.3/gems/nokogiri-1.10.3 for inspection.
Results logged to /home/<username>/.rvm/gems/ruby-2.5.3/extensions/x86_64-linux/2.5.0/nokogiri-1.10.3/gem_make.out

````

**my mkmf.log**

```
"gcc -o conftest -I/home/<username>/.rvm/rubies/ruby-2.5.3/include/ruby-2.5.0/x86_64-linux -I/home/<username>/.rvm/rubies/ruby-2.5.3/include/ruby-2.5.0/ruby/backward -I/home/<username>/.rvm/rubies/ruby-2.5.3/include/ruby-2.5.0 -I.    -O3 -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wmisleading-indentation -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wimplicit-fallthrough=0 -Wduplicated-cond -Wrestrict  -fPIC  conftest.c  -L. -L/home/<username>/.rvm/rubies/ruby-2.5.3/lib -Wl,-rpath,/home/<username>/.rvm/rubies/ruby-2.5.3/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/<username>/.rvm/rubies/ruby-2.5.3/lib -L/home/<username>/.rvm/rubies/ruby-2.5.3/lib -lruby  -lpthread -lgmp -ldl -lcrypt -lm   -lc "
invalid option: -I

Usage: as [options] command [<args>] [command_options]
Try 'as help [command]' or 'as help options' for more information.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by zarszz** [comment]
fixed with reinstall ruby with rvm
