### ISSUE TITLE
Installation difficulties on Fedora 32 beta

### ISSUE THREAD

**Issue by Colin-Suckow** [sparklemotion/nokogiri#2018]
Error occurs when attempting to install using ```gem install nokogiri```

gem install output
```
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /home/colin/.gem/ruby/gems/nokogiri-1.10.9/ext/nokogiri
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20200401-11102-1tvxe7o.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/usr/share/ruby/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/share/ruby/mkmf.rb:597:in `block in try_compile'
	from /usr/share/ruby/mkmf.rb:544:in `with_werror'
	from /usr/share/ruby/mkmf.rb:597:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /usr/share/ruby/mkmf.rb:655:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/colin/.gem/ruby/extensions/x86_64-linux/2.7.0/nokogiri-1.10.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/colin/.gem/ruby/gems/nokogiri-1.10.9 for inspection.
Results logged to /home/colin/.gem/ruby/extensions/x86_64-linux/2.7.0/nokogiri-1.10.9/gem_make.out

```
mkmf.log contents
```
"gcc -o conftest -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC  conftest.c  -L. -L/usr/lib64 -L. -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic  -m64   -lruby  -lm   -lc "
annobin: conftest.c: ICE: The location of the "-fstack-clash-protection" flag has changed - please rebuild annobin
annobin: conftest.c: ICE: Please contact the annobin maintainer with details of this problem
annobin: conftest.c: Expeceted name: -fstack-clash-protection.  Actual name: -fstack-check=
cc1: error: failed to initialize plugin /usr/lib/gcc/x86_64-redhat-linux/10/plugin/annobin.so
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

Operating system is Fedora 32 beta.

uname -a output
```
Linux colindesktop 5.6.0-300.fc32.x86_64 #1 SMP Mon Mar 30 15:45:58 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Thank you

**Comment by flavorjones** [comment]
Hi @Colin-Suckow, sorry to hear you're having problems. Unfortunately, I don't think what you're seeing is caused by (or can be fixed by) Nokogiri.

I don't know much about `annobin`, but this looks like an issue with compiler flags. For context, C extensions (like Nokogiri) use the same flags that your `ruby` executable was compiled with. You can see these flags to verify this statement:

```
require "rbconfig"
puts RbConfig::CONFIG["CFLAGS"]
```

Can I ask that you verify that the flags emitted by this code include `-fstack-clash-protection`? If so, then this means ruby was compiled with flags that are not valid (perhaps because you upgraded gcc or because something else in your system changed after ruby was compiled/installed?).

You may have similar errors compiling other gems with C extensions, like `sqlite3`, which may also be worth verifying.

**Comment by Colin-Suckow** [comment]
You're spot on about other C extensions not working. I'll continue the search elsewhere. Thank you for the reply, it was very helpful. I'll go ahead and close this for you.
