### ISSUE TITLE
Installation difficulties- `cannot load such file -- mini_portile2`

### ISSUE THREAD

**Issue by DougEdey** [sparklemotion/nokogiri#2072]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

Yes, Nokogiri has been fine in my app for a while, I've recently come back to work on it and nokogiri v1.10.10 is not installing because it can't find `mini_portile2`

If I install the prerelease version of nokogiri it installs fine, but 1.10.10 has this issue.

**What is the complete output of `gem install`?**

```
bundle install
Fetching source index from https://enterprise.contribsys.com/
Fetching gem metadata from https://packages.shopify.io/shopify/gems/....
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://packages.shopify.io/shopify/gems/....
Fetching source index from https://enterprise.contribsys.com/
Using rake 13.0.1
Using Ascii85 1.0.3
Using concurrent-ruby 1.1.7
Using minitest 5.14.2
Using thread_safe 0.3.6
Using zeitwerk 2.4.0
Using builder 3.2.4
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using crass 1.0.6
Using rack 2.2.3
Using nio4r 2.5.2
Using websocket-extensions 0.1.5
Using mimemagic 0.3.4
Using mini_mime 1.0.2
Using jsonapi-renderer 0.2.2
Using mysql2 0.5.3
Using public_suffix 4.0.5
Using afm 0.2.2
Using ansi 1.5.0
Using ast 2.4.1
Using execjs 2.7.0
Using aws-partitions 1.364.0
Using jmespath 1.4.0
Using aws-eventstream 1.1.0
Using smart_properties 1.15.0
Using html_tokenizer 0.0.7
Using method_source 0.9.2
Using thor 0.20.3
Using msgpack 1.3.3
Using bundler 2.1.4
Using semantic 1.6.1
Using browser_sniffer 1.2.1
Using buffered-logger 2.1.0
Using multi_json 1.15.0
Using byebug 10.0.2
Using chunky_png 1.3.11
Using ci-queue 0.20.5
Using climate_control 0.2.0
Using coderay 1.1.2
Using colorize 0.8.1
Using ruby-rc4 0.1.5
Using connection_pool 2.2.3
Using constant_resolver 0.1.5
Using psych 3.1.0
Using safe_yaml 1.0.5
Using csv 3.1.7
Using escape_utils 1.2.1
Using mime-types-data 3.2020.0512
Using net-http-persistent 2.9.4
Using open_uri_redirections 0.2.1
Using ffi 1.13.0
Using uri_template 0.7.0
Using ejson 1.2.1
Using graphql 1.11.4
Using jwt 2.2.2
Using multipart-post 2.1.1
Using semian 0.10.4
Using statsd-instrument 2.9.2
Using redcarpet 3.4.0
Using declarative 0.0.20
Using declarative-option 0.1.0
Using digest-crc 0.6.1
Using unf_ext 0.0.7.7
Using dotenv 2.7.6
Using einhorn 0.7.4
Using filesize 0.1.1
Using memoist 0.16.2
Using os 1.1.0
Using httpclient 2.8.3
Using uber 0.1.0
Using retriable 3.1.2
Using google-cloud-errors 1.0.1
Using google-protobuf 3.13.0 (universal-darwin)
Using hashdiff 1.0.1
Using hashery 2.1.2
Using json 2.3.1
Using snappy 0.0.17
Using sysvmq 0.2.2
Using tros 1.7.6.4
Using kaminari-core 1.2.1
Using king_konf 0.3.7
Using lhm 3.0.0.alpha from git@github.com:Shopify/lhm (at a9ad189@a9ad189)
Using kramdown 1.13.2
Using mini_magick 4.10.1
Using minitest-stub-const 0.6
Using mocha 1.11.2
Using user_agent_parser 2.6.0
Using net-ssh 6.0.2
Using newrelic_rpm 6.9.0.363
Using parallel 1.19.2
Using rainbow 3.0.0
Using regexp_parser 1.7.1
Using rexml 3.2.4
Using ruby-progressbar 1.10.1
Using unicode-display_width 1.7.0
Using sorbet-runtime 0.5.5622
Using pdf-core 0.7.0
Using ttfunk 1.5.1
Using polaris_icons 0.2.3
Using polaris_tokens 2.12.1
Using rb-fsevent 0.10.3
Using tilt 2.0.10
Using schmooze 0.1.6
Using raindrops 0.19.1
Using rcsv 0.3.1
Using redis 4.1.3
Using rubyzip 1.3.0
Using ruby-ole 1.2.12.2
Using scientist 1.4.0
Using shipping_base 0.1.5
Using shopify-money 0.14.5
Using sqlite3 1.4.2
Using timecop 0.9.1
Using toxiproxy 1.0.3 from git@github.com:Shopify/toxiproxy-ruby (at master@c3151c2)
Using ruby-prof 0.17.0
Using typechecked 2.1.0
Using aasm 5.1.1
Using i18n 1.6.0
Using tzinfo 1.2.7
Fetching nokogiri 1.10.10
Using rack-test 1.1.0
Using websocket-driver 0.7.1
Using marcel 0.3.3
Using mail 2.7.1
Using addressable 2.7.0
Using parser 2.7.1.4
Using sprockets 3.7.2
Using minitest-ci 3.4.0
Using bugsnag 6.16.0
Using rack-protection 2.0.8.1
Using puma 4.3.5
Using autoprefixer-rails 7.2.6
Using uglifier 4.2.0
Using bootsnap 1.4.8
Using avro 1.10.0
Using aws-sigv4 1.2.2
Using combine_pdf 1.0.18
Using crack 0.4.3
Using mime-types 3.3.1
Using ethon 0.12.0
Using faraday 0.17.3
Using daggr 0.0.1 from git@github.com:Shopify/daggr (at master@fa11d6e)
Using unf 0.1.4
Using representable 3.0.4
Using googleapis-common-protos-types 1.0.5
Using graphql-schema_comparator 1.0.0
Using ruby-kafka 1.2.0
Using terrapin 0.6.0
Using rb-inotify 0.10.1
Using sassc 2.4.0
Using shopify-tracing 0.7.10
Using pry 0.12.2
Using browserslist_useragent 0.1.3
Using net-sftp 3.0.0
Using pdf-reader 2.1.0
Using prawn 2.2.2
Using shopify_metrics 1.4.1
Using shopify_minitest_reporters 0.1.9
Using spreadsheet 1.2.6
Using request_profiler 0.0.4
Using faker 2.13.0
Using activesupport 6.0.2.2
Using launchy 2.5.0
Using rubocop-ast 0.3.0
Using sprockets-commoner 0.6.4
Using sidekiq 6.0.7
Using aws-sdk-core 3.105.0
Using typhoeus 1.4.0
Using sawyer 0.8.2
Using simpleidn 0.1.1
Using faraday_middleware 0.14.0
Using signet 0.14.0
Using google-cloud-env 1.3.2
Using grpc 1.31.1 (universal-darwin)
Using webmock 3.8.3
Using racecar 1.1.0
Using sass-listen 4.0.0
Using pry-byebug 3.6.0
Using pry-rails 0.3.9
Using pdf-inspector 1.3.0
Using prawn-table 0.2.2
Using globalid 0.4.2
Using activemodel 6.0.2.2
Using case_transform 0.2
Using active_utils 3.3.17
Using aws-sdk-kms 1.37.0
Using identifications 2.1.0
Using csvlint 0.4.0
Using graphql-client 0.16.0
Using dnsruby 1.61.4
Using factory_bot 6.1.0
Using googleauth 0.13.0
Using google-cloud-core 1.5.0
Using measured 2.5.2
Using minerva 0.5.10
Using rubocop 0.89.1
Using shopify_panama 1.2.7
Using sidekiq-pro 5.0.1
Using sidekiq-limit_fetch 3.4.0
Using sass 3.7.4
Using activejob 6.0.2.2
Using octokit 4.18.0
Using aws-sdk-s3 1.79.1
Using country_db 8.6.0
Using activemodel-serializers-xml 1.0.2
Using frozen_record 0.18.0
Using paperclip 6.1.0
Using google-api-client 0.41.1
Using kafka-client-ruby 2.4.0
Using rubocop-performance 1.7.1
Using rubocop-rails 2.6.0
Using rubocop-shopify 1.0.5
Using sidekiq-ent 2.0.1
Using cusco 0.14.8
Using activeresource 5.1.1
Using shopify-i18n 2.4.7
Using google-cloud-storage 1.26.2
Using activerecord 6.0.2.2
Using kafka-shopify 1.7.6 from git@github.com:Shopify/kafka-shopify (at master@d209a60)
Using activerecord-pedantmysql2-adapter 1.2.0
Using encrypted_attr 1.0.1
Using kaminari-activerecord 1.2.1
Using privacy_enforcer 3.5.1
Using monorail 0.1.93.20200902185138
Installing nokogiri 1.10.10 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/doug/.gem/ruby/2.6.6/gems/nokogiri-1.10.10/ext/nokogiri
/opt/rubies/2.6.6/bin/ruby -I /opt/rubies/2.6.6/lib/ruby/2.6.0 -r ./siteconf20200905-17765-ou44ku.rb extconf.rb
checking if the C compiler accepts  -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/rubies/2.6.6/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
/opt/rubies/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- mini_portile2 (LoadError)
	from /opt/rubies/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /opt/rubies/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from extconf.rb:470:in `<main>'
/opt/rubies/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mini_portile2 (LoadError)
	from /opt/rubies/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from extconf.rb:470:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/doug/.gem/ruby/2.6.6/extensions/x86_64-darwin-19/2.6.0-static/nokogiri-1.10.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/doug/.gem/ruby/2.6.6/gems/nokogiri-1.10.10 for inspection.
Results logged to /Users/doug/.gem/ruby/2.6.6/extensions/x86_64-darwin-19/2.6.0-static/nokogiri-1.10.10/gem_make.out
```

**What are the complete contents of the `mkmf.log` file generated during the failed installation?**

```
cat /Users/doug/.gem/ruby/2.6.6/extensions/x86_64-darwin-19/2.6.0-static/nokogiri-1.10.10/mkmf.log
"clang -o conftest -I/opt/rubies/2.6.6/include/ruby-2.6.0/x86_64-darwin19 -I/opt/rubies/2.6.6/include/ruby-2.6.0/ruby/backward -I/opt/rubies/2.6.6/include/ruby-2.6.0 -I.  -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include -I/usr/local/opt/libyaml/include -I/usr/local/opt/gdbm/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens  -pipe  -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 conftest.c  -L. -L/opt/rubies/2.6.6/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/gdbm/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/gdbm/lib     -lruby.2.6-static -framework Security -framework Foundation -lpthread -ldl -lobjc    "
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"clang -I/opt/rubies/2.6.6/include/ruby-2.6.0/x86_64-darwin19 -I/opt/rubies/2.6.6/include/ruby-2.6.0/ruby/backward -I/opt/rubies/2.6.6/include/ruby-2.6.0 -I.  -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include -I/usr/local/opt/libyaml/include -I/usr/local/opt/gdbm/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens  -pipe  -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2   -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main() {return 0;}
/* end */

"clang -I/opt/rubies/2.6.6/include/ruby-2.6.0/x86_64-darwin19 -I/opt/rubies/2.6.6/include/ruby-2.6.0/ruby/backward -I/opt/rubies/2.6.6/include/ruby-2.6.0 -I.  -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include -I/usr/local/opt/libyaml/include -I/usr/local/opt/gdbm/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens  -pipe  -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2 -Wno-error=unused-command-line-argument-hard-error-in-future   -Werror -c conftest.c"
error: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Werror,-Wunknown-warning-option]
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main() {return 0;}
/* end */

```

**What operating system are you using?**

MacOS

If MacOS, please note the version of XCode you have installed.
```
> xcodebuild -version
Xcode 11.7
Build version 11E801a
```

**Comment by flavorjones** [comment]
@DougEdey Sorry you're having problems, I'll try to help.

(Coordinating with Doug in our company Slack, will close the loop here.)

**Comment by flavorjones** [comment]
@DougEdey I couldn't reproduce this using the same toolchain and setup. So I'd like to ask some exploratory questions:

1. what's the output from `bundle info mini_portile2`? Or, if bundler won't tell you because it didn't finish bundling, what's the output from `gem info mini_portile2`?

I see:

```
shipify $ bundle info mini_portile2
  * mini_portile2 (2.4.0)
	Summary: Simplistic port-like solution for developers
	Homepage: http://github.com/flavorjones/mini_portile
	Path: /Users/flavorjones/.gem/ruby/2.6.6/gems/mini_portile2-2.4.0

shipify $ gem info mini_portile2

*** LOCAL GEMS ***

mini_portile2 (2.5.0, 2.4.0)
    Authors: Luis Lavena, Mike Dalessio, Lars Kanis
    Homepage: http://github.com/flavorjones/mini_portile
    License: MIT
    Installed at (2.5.0): /Users/flavorjones/.gem/ruby/2.6.6
                 (2.4.0): /Users/flavorjones/.gem/ruby/2.6.6

    Simplistic port-like solution for developers

```

2. Is the mini_portile2 installation OK? Are the files we expect there? Here's what I see:

```
shipify $ find /Users/flavorjones/.gem/ruby/2.6.6/gems/mini_portile2-2.4.0/lib
/Users/flavorjones/.gem/ruby/2.6.6/gems/mini_portile2-2.4.0/lib
/Users/flavorjones/.gem/ruby/2.6.6/gems/mini_portile2-2.4.0/lib/mini_portile2
/Users/flavorjones/.gem/ruby/2.6.6/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb
/Users/flavorjones/.gem/ruby/2.6.6/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile_cmake.rb
/Users/flavorjones/.gem/ruby/2.6.6/gems/mini_portile2-2.4.0/lib/mini_portile2/version.rb
/Users/flavorjones/.gem/ruby/2.6.6/gems/mini_portile2-2.4.0/lib/mini_portile2.rb
```

3. What is your `bundle config` output? I'd be interested in anything related to paths. Here's what I see:

```
shipify $ bundle config
Settings are listed in order of priority. The top value will be used.
packages.shopify.io
Set for the current user (/Users/flavorjones/.bundle/config): "<redacted>"

jobs
Set for your local app (/Users/flavorjones/src/github.com/Shopify/shipify/.bundle/config): 4
```

(please redact your packages credential!)

4. What's your `gem env`? Here's mine (with shell paths redacted):

```
shipify $ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.6 (2020-03-31 patchlevel 146) [x86_64-darwin19]
  - INSTALLATION DIRECTORY: /Users/flavorjones/.gem/ruby/2.6.6
  - USER INSTALLATION DIRECTORY: /Users/flavorjones/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /opt/rubies/2.6.6/bin/ruby
  - GIT EXECUTABLE: /Users/flavorjones/.nix-profile/bin/git
  - EXECUTABLE DIRECTORY: /Users/flavorjones/.gem/ruby/2.6.6/bin
  - SPEC CACHE DIRECTORY: /Users/flavorjones/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/rubies/2.6.6/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-19
  - GEM PATHS:
     - /Users/flavorjones/.gem/ruby/2.6.6
     - /opt/rubies/2.6.6/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-ri --no-rdoc --no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
... <snip> ...
```

I'm fishing for differences in our configurations, or issues that might be specific to your gem installation.

**Comment by DougEdey** [comment]
## Mini Portile2

Bundle info :(
```
❯ bundle info mini_portile2
Could not find nokogiri-1.10.10 in any of the sources
```


gem info

```
gem info mini_portile2

*** LOCAL GEMS ***

mini_portile2 (2.5.0, 2.4.0)
    Authors: Luis Lavena, Mike Dalessio, Lars Kanis
    Homepage: http://github.com/flavorjones/mini_portile
    License: MIT
    Installed at (2.5.0): /Users/doug/.gem/ruby/2.6.6
                 (2.4.0): /Users/doug/.gem/ruby/2.6.6

    Simplistic port-like solution for developers
```


I think the second question may be the issue:

```
❯ ls /Users/doug/.gem/ruby/2.6.6/gems
bundler-2.1.4       jaro_winkler-1.5.4  mini_portile2-2.5.0 nokogiri-1.10.10    nokogiri-1.11.0.rc2
```

I don't have `mini_portile2-2.4.0` here..


## Bundle config

```
❯ bundle config
Settings are listed in order of priority. The top value will be used.
packages.shopify.io
Set for the current user (/Users/doug/.bundle/config): "<REDACTED>"

build.snappy
Set for the current user (/Users/doug/.bundle/config): "--with-opt-dir=(brew --prefix snappy)"

gem.test
Set for the current user (/Users/doug/.bundle/config): "minitest"

gem.mit
Set for the current user (/Users/doug/.bundle/config): true

gem.coc
Set for the current user (/Users/doug/.bundle/config): true

jobs
Set for your local app (/Users/doug/src/github.com/Shopify/shipify/.bundle/config): 4
```

## Gem env

```
❯ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.6 (2020-03-31 patchlevel 146) [x86_64-darwin19]
  - INSTALLATION DIRECTORY: /Users/doug/.gem/ruby/2.6.6
  - USER INSTALLATION DIRECTORY: /Users/doug/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /opt/rubies/2.6.6/bin/ruby
  - GIT EXECUTABLE: /nix/var/nix/gcroots/dev-profiles/user-extra-profile/bin/git
  - EXECUTABLE DIRECTORY: /Users/doug/.gem/ruby/2.6.6/bin
  - SPEC CACHE DIRECTORY: /Users/doug/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/rubies/2.6.6/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-19
  - GEM PATHS:
     - /Users/doug/.gem/ruby/2.6.6
     - /opt/rubies/2.6.6/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
<<>>>
```

**Comment by DougEdey** [comment]
I tried doing a `gem install mini_portfile2 -v 2.4.0`

```
❯ gem install mini_portfile2 -v 2.4.0
ERROR:  Could not find a valid gem 'mini_portfile2' (= 2.4.0) in any repository
```

**Comment by DougEdey** [comment]
SO I manually installed `gem install mini_portile2 -v 2.4.0` and got through this, but I'm going to chat to @flavorjones about why my system is messed up
