### ISSUE TITLE
ci: Introduce CI coverage for Ruby 3.0.0 release candidate

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2090]
- [x] Create a nokogiri-test image based on Ruby 3.0 RCs (which will involve an update to concourse-gem)
- [x] Add a non-release-blocking job to the CI pipelines
- [x] Make sure it builds without errors (failures would be OK at this point)

**Comment by flavorjones** [comment]
Seeing [this error](https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri/jobs/cruby-3.0-rc/builds/1#L5f68ad83:1287):

```
/usr/local/lib/ruby/3.0.0/bundler/runtime.rb:302:in `check_for_activated_spec!': You have already activated racc 1.5.0, but your Gemfile requires racc 1.4.16. Since racc is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports racc as a default gem. (Gem::LoadError)
	from /usr/local/lib/ruby/3.0.0/bundler/runtime.rb:31:in `block in setup'
	from /usr/local/lib/ruby/3.0.0/bundler/spec_set.rb:147:in `each'
	from /usr/local/lib/ruby/3.0.0/bundler/spec_set.rb:147:in `each'
	from /usr/local/lib/ruby/3.0.0/bundler/runtime.rb:26:in `map'
	from /usr/local/lib/ruby/3.0.0/bundler/runtime.rb:26:in `setup'
	from /usr/local/lib/ruby/3.0.0/bundler.rb:149:in `setup'
	from /usr/local/lib/ruby/3.0.0/bundler/setup.rb:20:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.0.0/bundler/ui/shell.rb:136:in `with_level'
	from /usr/local/lib/ruby/3.0.0/bundler/ui/shell.rb:88:in `silence'
	from /usr/local/lib/ruby/3.0.0/bundler/setup.rb:20:in `<top (required)>'
	from /usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb:83:in `require'
```

**Comment by flavorjones** [comment]
Green build: https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri/jobs/cruby-3.0-rc/builds/5

Closing.
