### ISSUE TITLE
[install] Centos 7 installation difficulties

### ISSUE THREAD

**Issue by pfranchini** [sparklemotion/nokogiri#2117]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [X] Yes!

**What is the complete output of `gem install` or `bundle install`?**
```
[redmine@heplnv153 redmine]$ yum install rpm-build ruby-devel zlib-devel                      
Loaded plugins: fastestmirror, langpacks, priorities
You need to be root to perform this command.
[redmine@heplnv153 redmine]$ bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.                                    
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.                                            
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Using rake 13.0.1
Using concurrent-ruby 1.1.7
Using i18n 1.6.0
Using minitest 5.14.2
Using thread_safe 0.3.6
Using tzinfo 1.2.8
Using activesupport 5.2.4.2
Using builder 3.2.4
Using erubi 1.10.0
Using mini_portile2 2.4.0
Fetching nokogiri 1.10.10
Installing nokogiri 1.10.10 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /redmine/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.10/ext/nokogiri
/opt/rh/rh-ruby26/root/usr/bin/ruby -I /opt/rh/rh-ruby26/root/usr/share/rubygems -r ./siteconf20201129-17583-c79fj6.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib64
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/rh/rh-ruby26/root/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
/opt/rh/rh-ruby26/root/usr/share/ruby/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/rh/rh-ruby26/root/usr/share/ruby/mkmf.rb:585:in `block in try_compile'
        from /opt/rh/rh-ruby26/root/usr/share/ruby/mkmf.rb:532:in `with_werror'
        from /opt/rh/rh-ruby26/root/usr/share/ruby/mkmf.rb:585:in `try_compile'
        from extconf.rb:138:in `nokogiri_try_compile'
        from extconf.rb:162:in `block in add_cflags'
        from /opt/rh/rh-ruby26/root/usr/share/ruby/mkmf.rb:643:in `with_cflags'
        from extconf.rb:161:in `add_cflags'
        from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /redmine/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/nokogiri-1.10.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /redmine/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.10 for inspection.
Results logged to /redmine/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/nokogiri-1.10.10/gem_make.out

An error occurred while installing nokogiri (1.10.10), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.10' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  rails was resolved to 5.2.4.2, which depends on
    actioncable was resolved to 5.2.4.2, which depends on
      actionpack was resolved to 5.2.4.2, which depends on
        actionview was resolved to 5.2.4.2, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            nokogiri
```

**What are the complete contents of the `mkmf.log` file generated during the failed installation?**

```
"gcc -o conftest -I/opt/rh/rh-ruby26/root/usr/include -I/opt/rh/rh-ruby26/root/usr/include/ruby/backward -I/opt/rh/rh-ruby26/root/usr/include -I.    -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -fPIC  conftest.c  -L. -L/opt/rh/rh-ruby26/root/usr/lib64 -L. -Wl,-z,relro -fstack-protector-strong -rdynamic -Wl,-export-dynamic  -m64   -lruby  -lm   -lc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Tell us about your system!**

What is the output from `ruby -v`?
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]

What is the output from `gem -v`?
3.0.3

What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.2 (2019-03-13 patchlevel 47) [x86_64-linux]
  - INSTALLATION DIRECTORY: /opt/rh/rh-ruby26/root/usr/share/gems
  - USER INSTALLATION DIRECTORY: /home/redmine/.gem/ruby
  - RUBY EXECUTABLE: /opt/rh/rh-ruby26/root/usr/bin/ruby
  - GIT EXECUTABLE: 
  - EXECUTABLE DIRECTORY: /opt/rh/rh-ruby26/root/usr/bin
  - SPEC CACHE DIRECTORY: /home/redmine/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc/opt/rh/rh-ruby26
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /opt/rh/rh-ruby26/root/usr/share/gems
     - /home/redmine/.gem/ruby
     - /opt/rh/rh-ruby26/root/usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--user-install --bindir /home/redmine/bin"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /opt/rh/rh-ruby26/root/usr/local/bin
     - /opt/rh/rh-ruby26/root/usr/bin
     - /usr/local/bin
     - /usr/bin
     - /usr/local/sbin
     - /usr/sbin
     - /opt/puppetlabs/bin
     - /home/local/cjm61328/.local/bin
     - /home/local/cjm61328/bin

```

If you're using Bundler:
- what is the output from `bundle version`?
Bundler version 1.17.2 (2018-12-19 commit 3fc4de72b)

- what is the output from `bundle config`? (Take care to redact any credentials)
```
Settings are listed in order of priority. The top value will be used.
path
Set for your local app (/redmine/.bundle/config): "vendor/bundle"

without
Set for your local app (/redmine/.bundle/config): [:development, :test]

```

If Linux or a BSD variant, please note:
- the distro you're using
CentOS Linux release 7.9.2009 (Core)

- the output of `uname -a`
Linux heplnv153.pp.rl.ac.uk 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by flavorjones** [comment]
@pfranchini, sorry you're having problems. Thanks for providing complete information, I'll take a look in a little bit.

**Comment by flavorjones** [comment]
@pfranchini Can you help me understand how you installed your version of Ruby? It looks like Centos 7 comes with (gulp) ruby 2.0.0p548 installed by default, and you're running a ruby installed to `/opt/rh`.

My guess is that you don't have the full development environment set up for that Ruby (so `yum install ruby-devel` is going to be ineffective).

Can you attempt to `gem install bcrypt` on this machine and tell me if that's successful? I like to use `bcrypt` as an example of a ruby gem with a small, self-contained C extension; so if you have the same problem we can isolate it to the toolchain (and not Nokogiri).

**Comment by pfranchini** [comment]
ruby comes from CentOS Software Collections Library  so basically I source in this way (I am just a sudoer and there is puppet taking care of stuff)
`scl enable rh-ruby26 /bin/bash`

apparently the issue is in `gcc`

```
Fetching: bcrypt-3.1.16.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing bcrypt:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. -D__SKIP_GNU    -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -fPIC -m64 -o bcrypt_ext.o -c bcrypt_ext.c
make: gcc: Command not found
make: *** [bcrypt_ext.o] Error 127


Gem files will remain installed in /home/redmine/.gem/ruby/gems/bcrypt-3.1.16 for inspection.
Results logged to /home/redmine/.gem/ruby/gems/bcrypt-3.1.16/ext/mri/gem_make.out
```

```
cat /home/redmine/.gem/ruby/gems/bcrypt-3.1.16/ext/mri/gem_make.out
/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. -D__SKIP_GNU    -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -fPIC -m64 -o bcrypt_ext.o -c bcrypt_ext.c
make: gcc: Command not found
make: *** [bcrypt_ext.o] Error 127
```

**Comment by pfranchini** [comment]
have done a `yum install gcc` so now

```
[ ]$ bundle install --without development test
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.                                    
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.                                            
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.1
Using concurrent-ruby 1.1.7
Using i18n 1.6.0
Using minitest 5.14.2
Using thread_safe 0.3.6
Using tzinfo 1.2.8
Using activesupport 5.2.4.2
Using builder 3.2.4
Using erubi 1.10.0
Using mini_portile2 2.4.0
Fetching nokogiri 1.10.10
Installing nokogiri 1.10.10 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /redmine/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.10/ext/nokogiri
/opt/rh/rh-ruby26/root/usr/bin/ruby -I /opt/rh/rh-ruby26/root/usr/share/rubygems -r ./siteconf20201130-71648-1la5aml.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... yes
checking for iconv... yes
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxml2-2.9.10
with the following patches applied:
        - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
        - 0002-Remove-script-macro-support.patch
        - 0003-Update-entities-to-remove-handling-of-ssi.patch
        - 0004-libxml2.la-is-in-top_builddir.patch
        - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
Extracting libxml2-2.9.10.tar.gz into tmp/x86_64-redhat-linux-gnu/ports/libxml2/2.9.10... OK
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib64
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/rh/rh-ruby26/root/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib64
        --enable-cross-build
        --disable-cross-build
/redmine/vendor/bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:84:in `apply_patch': Failed to complete patch task; patch(1) or git(1) is
required. (RuntimeError)
        from /redmine/vendor/bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:92:in `block in patch'
        from /redmine/vendor/bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:90:in `each'
        from /redmine/vendor/bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:90:in `patch'
        from /redmine/vendor/bundle/ruby/2.6.0/gems/mini_portile2-2.4.0/lib/mini_portile2/mini_portile.rb:152:in `cook'
        from extconf.rb:365:in `block (2 levels) in process_recipe'
        from extconf.rb:257:in `block in chdir_for_build'
        from extconf.rb:256:in `chdir'
        from extconf.rb:256:in `chdir_for_build'
        from extconf.rb:364:in `block in process_recipe'
        from extconf.rb:262:in `tap'
        from extconf.rb:262:in `process_recipe'
        from extconf.rb:557:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /redmine/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/nokogiri-1.10.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /redmine/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.10 for inspection.
Results logged to /redmine/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/nokogiri-1.10.10/gem_make.out

An error occurred while installing nokogiri (1.10.10), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.10' --source 'https://rubygems.org/'` succeeds before bundling.                                                               

In Gemfile:
  rails was resolved to 5.2.4.2, which depends on
    actioncable was resolved to 5.2.4.2, which depends on
      actionpack was resolved to 5.2.4.2, which depends on
        actionview was resolved to 5.2.4.2, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            nokogiri
```

**Comment by pfranchini** [comment]
Solve.
`git` and `patch` were missing.
With `gem` `nokogiri` would build but for `bundled` had to do
```
bundle config build.nokogiri --with-xml2-config=/opt/puppetlabs/puppet/include/libxml2 --with-xslt-config=/opt/puppetlabs/puppet/include/libxslt --with-zlib-include=/usr/include/  
```
Thanks

**Comment by flavorjones** [comment]
@pfranchini Thanks for closing the loop here. Can I ask for a suggestion on how to improve the installation documentation here:

- https://nokogiri.org/tutorials/installing_nokogiri.html#fedora-red-hat-and-centos
- for which the source is at https://github.com/sparklemotion/nokogiri.org/blob/master/docs/tutorials/installing_nokogiri.md#fedora-red-hat-and-centos
