### ISSUE TITLE
[bug] cannot load such file -- nokogiri/nokogiri (v=1.13.1 on Mac M1 with Docker)

### ISSUE THREAD

**Issue by matheusvetor** [sparklemotion/nokogiri#2430]
I'm using docker with docker compose on macbook air M1. When updating nokogiri from 1.12.5 to 1.13.1 on a new Rails 7 project the following error shows up. I already see the 1.13 implements `aarch64-linux` version and thats the problem when using the setup like mine.

NOTE: I built a similar docker environment to run nokogiri tests and except for rubocop, all other rake stack are running ok. 
```
2.128333s test_0006_supports a line number greater than a short int#Nokogiri::XML::Node::#line
0.586617s test_version_info_for_libxslt#TestVersionInfo::RequireNokogiri
0.428044s test_version_info_for_libxml#TestVersionInfo::RequireNokogiri
0.410100s test_version_info_for_libxslt#TestVersionInfo::RequireVersionFileOnly
0.287989s test_add_namespace#Nokogiri::XML::TestUnparentedNode
0.248674s test_version_info_for_libxml#TestVersionInfo::RequireVersionFileOnly
0.186723s test_0033_test_large_cdata_is_handled#Nokogiri::XML::SAX::Parser
0.150187s test_document_root_can_have_a_processing_instruction_sibling_via_add_next_sibling#Nokogiri::XML::TestUnparentedNode
0.143485s test_0001_adds new keywords and ignores existing keywords#keyword attribute helpers::kwattr_add::given a string of keywords
0.143350s test_reader_blocking#Nokogiri::XML::TestReader

2370 tests, 8410 assertions, 0 failures, 0 errors, 17 skips
```

Basic Gemfile:
```
ruby '3.0.3'

gem 'rails', github: 'rails/rails', branch: 'main'

gem 'nokogiri', '1.12.5'

gem 'coffee-rails',  '5.0.0'

gem 'sprockets-rails', '3.4.2'

gem 'pg', '1.2.3'

gem 'puma', '5.5.2'

gem 'jbuilder', '2.11.5'

gem 'redis', '4.5.1'

gem 'slim', '4.1.0'
...
```

Dockerfile:
```
FROM ruby:3.0-alpine
RUN apk --update --no-cache add build-base nodejs git zsh bash curl tzdata postgresql-dev \
                     postgresql-client libxslt-dev libxml2-dev imagemagick
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

ENV BUNDLE_PATH=/bundle \
    BUNDLE_BIN=/bundle/bin \
    GEM_HOME=/bundle
ENV PATH="${BUNDLE_BIN}:${PATH}"

RUN bundle install
```

The error:
```
 /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:46:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:46:in `require'
   from /bundle/ruby/3.0.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/extension.rb:30:in `rescue in <main>'
   from /bundle/ruby/3.0.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/extension.rb:4:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:62:in `require_relative'
   from /bundle/ruby/3.0.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri.rb:10:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/actiontext/lib/action_text.rb:6:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/actiontext/lib/action_text/engine.rb:8:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /app/config/application.rb:12:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/railties/lib/rails/commands/server/server_command.rb:137:in `block in perform'
   from <internal:kernel>:90:in `tap'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/railties/lib/rails/commands/server/server_command.rb:134:in `perform'
   from /bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
   from /bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
   from /bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/railties/lib/rails/command/base.rb:87:in `perform'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/railties/lib/rails/command.rb:48:in `invoke'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/railties/lib/rails/commands.rb:18:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from bin/rails:4:in `<main>'
 /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require': Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /bundle/ruby/3.0.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/3.0/nokogiri.so) - /bundle/ruby/3.0.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/3.0/nokogiri.so (LoadError)
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:62:in `require_relative'
   from /bundle/ruby/3.0.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/extension.rb:7:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:62:in `require_relative'
   from /bundle/ruby/3.0.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri.rb:10:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/actiontext/lib/action_text.rb:6:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/actiontext/lib/action_text/engine.rb:8:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /app/config/application.rb:12:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/railties/lib/rails/commands/server/server_command.rb:137:in `block in perform'
   from <internal:kernel>:90:in `tap'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/railties/lib/rails/commands/server/server_command.rb:134:in `perform'
   from /bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
   from /bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
   from /bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/railties/lib/rails/command/base.rb:87:in `perform'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/railties/lib/rails/command.rb:48:in `invoke'
   from /bundle/ruby/3.0.0/bundler/gems/rails-3be590edbeda/railties/lib/rails/commands.rb:18:in `<main>'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from /bundle/ruby/3.0.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
   from bin/rails:4:in `<main>'
```

**Comment by flavorjones** [comment]
@matheusvetor Thanks for asking this question, and sorry you're having problems.

Your log file tells the story:

> Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /bundle/ruby/3.0.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/3.0/nokogiri.so)

The installation documentation has been updated within the last couple of weeks to address this issue:

https://nokogiri.org/tutorials/installing_nokogiri.html#linux-musl-error-loading-shared-library

I'll save you a click:

> ### [Linux musl] "Error loading shared library"
> 
> Musl-based systems like Alpine may not have a glibc-compatible library installed, leading to problems running the precompiled native gems.
> 
> #### Symptoms
> 
> Installation succeeds, but then at runtime you'll see an error like this:
> 
> ``` text
> Error loading shared library ld-linux-x86-64.so.2: No such file or directory
> ```
> 
> or like this if you're on ARM64:
> 
> ``` text
> Error loading shared library ld-linux-aarch64.so.1: No such file or directory
> ```
> 
> #### Solution
> 
> Install the glibc compatibility layer:
> 
> ``` sh
> apk add gcompat
> ```
> 
> See https://wiki.alpinelinux.org/wiki/Running_glibc_programs for more details.
> 
> 
>
