### ISSUE TITLE
[install] xz-utils new dependency on linux/arm/v7

### ISSUE THREAD

**Issue by stefansundin** [sparklemotion/nokogiri#2466]
It appears as 2cf26d97fccf81837baa68b2fdee19db04d36bc2 introduces a new dependency for linux/arm/v7. I now need to install `xz-utils` to decompress the new archive (was `.tar.gz` before, now `.tar.xz`). I build multi-arch Docker images of https://github.com/stefansundin/rssbox, and it only failed for linux/arm/v7, presumably because prebuilt binaries are missing for this arch? 🤷 

I reported the issue as a comment on the commit above and was told to create an issue with more information. I solved my problem by installing `xz-utils` so feel free to close the issue at your convenience. However, it would be nice to have prebuilt binaries for this arch.

**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [x] Yes!

**What is the complete output of `gem install` or `bundle install`?**

```
# xz
bash: xz: command not found

# gem install nokogiri
Fetching mini_portile2-2.8.0.gem
Fetching nokogiri-1.13.3.gem
Successfully installed mini_portile2-2.8.0
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/ruby/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.3/ext/nokogiri
/usr/local/ruby/bin/ruby -I /usr/local/ruby/lib/ruby/3.1.0 -r ./siteconf20220222-10-jzkf62.rb extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... yes
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS... yes
checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
Using mini_portile version 2.8.0
checking for iconv... yes
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxml2-2.9.13.
Configuration options: --host\=armv7l-unknown-linux-gnueabihf --enable-static --disable-shared --libdir\=/usr/local/ruby/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.3/ports/armv7l-linux-eabihf/libxml2/2.9.13/lib --with-iconv\=yes --disable-dependency-tracking --without-python --without-readline --with-c14n --with-debug --with-threads --disable-shared --enable-static CFLAGS\=-O2\ -U_FORTIFY_SOURCE\ -g\ -fPIC
The following patches are being applied:
  - 0001-Remove-script-macro-support.patch
  - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0003-libxml2.la-is-in-top_builddir.patch
  - 0004-use-glibc-strlen.patch
  - 0005-avoid-isnan-isinf.patch
  - 0006-update-automake-files-for-arm64.patch
  - 0008-htmlParseComment-handle-abruptly-closed-comments.patch
  - 0009-allow-wildcard-namespaces.patch
  - 0010-Revert-Different-approach-to-fix-quadratic-behavior.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Note, however, that nokogiri cannot guarantee compatibility with every
version of libxml2 that may be provided by OS/package vendors.

[{:url=>
   "https://mirror.csclub.uwaterloo.ca/gnome/sources/libxml2/2.9/libxml2-2.9.13.tar.xz",
  :sha256=>"276130602d12fe484ecc03447ee5e759d0465558fbc9d6bd144e3745306ebf0e"}]
Extracting libxml2-2.9.13.tar.xz into tmp/armv7l-unknown-linux-gnueabihf/ports/libxml2/2.9.13... ERROR, review '/usr/local/ruby/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.3/ext/nokogiri/tmp/armv7l-unknown-linux-gnueabihf/ports/libxml2/2.9.13/extract.log' to see what happened. Last lines are:
========================================================================
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/ruby/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--prevent-strip
	--enable-system-libraries
	--disable-system-libraries
	--use-system-libraries
	--enable-system-libraries
	--disable-system-libraries
	--use-system-libraries
	--enable-static
	--disable-static
	--enable-cross-build
	--disable-cross-build
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--with-xml2-source-dir
/usr/local/ruby/lib/ruby/gems/3.1.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:460:in `block in execute': Failed to complete extract task (RuntimeError)
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:426:in `chdir'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:426:in `execute'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:413:in `extract_file'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:90:in `block in extract'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:88:in `each'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:88:in `extract'
	from /usr/local/ruby/lib/ruby/gems/3.1.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:183:in `cook'
	from extconf.rb:528:in `block (2 levels) in process_recipe'
	from extconf.rb:309:in `chdir'
	from extconf.rb:309:in `chdir_for_build'
	from extconf.rb:528:in `block in process_recipe'
	from <internal:kernel>:90:in `tap'
	from extconf.rb:427:in `process_recipe'
	from extconf.rb:781:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/ruby/lib/ruby/gems/3.1.0/extensions/armv7l-linux-eabihf/3.1.0/nokogiri-1.13.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/ruby/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.3 for inspection.
Results logged to /usr/local/ruby/lib/ruby/gems/3.1.0/extensions/armv7l-linux-eabihf/3.1.0/nokogiri-1.13.3/gem_make.out
```

**If installation failed during compilation, what are the complete contents of the `mkmf.log` file generated during the failed installation?**

```
# cat /usr/local/ruby/lib/ruby/gems/3.1.0/extensions/armv7l-linux-eabihf/3.1.0/nokogiri-1.13.3/mkmf.log
block in append_cflags: checking for whether -std=c99 is accepted as CFLAGS... -------------------- yes

LD_LIBRARY_PATH=.:/usr/local/ruby/lib "gcc -o conftest -I/usr/local/ruby/include/ruby-3.1.0/armv7l-linux-eabihf -I/usr/local/ruby/include/ruby-3.1.0/ruby/backward -I/usr/local/ruby/include/ruby-3.1.0 -I. -I/usr/local/ruby/include  -D_FILE_OFFSET_BITS=64   -s -fPIC conftest.c  -L. -L/usr/local/ruby/lib -Wl,-rpath,/usr/local/ruby/lib -L. -L/usr/local/ruby/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed     -Wl,-rpath,/usr/local/ruby/lib -L/usr/local/ruby/lib -lruby  -lm  -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

LD_LIBRARY_PATH=.:/usr/local/ruby/lib "gcc -I/usr/local/ruby/include/ruby-3.1.0/armv7l-linux-eabihf -I/usr/local/ruby/include/ruby-3.1.0/ruby/backward -I/usr/local/ruby/include/ruby-3.1.0 -I. -I/usr/local/ruby/include  -D_FILE_OFFSET_BITS=64   -s -fPIC  -std=c99 -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

--------------------

block in append_cflags: checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... -------------------- yes

LD_LIBRARY_PATH=.:/usr/local/ruby/lib "gcc -I/usr/local/ruby/include/ruby-3.1.0/armv7l-linux-eabihf -I/usr/local/ruby/include/ruby-3.1.0/ruby/backward -I/usr/local/ruby/include/ruby-3.1.0 -I. -I/usr/local/ruby/include  -D_FILE_OFFSET_BITS=64   -s -fPIC -std=c99  -Wno-declaration-after-statement -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

--------------------

block in append_cflags: checking for whether -g is accepted as CFLAGS... -------------------- yes

LD_LIBRARY_PATH=.:/usr/local/ruby/lib "gcc -I/usr/local/ruby/include/ruby-3.1.0/armv7l-linux-eabihf -I/usr/local/ruby/include/ruby-3.1.0/ruby/backward -I/usr/local/ruby/include/ruby-3.1.0 -I. -I/usr/local/ruby/include  -D_FILE_OFFSET_BITS=64   -s -fPIC -std=c99 -Wno-declaration-after-statement  -g -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

--------------------

block in append_cflags: checking for whether -Winline is accepted as CFLAGS... -------------------- yes

LD_LIBRARY_PATH=.:/usr/local/ruby/lib "gcc -I/usr/local/ruby/include/ruby-3.1.0/armv7l-linux-eabihf -I/usr/local/ruby/include/ruby-3.1.0/ruby/backward -I/usr/local/ruby/include/ruby-3.1.0 -I. -I/usr/local/ruby/include  -D_FILE_OFFSET_BITS=64   -s -fPIC -std=c99 -Wno-declaration-after-statement -g  -Winline -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

--------------------

block in append_cflags: checking for whether -Wmissing-noreturn is accepted as CFLAGS... -------------------- yes

LD_LIBRARY_PATH=.:/usr/local/ruby/lib "gcc -I/usr/local/ruby/include/ruby-3.1.0/armv7l-linux-eabihf -I/usr/local/ruby/include/ruby-3.1.0/ruby/backward -I/usr/local/ruby/include/ruby-3.1.0 -I. -I/usr/local/ruby/include  -D_FILE_OFFSET_BITS=64   -s -fPIC -std=c99 -Wno-declaration-after-statement -g -Winline  -Wmissing-noreturn -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

--------------------

try_link_iconv: checking for iconv... -------------------- yes

LD_LIBRARY_PATH=.:/usr/local/ruby/lib "gcc -o conftest -I/usr/local/ruby/include/ruby-3.1.0/armv7l-linux-eabihf -I/usr/local/ruby/include/ruby-3.1.0/ruby/backward -I/usr/local/ruby/include/ruby-3.1.0 -I. -I/usr/local/ruby/include  -D_FILE_OFFSET_BITS=64   -s -fPIC -std=c99 -Wno-declaration-after-statement -g -Winline -Wmissing-noreturn conftest.c  -L. -L/usr/local/ruby/lib -Wl,-rpath,/usr/local/ruby/lib -L. -L/usr/local/ruby/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed     -Wl,-rpath,/usr/local/ruby/lib -L/usr/local/ruby/lib -lruby  -lm  -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: #include <stdlib.h>
 4: #include <iconv.h>
 5: int main(void)
 6: {
 7:     iconv_t cd = iconv_open("", "");
 8:     iconv(cd, NULL, NULL, NULL, NULL);
 9:     return EXIT_SUCCESS;
10: }
/* end */

--------------------
```

**Tell us about your system!**

What is the output from `ruby -v`? `ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [armv7l-linux-eabihf]`

What is the output from `gem -v`? `3.3.7`

What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.7
  - RUBY VERSION: 3.1.1 (2022-02-18 patchlevel 18) [armv7l-linux-eabihf]
  - INSTALLATION DIRECTORY: /usr/local/ruby/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: /root/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: /usr/local/ruby/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/ruby/bin
  - SPEC CACHE DIRECTORY: /root/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/ruby/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - armv7l-linux-eabihf
  - GEM PATHS:
     - /usr/local/ruby/lib/ruby/gems/3.1.0
     - /root/.local/share/gem/ruby/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - bin
     - /usr/local/ruby/bin
     - /usr/local/ruby-build/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```

If Linux or a BSD variant, please note:
- the distro you're using. Docker based on `debian:bullseye-slim`
- the output of `uname -a`. `Linux fc019506aef1 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 armv7l GNU/Linux`
- the contents of `/etc/lsb-release`.

**Comment by larskanis** [comment]
Rake-compiler-dock already has the target `arm-linux` for arm/v7. It is not activated in nokogiri yet.

**Comment by flavorjones** [comment]
@larskanis Well, gosh. I guess I'll go check that out, then! Thanks as always for your amazing rake-compiler-dock work.

**Comment by flavorjones** [comment]
I've created #2467 to drive native gem support for this platform.

I've updated nokogiri.org with some troubleshooting info:

https://nokogiri.org/tutorials/installing_nokogiri.html#tar-child-xz-cannot-exec-no-such-file-or-directory

This is what it looks like:

![image](https://user-images.githubusercontent.com/8207/155331626-06290c7e-3966-49c4-9626-9e4e903c1e45.png)

@stefansundin Thanks again for opening this issue! :heart: :heart: :heart:

**Comment by flavorjones** [comment]
Note that v1.14.0 will support arm-linux as a native gem. See #2533 for details. I'd love help testing it once a release candidate is out.
