### ISSUE TITLE
Nokogiri gem version upgraded after rails 5.2.6.2 is breaking the docker setup - version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by saranya-sanju** [sparklemotion/nokogiri#2470]
Facing issue in docker setup after nokogiri gem version upgraded in rails 5.2.6.2. The app server is not running due to this error.

The issue is - /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

Below are the configurations used 

**OS**: MAC OS Big Sur
**Ruby version**: 2.6.7
**Rails version**: 5.2.6.2
**Tried Nokogiri version**: 1.13.1, 1.13.2, 1.13.3

Below is the DockerFile we are using:
```
FROM ruby:2.6.7

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends build-essential wkhtmltopdf nodejs vim && \
	rm -rf /var/lib/apt/lists/*

RUN mkdir /myapp
WORKDIR /myapp
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

ENV BUNDLE_PATH=/bundle \
    BUNDLE_BIN=/bundle/bin \
    GEM_HOME=/bundle
ENV PATH="${BUNDLE_BIN}:${PATH}"
ENV BUNDLER_VERSION=2.3.0
ENV EXECJS_RUNTIME=Node
RUN gem update --system && gem install bundler -v $BUNDLER_VERSION
```

Below is the backtrace of the error faced while running docker

```
ERROR: It looks like you're trying to use Nokogiri as a precompiled native gem on a system with glibc < 2.17:
app_1          | 
app_1          |   /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /bundle/ruby/2.6.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/2.6/nokogiri.so) - /bundle/ruby/2.6.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/2.6/nokogiri.so
app_1          | 
app_1          |   If that's the case, then please install Nokogiri via the `ruby` platform gem:
app_1          |       gem install nokogiri --platform=ruby
app_1          |   or:
app_1          |       bundle config set force_ruby_platform true
app_1          | 
app_1          |   Please visit https://nokogiri.org/tutorials/installing_nokogiri.html for more help.
app_1          | 
app_1          | /bundle/ruby/2.6.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/extension.rb:7:in `require_relative': /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /bundle/ruby/2.6.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/2.6/nokogiri.so) - /bundle/ruby/2.6.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/2.6/nokogiri.so (LoadError)
app_1          | 	from /bundle/ruby/2.6.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri/extension.rb:7:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri.rb:10:in `require_relative'
app_1          | 	from /bundle/ruby/2.6.0/gems/nokogiri-1.13.1-aarch64-linux/lib/nokogiri.rb:10:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/loofah-2.14.0/lib/loofah.rb:4:in `require'
app_1          | 	from /bundle/ruby/2.6.0/gems/loofah-2.14.0/lib/loofah.rb:4:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/rails-html-sanitizer-1.4.2/lib/rails-html-sanitizer.rb:2:in `require'
app_1          | 	from /bundle/ruby/2.6.0/gems/rails-html-sanitizer-1.4.2/lib/rails-html-sanitizer.rb:2:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/sanitize_helper.rb:4:in `require'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/sanitize_helper.rb:4:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/text_helper.rb:34:in `require'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/text_helper.rb:34:in `<module:TextHelper>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/text_helper.rb:31:in `<module:Helpers>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/text_helper.rb:8:in `<module:ActionView>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/text_helper.rb:6:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/form_tag_helper.rb:20:in `require'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/form_tag_helper.rb:20:in `<module:FormTagHelper>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/form_tag_helper.rb:16:in `<module:Helpers>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/form_tag_helper.rb:10:in `<module:ActionView>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/form_tag_helper.rb:8:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/form_helper.rb:6:in `require'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers/form_helper.rb:6:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers.rb:54:in `require'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers.rb:54:in `<module:Helpers>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers.rb:6:in `<module:ActionView>'
app_1          | 	from /bundle/ruby/2.6.0/gems/actionview-5.2.6.2/lib/action_view/helpers.rb:5:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/context.rb:1:in `require'
app_1          | 	from /bundle/ruby/2.6.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/context.rb:1:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:10:in `require'
app_1          | 	from /bundle/ruby/2.6.0/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:10:in `<top (required)>'
app_1          | 	from /myapp/config/application.rb:8:in `require'
app_1          | 	from /myapp/config/application.rb:8:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/railties-5.2.6.2/lib/rails/commands/server/server_command.rb:145:in `require'
app_1          | 	from /bundle/ruby/2.6.0/gems/railties-5.2.6.2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
app_1          | 	from /bundle/ruby/2.6.0/gems/railties-5.2.6.2/lib/rails/commands/server/server_command.rb:142:in `tap'
app_1          | 	from /bundle/ruby/2.6.0/gems/railties-5.2.6.2/lib/rails/commands/server/server_command.rb:142:in `perform'
app_1          | 	from /bundle/ruby/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
app_1          | 	from /bundle/ruby/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
app_1          | 	from /bundle/ruby/2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
app_1          | 	from /bundle/ruby/2.6.0/gems/railties-5.2.6.2/lib/rails/command/base.rb:69:in `perform'
app_1          | 	from /bundle/ruby/2.6.0/gems/railties-5.2.6.2/lib/rails/command.rb:46:in `invoke'
app_1          | 	from /bundle/ruby/2.6.0/gems/railties-5.2.6.2/lib/rails/commands.rb:18:in `<top (required)>'
app_1          | 	from /myapp/bin/rails:9:in `require'
app_1          | 	from /myapp/bin/rails:9:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
app_1          | 	from /bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
app_1          | 	from /bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
app_1          | 	from /bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
app_1          | 	from /bundle/ruby/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
app_1          | 	from /bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
app_1          | 	from /bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
app_1          | 	from /myapp/bin/spring:13:in `require'
app_1          | 	from /myapp/bin/spring:13:in `<top (required)>'
app_1          | 	from bin/rails:3:in `load'
app_1          | 	from bin/rails:3:in `<main>'
```

Can anyone help in resolving this error in docker?

**Comment by flavorjones** [comment]
I'm going to go ahead and close this, but please do let me know if there's anything you need help with.

**Comment by stanhu** [comment]
@flavorjones We ran into this while installing Nokogiri 1.13 on Amazon Linux 2 and Debian 10. I think https://github.com/rake-compiler/rake-compiler-dock/pull/68 should help here?
