### ISSUE TITLE
mini_portile2 fails when 'unlink'-ing temp log-file in Windows [install]

### ISSUE THREAD

**Issue by andrewcarver** [sparklemotion/nokogiri#2558]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [x] Yes!

Although I'm trying to install an earlier version of Nokogiri (1.8.5 -- due to `~> 1.8.1` dependency of the main gem I'm trying to install -- which is in turn dependent on mini_portile2 v. 2.3.0), I believe the problem derives from code still present in the latest version of Mini_portile (2.8.0). So, please bear with me, to see whether you agree that this code-bit is problematic :)

> (I reckon that if I'm right about the cause -- which I believe is a Windows-portability problem --  any fix you have for it may work on the earlier v. of mini_portile, potentially solving my problem ... In the meantime, though, I've suggested to the handlers of the "main gem I'm trying to install" that they might be able to shift to a `>=1.11.0` version of Nokogiri, supporting native-gem installation on Windows thereby ;)

So, I'm trying to install Nokogiri 1.8.5 on my brand-new Windows 10 machine. My new Ruby 3.1.1 install is via Chocolatey ( [https://community.chocolatey.org/packages/ruby](url) ). For whatever reason, the 1.8.5 install on this machine wants to BUILD Nokogiri (though on my previous Windows 10 machine, I don't recall it needing to do so). 

Thus, I found it necessary (or at least helpful) to install also the Chocolatey package for MSYS2 ( [https://community.chocolatey.org/packages/msys2](url) ). After the latter install, I was able to use `ridk install 1 2 3` to completion, receiving the message "Install MSYS2 and MINGW development toolchain succeeded".

But the gem-install depending on Nokogiri 1.8.5 hung (after "`Building native extensions. This could take a while...`"). An attempted install with

`gem install nokogiri --version '1.8.5' -V`

generated lots of ouput; but most helpfully, the following trace:

````
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:302:in `unlink': Permission denied @ apply2files - C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.8.5/ext/nokogiri/tmp/x86_64-w64-mingw32/ports/libiconv/1.15/configure.log (Errno::EACCES)
    from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:302:in `block in log_file'
    from <internal:kernel>:90:in `tap'
    from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:301:in `log_file'
    from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:371:in `execute'
    from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:108:in `configure'
    from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:153:in `cook'
    from extconf.rb:365:in `block (2 levels) in process_recipe'
    from extconf.rb:257:in `block in chdir_for_build'
    from extconf.rb:256:in `chdir'
    from extconf.rb:256:in `chdir_for_build'
    from extconf.rb:364:in `block in process_recipe'
    from <internal:kernel>:90:in `tap'
    from extconf.rb:262:in `process_recipe'
    from extconf.rb:516:in `<main>'
ERROR:  Error installing asciidoctor-bibliography:
    ERROR: Failed to build gem native extension.
````

Now, to my mind, the most-informative line there is this one:

`C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:302:in 'unlink'' Permission denied @ apply2files - C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/nokogiri-1.8.5/ext/nokogiri/tmp/x86_64-w64-mingw32/ports/libiconv/1.15/configure.log (Errno::EACCES)`

The line of code this is pointing to is in this method from mini_portile.rb:

````
  def log_file(action)`
    @log_files[action] ||=`
      File.expand_path("#{action}.log", tmp_path).tap { |file|`
        File.unlink(file) if File.exist?(file)`
      }`
 end
````
Judging from the stack-trace, the build of nokogiri fails when the line
`File.unlink(file) if File.exist?(file)`
fails to unlink the 'configure.log' file, due to a Windows errno 'EACCES'.

I tried the first thing that comes to mind: to liberalise the permissions on the file itself; none of that solved the problem. But 'EACCES' doesn't pertain to that, necessarily; it has to do with an attempt to do anything to/with a file that is not permitted, by the nature or status of the file (e.g., trying to write to a read-only file). And [in Windows that includes trying to delete (or "unlink") a file that's still open for any process](https://stackoverflow.com/questions/8678086/is-it-okay-to-unlink-files-without-closing-them-in-ruby) (including the current one).

Which is why numerous posts say that if you're going to write Ruby in a Windows-compatible way, [you have to be careful about this](https://stackoverflow.com/questions/3202329/will-we-ever-be-able-to-delete-an-open-file-in-windows): e.g, you may [decide to use Tempfile instead of File](https://ruby-doc.org/stdlib-2.7.0/libdoc/tempfile/rdoc/Tempfile.html#method-i-unlink-label-Unlink-before-close) when you want to create (and then delete) a temporary-only file.

Interestingly, this same mini_portile.rb script DOES make use of Tempfile -- including Tempfile.close() -- but, only for the temporary files downloaded, NOT for this temporary log-file...

So, what do you reckon? Isn't Windows complaining, here, that mini_portile.rb is trying to delete (unlink) a file that it hasn't yet closed -- which prior closure Windows requires?

And, why not use Tempfile -- including Tempfile.close() -- in this case, as in other cases in the script?

**If installation failed during compilation, what are the complete contents of the `mkmf.log` file generated during the failed installation?**

Here I must apologize: Though in earlier attempts I did get a resulting `mkmf.log` file, the most recent runs (which were AFTER a successful native-gem install of the latest Nokogiri version) left an empty folder where that file should be -- and I didn't think to save the output of the file when it was being generated. I can tell you that there seemed, to me, nothing pertinent to this install-issue in the file's contents.

**Tell us about your system!**

What is the output from `ruby -v`?

`ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]`

What is the output from `gem -v`?

3.3.7

What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.7
  - RUBY VERSION: 3.1.1 (2022-02-18 patchlevel 18) [x64-mingw-ucrt]
  - INSTALLATION DIRECTORY: C:/tools/ruby31/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: C:/Users/andyc/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: C:/tools/ruby31/bin/ruby.exe
  - GIT EXECUTABLE:
  - EXECUTABLE DIRECTORY: C:/tools/ruby31/bin
  - SPEC CACHE DIRECTORY: C:/Users/andyc/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
     - ruby
     - x64-mingw-ucrt
  - GEM PATHS:
     - C:/tools/ruby31/lib/ruby/gems/3.1.0
     - C:/Users/andyc/.local/share/gem/ruby/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Program Files (x86)\Common Files\Oracle\Java\javapath
     - C:\tools\ruby31\bin
     - C:\Program Files\Antenna House\AHFormatterV72
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Windows\System32\OpenSSH\
     - C:\ProgramData\chocolatey\bin
     - C:\Strawberry\c\bin
     - C:\Strawberry\perl\site\bin
     - C:\Strawberry\perl\bin
     - C:\Users\andyc\AppData\Roaming\nvm
     - C:\Program Files\nodejs
     - C:\Program Files (x86)\PuTTY\
     - C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\
     - C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\
     - C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\
     - C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\
     - C:\Users\andyc\AppData\Local\Microsoft\WindowsApps
     - C:\Users\andyc\AppData\Roaming\nvm
     - C:\Program Files\nodejs
     - C:\Users\andyc\AppData\Local\atom\bin
     - C:\Users\andyc\AppData\Local\GitHubDesktop\bin
     - C:\tools\msys64
```

**Comment by flavorjones** [comment]
@andrewcarver Thanks for opening this issue, and sorry you're having problems.

I'm a bit confused by your description -- were you able to install after deleting that temporary directory? That seems like the obvious thing to try if you haven't tried it already.

I suspect the file couldn't be deleted because it was still open (being written to) by a previous `gem install` subprocess that hadn't completed, or was terminated but didn't exit. I'm unable to reproduce this and that's the first possible cause that comes to mind.

If you can figure out how to reproduce this, and wanted to file a bug report upstream with `mini_portile2` (which I also maintain) I'm open to taking a deeper look. Otherwise, though, I'm not going to spend time digging into this because the version of the software is quite old and there seems like an easy workaround (mentioned above).

**Comment by andrewcarver** [comment]
@flavorjones Thanks for the prompt reply. Let me try to clarify, please:

> I'm a bit confused by your description -- were you able to install after deleting that temporary directory?

No, I've not gotten the install (of 1.8.5) to succeed.
Sorry, which directory? I did try deleting the configure.log file and re-running, but all that returns different is to open a Windows Explorer window, to the now empty folder `C:\tools\ruby31\lib\ruby\gems\3.1.0\gems\nokogiri-1.8.5\ext\nokogiri\tmp\x86_64-w64-mingw32\ports\libiconv\1.15`, and to give me a Windows pop-up informing me that

> Location is not available
> C:\tools\ruby31\lib\ruby\gems\3.1.0\gems\nokogiri-1.8.5\ext\nokogiri\tmp\x86_6...\libiconv is unavailable. If the location is on this PC, make sure the device or drive is connected or the disc is inserted, and then try again. If the location is on a network, make sure you're connected to the network or Internet, and then try again. If the location still can't be found, it might have been moved or deleted.

So, it doesn't like that at all -- but nor does it end the process and give me back the command prompt. But if (after closing this command-window and opening another) I try the install again -- and even though the process hangs again -- before it hangs, it re-populates this folder, with three files (and a sub-folder), including configure.log.



> I suspect the file couldn't be deleted because it was still open (being written to) by a previous gem install subprocess that hadn't completed, or was terminated but didn't exit.

Yes, that's my guess. And I thought it would be the process (whichever one it is) that creates (or, as I just mentioned, re-creates) the contents of the above folder ... But then, the fact that I can't even close my command-window with `exit`, after one of these runs, does make me wonder, "what's going on under the ground" ... and, the fact that I'm no longer even able to get the stack-trace, in any install-attempt with `-V` --: the screen-output just hangs, at the point where it's trying to do the Nokogiri build. 

So, something seems to be still "hung", even after I Ctrl+C (just to get my command prompt back). But even after I close that command-window, or even re-boot the machine .... the next time I run the install, I get the same problem.

> If you can figure out how to reproduce this ...

Reproduce it? I'm just trying hard NOT to reproduce it ... Not sure what you're asking, here?

**Comment by andrewcarver** [comment]
P.S. If you can tell me exactly what section of the "temporary directory" folder-path you'd try deleting, I will (VERY) gladly try it. Many thanks!!
`C:\tools\ruby31\lib\ruby\gems\3.1.0\gems\nokogiri-1.8.5\ext\nokogiri\tmp\x86_64-w64-mingw32\ports\libiconv\1.15`

**Comment by flavorjones** [comment]
@andrewcarver I'm sorry that you're having this problem, but we've run Windows CI on every version of Nokogiri going back to 2015 and I've never seen this happen. When I ask for help reproducing it, I mean reproducing it in CI or in my Windows development VM.

I'm not a frequent windows user, so I unfortunately can't tell you how to figure out what process is reading that configure.log file and preventing mini_portile from cleaning it up.

If you are deleting the tmp directory before attempting to install the gem; and then during gem installation you get this error message, and there isn't _another_ `gem install` process running simultaneously, then you may want to look at whether you have antivirus or something that is opening and scanning files and preventing mini_portile from cleaning up.

It's entirely possible that something that is under Nokogiri's or mini_portile's control could be changed; but you've established that you're unable to upgrade Nokogiri or mini_portile, even if a patch could be created (which I'm not willing to spend the time to do, given the age of these versions).

If you urgently need a workaround, I'd suggest monkeypatching mini_portile to avoid deleting this file. If you have more time and are willing to help write a test for mini_portile that reproduces this issue, then I will happily fix it in the current minor release of mini_portile. But I don't think this issue is actionable from the point-of-view of Nokogiri, and so I'm going to close it.

Please feel free to comment or ask questions and I'll do my best to respond to them here.

**Comment by flavorjones** [comment]
>  If you can tell me exactly what section of the "temporary directory" folder-path you'd try deleting

`C:\tools\ruby31\lib\ruby\gems\3.1.0\gems\nokogiri-1.8.5\ext\nokogiri\tmp`

**Comment by andrewcarver** [comment]
Ah ... which would explain why I didn't have this problem on my previous Windows 10 machine, still running Ruby 2.6.x ... Thanks!!

**Comment by andrewcarver** [comment]
YEP!! It works with Ruby [2.5.9.1](https://community.chocolatey.org/packages/ruby/2.5.9.1). It even appears, from an old error-message I'd noted (but then, sadly, overlooked!), that version 1.8.5 doesn't like any Ruby older than 2.5.x:

````
ERROR:  Error installing asciidoctor-bibliography:
        The last version of nokogiri (~> 1.8.1) to support your Ruby & RubyGems was 1.8.5. Try installing it with `gem install nokogiri -v 1.8.5` and then running the current command again
        nokogiri requires Ruby version >= 2.2, < 2.6. The current ruby version is 2.6.3.62.
````
