### ISSUE TITLE
[install] unable to install Nokogiri 1.13.6 on OpenBSD 7.1 amd64 - (testing purpose for Rails)

### ISSUE THREAD

**Issue by wesley974** [sparklemotion/nokogiri#2576]
Hi,

**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [x] Yes!

**What is the complete output of `gem install` 

```
Fetching nokogiri-1.13.6.gem
Fetching mini_portile2-2.8.0.gem
Successfully installed mini_portile2-2.8.0
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/3.0/gems/nokogiri-1.13.6/ext/nokogiri
/usr/local/bin/ruby30 -I /usr/local/lib/ruby/3.0 -r ./siteconf20220613-3139-5rscu1.rb extconf.rb
checking for whether -I/usr/local/include is accepted as CPPFLAGS... yes
checking for whether -std=c99 is accepted as CFLAGS... yes
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS... yes
checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
Using mini_portile version 2.8.0
checking for iconv... yes
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxml2-2.9.14.
Configuration options: --host\=x86_64-unknown-openbsd7.1 --enable-static --disable-shared --libdir\=/usr/local/lib/ruby/gems/3.0/gems/nokogiri-1.13.6/ports/x86_64-openbsd/libxml2/2.9.14/lib --with-iconv\=yes --disable-dependency-tracking --without-python --without-readline --with-c14n --with-debug --with-threads --disable-shared --enable-static CFLAGS\=-O2\ -U_FORTIFY_SOURCE\ -g\ -fPIC
The following patches are being applied:
  - 0001-Remove-script-macro-support.patch
  - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0003-libxml2.la-is-in-top_builddir.patch
  - 0004-use-glibc-strlen.patch
  - 0005-avoid-isnan-isinf.patch
  - 0006-update-automake-files-for-arm64.patch
  - 0008-htmlParseComment-handle-abruptly-closed-comments.patch
  - 0009-allow-wildcard-namespaces.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Note, however, that nokogiri cannot guarantee compatibility with every
version of libxml2 that may be provided by OS/package vendors.

[{:url=>
   "https://mirror.csclub.uwaterloo.ca/gnome/sources/libxml2/2.9/libxml2-2.9.14.tar.xz",
  :sha256=>"60d74a257d1ccec0475e749cba2f21559e48139efba6ff28224357c7c798dfee"}]
Extracting libxml2-2.9.14.tar.xz into tmp/x86_64-unknown-openbsd7.1/ports/libxml2/2.9.14... ERROR, review '/usr/local/lib/ruby/gems/3.0/gems/nokogiri-1.13.6/ext/nokogiri/tmp/x86_64-unknown-openbsd7.1/ports/libxml2/2.9.14/extract.log' to see what happened. Last lines are:
========================================================================
tar: unknown option J
usage: tar {crtux}[014578befHhjLmNOoPpqsvwXZz]
           [blocking-factor | archive | replstr] [-C directory] [-I file]
           [file ...]
       tar {-crtux} [-014578eHhjLmNOoPpqvwXZz] [-b blocking-factor]
           [-C directory] [-f archive] [-I file] [-s replstr] [file ...]
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)30
        --help
        --clean
        --enable-system-libraries
        --disable-system-libraries
        --use-system-libraries
        --prevent-strip
        --enable-system-libraries
        --disable-system-libraries
        --use-system-libraries
        --enable-system-libraries
        --disable-system-libraries
        --use-system-libraries
        --enable-static
        --disable-static
        --enable-cross-build
        --disable-cross-build
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --with-xml2-source-dir
/usr/local/lib/ruby/gems/3.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:460:in `block in execute': Failed to complete extract task (RuntimeError)
        from /usr/local/lib/ruby/gems/3.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:426:in `chdir'
        from /usr/local/lib/ruby/gems/3.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:426:in `execute'
        from /usr/local/lib/ruby/gems/3.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:413:in `extract_file'
        from /usr/local/lib/ruby/gems/3.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:90:in `block in extract'
        from /usr/local/lib/ruby/gems/3.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:88:in `each'
        from /usr/local/lib/ruby/gems/3.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:88:in `extract'
        from /usr/local/lib/ruby/gems/3.0/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:183:in `cook'
        from extconf.rb:529:in `block (2 levels) in process_recipe'
        from extconf.rb:309:in `chdir'
        from extconf.rb:309:in `chdir_for_build'
        from extconf.rb:529:in `block in process_recipe'
        from <internal:kernel>:90:in `tap'
        from extconf.rb:428:in `process_recipe'
        from extconf.rb:774:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/3.0/extensions/x86_64-openbsd/3.0/nokogiri-1.13.6/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/3.0/gems/nokogiri-1.13.6 for inspection.
Results logged to /usr/local/lib/ruby/gems/3.0/extensions/x86_64-openbsd/3.0/nokogiri-1.13.6/gem_make.out
```

**If installation failed during compilation, what are the complete contents of the `mkmf.log` file generated during the failed installation?**

```
block in append_cppflags: checking for whether -I/usr/local/include is accepted as CPPFLAGS... -------------------- yes

"cc -fdeclspec -o conftest -I/usr/local/include/ruby-3.0/x86_64-openbsd -I/usr/local/include/ruby-3.0/ruby/backward -I/usr/local/include/ruby-3.0 -I. -DOPENSSL_NO_STATIC_ENGINE -I/usr/local/include   -O2 -pipe -g -fPIC conftest.c  -L. -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L. -L/usr/local/lib -fstack-protector-strong -Wl,-E -Wl,--no-as-needed     -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lruby30  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

"cc -E -I/usr/local/include/ruby-3.0/x86_64-openbsd -I/usr/local/include/ruby-3.0/ruby/backward -I/usr/local/include/ruby-3.0 -I. -DOPENSSL_NO_STATIC_ENGINE -I/usr/local/include   -O2 -pipe -g -fPIC -I/usr/local/include conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

--------------------

block in append_cflags: checking for whether -std=c99 is accepted as CFLAGS... -------------------- yes

"cc -fdeclspec -I/usr/local/include/ruby-3.0/x86_64-openbsd -I/usr/local/include/ruby-3.0/ruby/backward -I/usr/local/include/ruby-3.0 -I. -DOPENSSL_NO_STATIC_ENGINE -I/usr/local/include   -I/usr/local/include -O2 -pipe -g -fPIC  -std=c99 -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

--------------------

block in append_cflags: checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... -------------------- yes

"cc -fdeclspec -I/usr/local/include/ruby-3.0/x86_64-openbsd -I/usr/local/include/ruby-3.0/ruby/backward -I/usr/local/include/ruby-3.0 -I. -DOPENSSL_NO_STATIC_ENGINE -I/usr/local/include   -I/usr/local/include -O2 -pipe -g -fPIC -std=c99  -Wno-declaration-after-statement -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

--------------------

block in append_cflags: checking for whether -g is accepted as CFLAGS... -------------------- yes

"cc -fdeclspec -I/usr/local/include/ruby-3.0/x86_64-openbsd -I/usr/local/include/ruby-3.0/ruby/backward -I/usr/local/include/ruby-3.0 -I. -DOPENSSL_NO_STATIC_ENGINE -I/usr/local/include   -I/usr/local/include -O2 -pipe -g -fPIC -std=c99 -Wno-declaration-after-statement  -g -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

--------------------

block in append_cflags: checking for whether -Winline is accepted as CFLAGS... -------------------- yes

"cc -fdeclspec -I/usr/local/include/ruby-3.0/x86_64-openbsd -I/usr/local/include/ruby-3.0/ruby/backward -I/usr/local/include/ruby-3.0 -I. -DOPENSSL_NO_STATIC_ENGINE -I/usr/local/include   -I/usr/local/include -O2 -pipe -g -fPIC -std=c99 -Wno-declaration-after-statement -g  -Winline -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

--------------------

block in append_cflags: checking for whether -Wmissing-noreturn is accepted as CFLAGS... -------------------- yes

"cc -fdeclspec -I/usr/local/include/ruby-3.0/x86_64-openbsd -I/usr/local/include/ruby-3.0/ruby/backward -I/usr/local/include/ruby-3.0 -I. -DOPENSSL_NO_STATIC_ENGINE -I/usr/local/include   -I/usr/local/include -O2 -pipe -g -fPIC -std=c99 -Wno-declaration-after-statement -g -Winline  -Wmissing-noreturn -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

--------------------

try_link_iconv: checking for iconv... -------------------- yes

"cc -fdeclspec -o conftest -I/usr/local/include/ruby-3.0/x86_64-openbsd -I/usr/local/include/ruby-3.0/ruby/backward -I/usr/local/include/ruby-3.0 -I. -DOPENSSL_NO_STATIC_ENGINE -I/usr/local/include   -I/usr/local/include -O2 -pipe -g -fPIC -std=c99 -Wno-declaration-after-statement -g -Winline -Wmissing-noreturn conftest.c  -L. -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L. -L/usr/local/lib -fstack-protector-strong -Wl,-E -Wl,--no-as-needed     -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lruby30  -lm   -lc"
ld: error: undefined symbol: libiconv_open
>>> referenced by conftest.c:7
>>>               /tmp/conftest-f1f3c4.o:(main)

ld: error: undefined symbol: libiconv
>>> referenced by conftest.c:8
>>>               /tmp/conftest-f1f3c4.o:(main)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: #include <stdlib.h>
 4: #include <iconv.h>
 5: int main(void)
 6: {
 7:     iconv_t cd = iconv_open("", "");
 8:     iconv(cd, NULL, NULL, NULL, NULL);
 9:     return EXIT_SUCCESS;
10: }
/* end */

"cc -fdeclspec -o conftest -I/usr/local/include/ruby-3.0/x86_64-openbsd -I/usr/local/include/ruby-3.0/ruby/backward -I/usr/local/include/ruby-3.0 -I. -DOPENSSL_NO_STATIC_ENGINE -I/usr/local/include   -I/usr/local/include -O2 -pipe -g -fPIC -std=c99 -Wno-declaration-after-statement -g -Winline -Wmissing-noreturn conftest.c  -L. -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L. -L/usr/local/lib -fstack-protector-strong -Wl,-E -Wl,--no-as-needed     -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lruby30 -liconv -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: #include <stdlib.h>
 4: #include <iconv.h>
 5: int main(void)
 6: {
 7:     iconv_t cd = iconv_open("", "");
 8:     iconv(cd, NULL, NULL, NULL, NULL);
 9:     return EXIT_SUCCESS;
10: }
/* end */

--------------------
```

**Tell us about your system!**

What is the output from `ruby -v`? ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-openbsd]

What is the output from `gem -v`? 3.2.33

What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.33
  - RUBY VERSION: 3.0.4 (2022-04-12 patchlevel 208) [x86_64-openbsd]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/3.0
  - USER INSTALLATION DIRECTORY: /root/.local/share/gem/ruby/3.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby30
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /root/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-openbsd
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/3.0
     - /root/.local/share/gem/ruby/3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /sbin
     - /usr/sbin
     - /bin
     - /usr/bin
     - /usr/X11R6/bin
     - /usr/local/sbin
     - /usr/local/bin
```

If you're using Bundler:
- what is the output from `bundle version`? just for info : Bundler version 2.2.33 (2022-06-13 commit unknown)

I'm using OpenBSD :
- the output of `clang -v`

```
OpenBSD clang version 13.0.0
Target: amd64-unknown-openbsd7.1
Thread model: posix
InstalledDir: /usr/bin
```

- `uname -a` :
OpenBSD 7.1 GENERIC#3 amd64

Merci!

**Comment by flavorjones** [comment]
@wesley974 Hi, sorry you're having this problem. See https://gitlab.gnome.org/Infrastructure/Infrastructure/-/issues/768 for more context, but the underlying source package is an `.xz` file and OpenBSD doesn't ship xz utilities by default.

The current installation docs try to address this, please let me know whether the docs are correct or not in these sections?

- https://nokogiri.org/tutorials/installing_nokogiri.html#openbsd-7
- https://nokogiri.org/tutorials/installing_nokogiri.html#tar-child-xz-cannot-exec-no-such-file-or-directory

**Comment by flavorjones** [comment]
Also: If you'd like to help make Nokogiri work better on OpenBSD, we could always use an extra pair of hands. If the installation experience doesn't meet your expectations we are open to changing it, but we really need someone who's an OpenBSD user to drive that work.

**Comment by wesley974** [comment]
Many thanks @flavorjones

**Comment by flavorjones** [comment]
I updated the installation docs with the exact error message you saw on openbsd (to hopefully make it more findable), see https://github.com/sparklemotion/nokogiri.org/commit/a2271c177032a23589a26489e2a84e30e4c2347f

**Comment by flavorjones** [comment]
Retitled section is https://nokogiri.org/tutorials/installing_nokogiri.html#tar-and-xz-files
