### ISSUE TITLE
Installing the generic version of nokogiri on Windows + Ruby 3.2 is flaky in RubyGems CI

### ISSUE THREAD

**Issue by deivid-rodriguez** [sparklemotion/nokogiri#2758]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [x] Yes!

**What is the complete output of `gem install` or `bundle install`?**

I'm copying logs from [RubyGems CI](https://github.com/rubygems/rubygems/actions/runs/3901447399/jobs/6663310026) below:

```
##[group]Run gem install rails && rails new foo 
gem install rails && rails new foo 
shell: C:\msys64\usr\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
env:
  TMPDIR: D:\a\_temp
  HOME: C:\Users\runneradmin
  MSYS2_PATH_TYPE: inherit
  MAKE: make.exe
  Path: C:\Program Files\MongoDB\Server\5.0\bin;C:\aliyun-cli;C:\vcpkg;C:\Program Files (x86)\NSIS\;C:\tools\zstd;C:\Program Files\Mercurial\;C:\hostedtoolcache\windows\stack\2.9.3\x64;C:\cabal\bin;C:\\ghcup\bin;C:\tools\ghc-9.4.4\bin;C:\Program Files\dotnet;C:\mysql\bin;C:\Program Files\R\R-4.2.2\bin\x64;C:\SeleniumWebDrivers\GeckoDriver;C:\Program Files (x86)\sbt\bin;C:\Program Files (x86)\GitHub CLI;C:\Program Files\Git\bin;C:\Program Files (x86)\pipx_bin;C:\npm\prefix;C:\hostedtoolcache\windows\go\1.17.13\x64\bin;C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts;C:\hostedtoolcache\windows\Python\3.9.13\x64;C:\tools\kotlinc\bin;C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.352-8\x64\bin;C:\Program Files\ImageMagick-7.1.0-Q16-HDRI;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\kind;C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\ProgramData\Chocolatey\bin;C:\Program Files\PowerShell\7\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\OpenSSL\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.7\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\GitHub CLI\;c:\tools\php;C:\Program Files (x86)\sbt\bin;C:\SeleniumWebDrivers\ChromeDriver\;C:\SeleniumWebDrivers\EdgeDriver\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Amazon\SessionManagerPlugin\bin\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\LLVM\bin;C:\Users\runneradmin\.dotnet\tools;C:\Users\runneradmin\.cargo\bin;C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps
  ACLOCAL_PATH: /ucrt64/share/aclocal:/usr/share/aclocal
  LANG: en_US.UTF-8
  MANPATH: /ucrt64/share/man
  MINGW_CHOST: x86_64-w64-mingw32
  MINGW_PACKAGE_PREFIX: mingw-w64-ucrt-x86_64
  MINGW_PREFIX: /ucrt64
  MSYSTEM: UCRT64
  MSYSTEM_CARCH: x86_64
  MSYSTEM_CHOST: x86_64-w64-mingw32
  MSYSTEM_PREFIX: /ucrt64
  PKG_CONFIG_PATH: /ucrt64/lib/pkgconfig:/ucrt64/share/pkgconfig
  PROMPT: $P$G
  RI_DEVKIT: c:\msys64
##[endgroup]
ERROR:  Error installing rails:
	ERROR: Failed to build gem native extension.

    current directory: C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.13.10/ext/nokogiri
C:/hostedtoolcache/windows/Ruby/3.2.0/x64/bin/ruby.exe -I C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/site_ruby/3.2.0 extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... yes
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS... yes
checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
checking for whether  "-Idummypath" is accepted as CPPFLAGS... yes
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
Using mini_portile version 2.8.1
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of zlib-1.2.13.
Configuration options: --host\=x86_64-w64-mingw32 --enable-static --disable-shared --libdir\=C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.13.10/ports/x64-mingw-ucrt/zlib/1.2.13/lib --disable-shared --enable-static CFLAGS\=-fPIC

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

[{:url=>"https://zlib.net/fossils/zlib-1.2.13.tar.gz",
  :sha256=>"b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30"}]

Downloading zlib-1.2.13.tar.gz 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=C:/hostedtoolcache/windows/Ruby/3.2.0/x64/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--prevent-strip
	--enable-system-libraries
	--disable-system-libraries
	--use-system-libraries
	--enable-system-libraries
	--disable-system-libraries
	--use-system-libraries
	--enable-static
	--disable-static
	--enable-cross-build
	--disable-cross-build
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:337:in `verify_file': Downloaded file 'C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.13.10/ports/archives/zlib-1.2.13.tar.gz' has wrong hash: expected: b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30 is: 95e56e77891bfe6087a7a19494c8c3d64d0ab782e175d6237dd24d69840ed390 (RuntimeError)
	from C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:83:in `block in download'
	from C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:81:in `each'
	from C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:81:in `download'
	from C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:182:in `cook'
	from extconf.rb:529:in `block (2 levels) in process_recipe'
	from extconf.rb:309:in `chdir'
	from extconf.rb:309:in `chdir_for_build'
	from extconf.rb:529:in `block in process_recipe'
	from <internal:kernel>:90:in `tap'
	from extconf.rb:428:in `process_recipe'
	from extconf.rb:675:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/extensions/x64-mingw-ucrt/3.2.0/nokogiri-1.13.10/mkmf.log

Successfully installed zeitwerk-2.6.6
Successfully installed thor-1.2.1
extconf failed, exit code 1
Successfully installed method_source-1.0.0

Successfully installed concurrent-ruby-1.1.10
Gem files will remain installed in C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/nokogiri-1.13.10 for inspection.
Successfully installed tzinfo-2.0.5
Results logged to C:/hostedtoolcache/windows/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/extensions/x64-mingw-ucrt/3.2.0/nokogiri-1.13.10/gem_make.out
Successfully installed i18n-1.12.0
Successfully installed activesupport-7.0.4
Successfully installed mini_portile2-2.8.1
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
```

**If installation failed during compilation, what are the complete contents of the `mkmf.log` file generated during the failed installation?**

Good question, I cannot access this file but I could probably add something to the workflow to get it automatically printed when this issue happens! Let me know :)

**Tell us about your system!**

This happens on the installation of Ruby provided by default by `ruby/setup-ruby` GitHub Action on Windows + Ruby 3.2.

This is the workflow that fails: it installs RubyGems, and the uses the installed version to install rails through `gem install rails` (which installs nokogiri transitively): https://github.com/rubygems/rubygems/blob/9abd8acdb11378d7c4a97d6e252360cb60e88ec6/.github/workflows/install-rubygems.yml#L93-L127.

To be honest, I doubt this is a problem in nokogiri itself, it seems like some corrupted download issue? I just figured this repo would be a good place to properly get this triaged and redirected to the right place.

Thanks so much!

**Comment by flavorjones** [comment]
@deivid-rodriguez Yes, the download from zlib is flaky and Nokogiri's CI itself caches this file to avoid this problem. You're only hitting it because we haven't shipped precompiled support yet for Ruby 3.2, and so you're compiling from source (which requires downloading some additional tarballs including zlib).

I'm planning to ship a version of Nokogiri with native support for 3.2 today, so this problem _should_ go away after that.

**Comment by deivid-rodriguez** [comment]
Awesome, I wanted to report the issue just in case you were not aware of the problem, since it's something that only appeared for us with Ruby 3.2. But I do realize now that it's unrelated to Ruby 3.2 at all, but to having to resort to using the ruby platform version in that particular case.

Thanks for clarifying and sorry for the noise :)

**Comment by flavorjones** [comment]
All good! I appreciate the test coverage :heart:
