### ISSUE TITLE
[install] Fails in psych.rb:455:in parse_stream: undefined method parse for Psych::Parser NoMethodError

### ISSUE THREAD

**Issue by mildred** [sparklemotion/nokogiri#2828]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [x] Yes!

Precompiled gem installation works but building fails outside of build in ruby code.

**What is the complete output of `gem install` or `bundle install`?**

```
Installing nokogiri 1.14.2 (was 1.13.10) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/nokogiri-1.14.2/ext/nokogiri
/usr/local/rvm/rubies/ruby-3.1.2/bin/ruby -I /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0 -r ./siteconf20230309-551423-gxlyix.rb extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... yes
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... yes
checking for whether -O2 is accepted as CFLAGS... yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS... yes
checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
checking for whether -Wconversion -Wno-sign-conversion is accepted as CFLAGS... yes
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/rvm/rubies/ruby-3.1.2/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--prevent-strip
	--enable-system-libraries
	--disable-system-libraries
	--use-system-libraries
	--enable-system-libraries
	--disable-system-libraries
	--use-system-libraries
	--enable-static
	--disable-static
	--enable-cross-build
	--disable-cross-build
	--enable-cross-build
	--disable-cross-build
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/psych.rb:455:in `parse_stream': undefined method `parse' for #<Psych::Parser:0x00007f90689f7ba8
@handler=#<Psych::Handlers::DocumentStream:0x00007f90689f7cc0 @stack=[], @last=nil, @root=nil, @start_line=nil, @start_column=nil, @end_line=nil, @end_column=nil,
@block=#<Proc:0x00007f90689f7bf8 /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/psych.rb:399>>, @external_encoding=0> (NoMethodError)

      parser.parse yaml, filename
            ^^^^^^
	from /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/psych.rb:399:in `parse'
	from /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/psych.rb:324:in `safe_load'
	from /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/psych.rb:370:in `load'
	from /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/psych.rb:671:in `block in load_file'
	from /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/psych.rb:670:in `open'
	from /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/psych.rb:670:in `load_file'
	from extconf.rb:726:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/rvm/gems/ruby-3.1.2@lcas/extensions/x86_64-linux/3.1.0/nokogiri-1.14.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/nokogiri-1.14.2 for inspection.
Results logged to /usr/local/rvm/gems/ruby-3.1.2@lcas/extensions/x86_64-linux/3.1.0/nokogiri-1.14.2/gem_make.out

  /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
  /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
  /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/source/rubygems.rb:204:in `install'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/worker.rb:54:in `loop'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/rvm/gems/ruby-3.1.2@lcas/gems/bundler-2.3.4/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing nokogiri (1.14.2), and Bundler cannot continue.

In Gemfile:
  rails was resolved to 7.0.4.2, which depends on
    actioncable was resolved to 7.0.4.2, which depends on
      actionpack was resolved to 7.0.4.2, which depends on
        actionview was resolved to 7.0.4.2, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            nokogiri
```

**If installation completed but is broken, what is the complete output from `nokogiri -v`?**

N/A

**If installation failed during compilation, what are the complete contents of the `mkmf.log` file generated during the failed installation?**

N/A

**Tell us about your system!**

What is the output from `ruby -v`?

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

What is the output from `gem -v`?

3.3.7

What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.7
  - RUBY VERSION: 3.1.2 (2022-04-12 patchlevel 20) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-3.1.2@lcas
  - USER INSTALLATION DIRECTORY: /home/mildred/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-3.1.2/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-3.1.2@lcas/bin
  - SPEC CACHE DIRECTORY: /home/mildred/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/rvm/rubies/ruby-3.1.2/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /usr/local/rvm/gems/ruby-3.1.2@lcas
     - /usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/rvm/gems/ruby-3.1.2@lcas/bin
     - /usr/local/rvm/gems/ruby-3.1.2@global/bin
     - /usr/local/rvm/rubies/ruby-3.1.2/bin
     - /usr/local/rvm/bin
     - /home/mildred/.local/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/local/games
     - /usr/games
     - /home/mildred/.gem/ruby/2.3.0/bin
     - /home/mildred/.cache/go/bin
     - /home/mildred/Projects/go/bin
     - /home/mildred/Projets/go/bin
     - /home/mildred/.nimble/bin
     - /home/mildred/.gem/ruby/2.2.0/bin
     - /home/mildred/.gem/ruby/2.3.0/bin
     - /home/mildred/.cache/go/bin
     - /home/mildred/Projects/go/bin
     - /home/mildred/Projets/go/bin
     - /home/mildred/.nimble/bin
     - /home/mildred/.gem/ruby/2.2.0/bin
     - /home/mildred/.cargo/bin
```

If you're using Bundler:
- what is the output from `bundle version`? Bundler version 2.3.4 (2021-12-29 commit 2296a0d6cc)
- what is the output from `bundle config`? (Take care to redact any credentials)

```
Settings are listed in order of priority. The top value will be used.
```

If you're on MacOS, please note: N/A

If Linux or a BSD variant, please note: N/A

If Windows, please note: N/A

**Comment by mildred** [comment]
Updating bundler to latest version (`Bundler version 2.4.8 (2023-03-08 commit a67b2657a0)`) does not help

**Comment by flavorjones** [comment]
Hi, sorry you're having trouble, I'll try to help.

This looks like your installation of the `psych` gem is possibly broken. The things I'd try, roughly in this order:

- use the precompiled native version of the gem, which avoids having to compile anything at installation
- re-install `psych` or install a newer version
- re-install ruby (which will re-install the system `psych` gem)

I'm also curious why you're not using the precompiled native gem for x86_64-linux. Have you set `force_ruby_platform` to true in your Gemfile? What's the command you're running (`gem` or `bundle install`)?

**Comment by mildred** [comment]
I was using `bundle update` and by default bundle is not using the precompiled version. I successfully installed the precompiled version of nokogiri though `gem install` but this error seemed suspect to me and I wanted to report it, if only for the sole purpose of having it indexed by Google and gather information about this issue.

Running IRB, I could use `psych` without any problem:

```
$ irb
3.1.2 :001 > require 'psych'
 => true 
3.1.2 :002 > Psych.load_file 'foo.yaml'
 => {"foo"=>{"bar"=>1}} 
```

So at a glance it does not look like psych is at fault here. Perhaps there is some bad interaction with some other gems.

Also I did not upgrade to ruby 3.2 and I kept with 3.1. On the changelog I see something about ruby no longer vendoring libyaml for psych. Perhaps this is related somehow...

**Comment by mildred** [comment]
With a new ruby 3.2.1, `bundle install` seems to install nokogiri without any issue.

**Comment by flavorjones** [comment]
> by default bundle is not using the precompiled version

You may want to investigate why this is happening -- the precompiled native gems will save you time and effort.

**Comment by willnet** [comment]
I was struggling with the same issue, but it was resolved after running `gem update --system`.

- nokogiri 1.18.1
- Ruby 3.1.6
