### ISSUE TITLE
[bug] illegal instruction on arm-linux-gnueabihf

### ISSUE THREAD

**Issue by Vokda** [sparklemotion/nokogiri#3145]
I'm trying to run a ruby on rails application which results in crash. The error points to nokogiri.so. 

The error message I get is
```/home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri/3.1/nokogiri.so: [BUG] Illegal instruction at 0xb37a7a0c
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm-linux-gnueabihf]```
```

I'm running ```rails server```.
Running the example ruby script in the comment, results in the same error. 
This is run on a Raspberry Pi B+ with the OS Raspbian. 

nokogiri -v output:
``` $ nokogiri -v
/home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri/3.1/nokogiri.so: [BUG] Illegal instruction at 0xb3f87a0c
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm-linux-gnueabihf]

-- Control frame information -----------------------------------------------
c:0011 p:-6491550 s:0063 e:000062 TOP    [FINISH]
c:0010 p:---- s:0060 e:000059 CFUNC  :require_relative
c:0009 p:0037 s:0055 e:000054 TOP    /home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri/extension.rb:7 [FINISH]
c:0008 p:---- s:0051 e:000050 CFUNC  :require_relative
c:0007 p:0033 s:0046 e:000045 TOP    /home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri.rb:8 [FINISH]
c:0006 p:---- s:0043 e:000042 CFUNC  :require
c:0005 p:0194 s:0038 e:000037 METHOD <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85
c:0004 p:0029 s:0021 e:000020 TOP    /home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/bin/nokogiri:8 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC  :load
c:0002 p:0124 s:0008 E:001f58 EVAL   /usr/bin/nokogiri:25 [FINISH]
c:0001 p:0000 s:0003 E:001f78 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/bin/nokogiri:25:in `<main>'
/usr/bin/nokogiri:25:in `load'
/home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/bin/nokogiri:8:in `<top (required)>'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri.rb:8:in `<top (required)>'
/home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri.rb:8:in `require_relative'
/home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri/extension.rb:7:in `<top (required)>'
/home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri/extension.rb:7:in `require_relative'

-- Machine register context ------------------------------------------------
  r0: 0xb40cedf4  r1: 0x00000000  r2: 0xb40cd000  r3: 0x00000000  r4: 0xb40c79bc
  r5: 0x00000003  r6: 0xbef4a554  r7: 0x015eaff0  r8: 0xb40c79bc  r9: 0x00000000
 r10: 0x00000000  sp: 0xbef48dc0 fau: 0x00000000

-- Other runtime information -----------------------------------------------

* Loaded script: /usr/bin/nokogiri

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 fiber.so
    3 rational.so
    4 complex.so
    5 ruby2_keywords.rb
    6 /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/enc/encdb.so
    7 /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/enc/trans/transdb.so
    8 /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/rbconfig.rb
    9 /usr/lib/ruby/vendor_ruby/rubygems/compatibility.rb
   10 /usr/lib/ruby/vendor_ruby/rubygems/defaults.rb
   11 /usr/lib/ruby/vendor_ruby/rubygems/deprecate.rb
   12 /usr/lib/ruby/vendor_ruby/rubygems/errors.rb
   13 /usr/lib/ruby/vendor_ruby/rubygems/unknown_command_spell_checker.rb
   14 /usr/lib/ruby/vendor_ruby/rubygems/exceptions.rb
   15 /usr/lib/ruby/vendor_ruby/rubygems/basic_specification.rb
   16 /usr/lib/ruby/vendor_ruby/rubygems/stub_specification.rb
   17 /usr/lib/ruby/vendor_ruby/rubygems/platform.rb
   18 /usr/lib/ruby/vendor_ruby/rubygems/version.rb
   19 /usr/lib/ruby/vendor_ruby/rubygems/requirement.rb
   20 /usr/lib/ruby/vendor_ruby/rubygems/util/list.rb
   21 /usr/lib/ruby/vendor_ruby/rubygems/specification.rb
   22 /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb
   23 /usr/lib/ruby/vendor_ruby/rubygems/util.rb
   24 /usr/lib/ruby/vendor_ruby/rubygems/dependency.rb
   25 /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_gem.rb
   26 /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/monitor.so
   27 /usr/lib/ruby/3.1.0/monitor.rb
   28 /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb
   29 /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_warn.rb
   30 /usr/lib/ruby/vendor_ruby/rubygems.rb
   31 /usr/lib/ruby/vendor_ruby/rubygems/path_support.rb
   32 /home/daniel/.gem/gems/error_highlight-0.6.0/lib/error_highlight/version.rb
   33 /home/daniel/.gem/gems/error_highlight-0.6.0/lib/error_highlight/base.rb
   34 /home/daniel/.gem/gems/error_highlight-0.6.0/lib/error_highlight/formatter.rb
   35 /home/daniel/.gem/gems/error_highlight-0.6.0/lib/error_highlight/core_ext.rb
   36 /home/daniel/.gem/gems/error_highlight-0.6.0/lib/error_highlight.rb
   37 /usr/lib/ruby/3.1.0/did_you_mean/version.rb
   38 /usr/lib/ruby/3.1.0/did_you_mean/core_ext/name_error.rb
   39 /usr/lib/ruby/3.1.0/did_you_mean/levenshtein.rb
   40 /usr/lib/ruby/3.1.0/did_you_mean/jaro_winkler.rb
   41 /usr/lib/ruby/3.1.0/did_you_mean/spell_checker.rb
   42 /usr/lib/ruby/3.1.0/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   43 /usr/lib/ruby/3.1.0/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   44 /usr/lib/ruby/3.1.0/did_you_mean/spell_checkers/name_error_checkers.rb
   45 /usr/lib/ruby/3.1.0/did_you_mean/spell_checkers/method_name_checker.rb
   46 /usr/lib/ruby/3.1.0/did_you_mean/spell_checkers/key_error_checker.rb
   47 /usr/lib/ruby/3.1.0/did_you_mean/spell_checkers/null_checker.rb
   48 /usr/lib/ruby/3.1.0/did_you_mean/tree_spell_checker.rb
   49 /usr/lib/ruby/3.1.0/did_you_mean/spell_checkers/require_path_checker.rb
   50 /usr/lib/ruby/3.1.0/did_you_mean/spell_checkers/pattern_key_name_checker.rb
   51 /usr/lib/ruby/3.1.0/did_you_mean/formatter.rb
   52 /usr/lib/ruby/3.1.0/did_you_mean.rb
   53 /usr/lib/ruby/vendor_ruby/rubygems/tsort/lib/tsort.rb
   54 /usr/lib/ruby/vendor_ruby/rubygems/tsort.rb
   55 /usr/lib/ruby/vendor_ruby/rubygems/request_set/gem_dependency_api.rb
   56 /usr/lib/ruby/vendor_ruby/rubygems/request_set/lockfile/parser.rb
   57 /usr/lib/ruby/vendor_ruby/rubygems/request_set/lockfile/tokenizer.rb
   58 /usr/lib/ruby/vendor_ruby/rubygems/request_set/lockfile.rb
   59 /usr/lib/ruby/vendor_ruby/rubygems/request_set.rb
   60 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/gem_metadata.rb
   61 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb
   62 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/errors.rb
   63 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/action.rb
   64 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/add_edge_no_circular.rb
   65 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/add_vertex.rb
   66 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/delete_edge.rb
   67 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/detach_vertex_named.rb
   68 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/set_payload.rb
   69 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/tag.rb
   70 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/log.rb
   71 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/dependency_graph/vertex.rb
   72 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/dependency_graph.rb
   73 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/state.rb
   74 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/modules/specification_provider.rb
   75 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/delegates/resolution_state.rb
   76 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/resolution.rb
   77 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/resolver.rb
   78 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/modules/ui.rb
   79 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo.rb
   80 /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo.rb
   81 /usr/lib/ruby/vendor_ruby/rubygems/resolver/activation_request.rb
   82 /usr/lib/ruby/vendor_ruby/rubygems/resolver/conflict.rb
   83 /usr/lib/ruby/vendor_ruby/rubygems/resolver/dependency_request.rb
   84 /usr/lib/ruby/vendor_ruby/rubygems/resolver/requirement_list.rb
   85 /usr/lib/ruby/vendor_ruby/rubygems/resolver/stats.rb
   86 /usr/lib/ruby/vendor_ruby/rubygems/resolver/set.rb
   87 /usr/lib/ruby/vendor_ruby/rubygems/resolver/api_set.rb
   88 /usr/lib/ruby/vendor_ruby/rubygems/resolver/composed_set.rb
   89 /usr/lib/ruby/vendor_ruby/rubygems/resolver/best_set.rb
   90 /usr/lib/ruby/vendor_ruby/rubygems/resolver/current_set.rb
   91 /usr/lib/ruby/vendor_ruby/rubygems/resolver/git_set.rb
   92 /usr/lib/ruby/vendor_ruby/rubygems/resolver/index_set.rb
   93 /usr/lib/ruby/vendor_ruby/rubygems/resolver/installer_set.rb
   94 /usr/lib/ruby/vendor_ruby/rubygems/resolver/lock_set.rb
   95 /usr/lib/ruby/vendor_ruby/rubygems/resolver/vendor_set.rb
   96 /usr/lib/ruby/vendor_ruby/rubygems/resolver/source_set.rb
   97 /usr/lib/ruby/vendor_ruby/rubygems/resolver/specification.rb
   98 /usr/lib/ruby/vendor_ruby/rubygems/resolver/spec_specification.rb
   99 /usr/lib/ruby/vendor_ruby/rubygems/resolver/api_specification.rb
  100 /usr/lib/ruby/vendor_ruby/rubygems/resolver/git_specification.rb
  101 /usr/lib/ruby/vendor_ruby/rubygems/resolver/index_specification.rb
  102 /usr/lib/ruby/vendor_ruby/rubygems/resolver/installed_specification.rb
  103 /usr/lib/ruby/vendor_ruby/rubygems/resolver/local_specification.rb
  104 /usr/lib/ruby/vendor_ruby/rubygems/resolver/lock_specification.rb
  105 /usr/lib/ruby/vendor_ruby/rubygems/resolver/vendor_specification.rb
  106 /usr/lib/ruby/vendor_ruby/rubygems/resolver.rb
  107 /usr/lib/ruby/vendor_ruby/rubygems/text.rb
  108 /usr/lib/ruby/vendor_ruby/rubygems/source/git.rb
  109 /usr/lib/ruby/vendor_ruby/rubygems/source/installed.rb
  110 /usr/lib/ruby/vendor_ruby/rubygems/source/specific_file.rb
  111 /usr/lib/ruby/vendor_ruby/rubygems/source/local.rb
  112 /usr/lib/ruby/vendor_ruby/rubygems/source/lock.rb
  113 /usr/lib/ruby/vendor_ruby/rubygems/source/vendor.rb
  114 /usr/lib/ruby/vendor_ruby/rubygems/source.rb
  115 /usr/lib/ruby/3.1.0/set.rb
  116 /usr/lib/ruby/3.1.0/optparse.rb
  117 /usr/lib/ruby/3.1.0/uri/version.rb
  118 /usr/lib/ruby/3.1.0/uri/rfc2396_parser.rb
  119 /usr/lib/ruby/3.1.0/uri/rfc3986_parser.rb
  120 /usr/lib/ruby/3.1.0/uri/common.rb
  121 /usr/lib/ruby/3.1.0/uri/generic.rb
  122 /usr/lib/ruby/3.1.0/uri/file.rb
  123 /usr/lib/ruby/3.1.0/uri/ftp.rb
  124 /usr/lib/ruby/3.1.0/uri/http.rb
  125 /usr/lib/ruby/3.1.0/uri/https.rb
  126 /usr/lib/ruby/3.1.0/uri/ldap.rb
  127 /usr/lib/ruby/3.1.0/uri/ldaps.rb
  128 /usr/lib/ruby/3.1.0/uri/mailto.rb
  129 /usr/lib/ruby/3.1.0/uri/ws.rb
  130 /usr/lib/ruby/3.1.0/uri.rb
  131 /home/daniel/.gem/gems/stringio-3.1.0/lib/stringio.so
  132 /home/daniel/.gem/gems/date-3.3.4/lib/date_core.so
  133 /home/daniel/.gem/gems/date-3.3.4/lib/date.rb
  134 /usr/lib/ruby/3.1.0/time.rb
  135 /usr/lib/ruby/3.1.0/open-uri.rb

* Process memory map:

00010000-00011000 r-xp 00000000 b3:02 61673      /usr/bin/ruby3.1
00011000-00012000 r--p 00000000 b3:02 61673      /usr/bin/ruby3.1
00012000-00013000 rw-p 00001000 b3:02 61673      /usr/bin/ruby3.1
01562000-01922000 rw-p 00000000 00:00 0          [heap]
b3f60000-b40b7000 r-xp 00000000 b3:02 403851     /home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri/3.1/nokogiri.so
b40b7000-b40c7000 ---p 00157000 b3:02 403851     /home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri/3.1/nokogiri.so
b40c7000-b40cd000 r--p 00157000 b3:02 403851     /home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri/3.1/nokogiri.so
b40cd000-b40cf000 rw-p 0015d000 b3:02 403851     /home/daniel/.gem/gems/nokogiri-1.16.2-arm-linux/lib/nokogiri/3.1/nokogiri.so
b40cf000-b40d1000 rw-p 00000000 00:00 0 
b40d5000-b40df000 r--p 00000000 b3:02 70917      /etc/ld.so.cache
b40df000-b4111000 r-xp 00000000 b3:02 405563     /home/daniel/.gem/gems/date-3.3.4/lib/date_core.so
b4111000-b4112000 r--p 00031000 b3:02 405563     /home/daniel/.gem/gems/date-3.3.4/lib/date_core.so
b4112000-b4113000 rw-p 00032000 b3:02 405563     /home/daniel/.gem/gems/date-3.3.4/lib/date_core.so
b4113000-b411a000 r-xp 00000000 b3:02 407229     /home/daniel/.gem/gems/stringio-3.1.0/lib/stringio.so
b411a000-b411b000 r--p 00006000 b3:02 407229     /home/daniel/.gem/gems/stringio-3.1.0/lib/stringio.so
b411b000-b411c000 rw-p 00007000 b3:02 407229     /home/daniel/.gem/gems/stringio-3.1.0/lib/stringio.so
b411c000-b41d0000 rw-p 00000000 00:00 0 
b41d0000-b41d1000 ---p 00000000 00:00 0 
b41d1000-b4222000 rw-p 00000000 00:00 0 
b4222000-b4223000 ---p 00000000 00:00 0 
b4223000-b4274000 rw-p 00000000 00:00 0 
b4274000-b4275000 ---p 00000000 00:00 0 
b4275000-b42c6000 rw-p 00000000 00:00 0 
b42c6000-b42c7000 ---p 00000000 00:00 0 
b42c7000-b4318000 rw-p 00000000 00:00 0 
b4318000-b4319000 ---p 00000000 00:00 0 
b4319000-b436a000 rw-p 00000000 00:00 0 
b436a000-b436b000 ---p 00000000 00:00 0 
b436b000-b43bc000 rw-p 00000000 00:00 0 
b43bc000-b43bd000 ---p 00000000 00:00 0 
b43bd000-b440e000 rw-p 00000000 00:00 0 
b440e000-b440f000 ---p 00000000 00:00 0 
b440f000-b6460000 rw-p 00000000 00:00 0 
b6463000-b64b4000 rw-p 00000000 00:00 0 
b64b5000-b6536000 rw-p 00000000 00:00 0 
b6536000-b67b0000 r--p 0006f000 b3:02 8717       /usr/lib/locale/locale-archive
b67b0000-b69b0000 r--p 00000000 b3:02 8717       /usr/lib/locale/locale-archive
b69b0000-b6b1c000 r-xp 00000000 b3:02 2543       /usr/lib/arm-linux-gnueabihf/libc.so.6
b6b1c000-b6b1e000 r--p 0016c000 b3:02 2543       /usr/lib/arm-linux-gnueabihf/libc.so.6
b6b1e000-b6b1f000 rw-p 0016e000 b3:02 2543       /usr/lib/arm-linux-gnueabihf/libc.so.6
b6b1f000-b6b29000 rw-p 00000000 00:00 0 
b6b29000-b6b6e000 r-xp 00000000 b3:02 2546       /usr/lib/arm-linux-gnueabihf/libm.so.6
b6b6e000-b6b6f000 r--p 00044000 b3:02 2546       /usr/lib/arm-linux-gnueabihf/libm.so.6
b6b6f000-b6b70000 rw-p 00045000 b3:02 2546       /usr/lib/arm-linux-gnueabihf/libm.so.6
b6b70000-b6ba2000 r-xp 00000000 b3:02 5505       /usr/lib/arm-linux-gnueabihf/libcrypt.so.1.1.0
b6ba2000-b6bbf000 ---p 00032000 b3:02 5505       /usr/lib/arm-linux-gnueabihf/libcrypt.so.1.1.0
b6bbf000-b6bc0000 r--p 0003f000 b3:02 5505       /usr/lib/arm-linux-gnueabihf/libcrypt.so.1.1.0
b6bc0000-b6bc1000 rw-p 00040000 b3:02 5505       /usr/lib/arm-linux-gnueabihf/libcrypt.so.1.1.0
b6bc1000-b6bc9000 rw-p 00000000 00:00 0 
b6bd0000-b6c35000 r-xp 00000000 b3:02 5567       /usr/lib/arm-linux-gnueabihf/libgmp.so.10.4.1
b6c35000-b6c4f000 ---p 00065000 b3:02 5567       /usr/lib/arm-linux-gnueabihf/libgmp.so.10.4.1
b6c4f000-b6c50000 r--p 0006f000 b3:02 5567       /usr/lib/arm-linux-gnueabihf/libgmp.so.10.4.1
b6c50000-b6c51000 rw-p 00070000 b3:02 5567       /usr/lib/arm-linux-gnueabihf/libgmp.so.10.4.1
b6c54000-b6c56000 r-xp 00000000 b3:02 164842     /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/monitor.so
b6c56000-b6c57000 r--p 00001000 b3:02 164842     /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/monitor.so
b6c57000-b6c58000 rw-p 00002000 b3:02 164842     /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/monitor.so
b6c58000-b6c60000 rw-p 00000000 00:00 0 
b6c60000-b6c76000 r-xp 00000000 b3:02 5778       /usr/lib/arm-linux-gnueabihf/libz.so.1.2.13
b6c76000-b6c8f000 ---p 00016000 b3:02 5778       /usr/lib/arm-linux-gnueabihf/libz.so.1.2.13
b6c8f000-b6c90000 r--p 0001f000 b3:02 5778       /usr/lib/arm-linux-gnueabihf/libz.so.1.2.13
b6c90000-b6c91000 rw-p 00020000 b3:02 5778       /usr/lib/arm-linux-gnueabihf/libz.so.1.2.13
b6c94000-b6c96000 r-xp 00000000 b3:02 164817     /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/enc/trans/transdb.so
b6c96000-b6c97000 r--p 00001000 b3:02 164817     /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/enc/trans/transdb.so
b6c97000-b6c98000 rw-p 00002000 b3:02 164817     /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/enc/trans/transdb.so
b6c98000-b6c9c000 rw-p 00000000 00:00 0 
b6c9c000-b6c9d000 r-xp 00000000 b3:02 2545       /usr/lib/arm-linux-gnueabihf/libdl.so.2
b6c9d000-b6c9e000 r--p 00000000 b3:02 2545       /usr/lib/arm-linux-gnueabihf/libdl.so.2
b6c9e000-b6c9f000 rw-p 00001000 b3:02 2545       /usr/lib/arm-linux-gnueabihf/libdl.so.2
b6c9f000-b6ca1000 rw-p 00000000 00:00 0 
b6ca1000-b6fa4000 r-xp 00000000 b3:02 61655      /usr/lib/arm-linux-gnueabihf/libruby-3.1.so.3.1.2
b6fa4000-b6fa9000 r--p 00303000 b3:02 61655      /usr/lib/arm-linux-gnueabihf/libruby-3.1.so.3.1.2
b6fa9000-b6faa000 rw-p 00308000 b3:02 61655      /usr/lib/arm-linux-gnueabihf/libruby-3.1.so.3.1.2
b6faa000-b6fb0000 rw-p 00000000 00:00 0 
b6fb0000-b6fb2000 r-xp 00000000 b3:02 5450       /usr/lib/arm-linux-gnueabihf/libarmmem-v6l.so
b6fb2000-b6fc1000 ---p 00002000 b3:02 5450       /usr/lib/arm-linux-gnueabihf/libarmmem-v6l.so
b6fc1000-b6fc2000 r--p 00001000 b3:02 5450       /usr/lib/arm-linux-gnueabihf/libarmmem-v6l.so
b6fc2000-b6fc3000 rw-p 00002000 b3:02 5450       /usr/lib/arm-linux-gnueabihf/libarmmem-v6l.so
b6fc4000-b6fc6000 r-xp 00000000 b3:02 164773     /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/enc/encdb.so
b6fc6000-b6fc7000 r--p 00001000 b3:02 164773     /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/enc/encdb.so
b6fc7000-b6fc8000 rw-p 00002000 b3:02 164773     /usr/lib/arm-linux-gnueabihf/ruby/3.1.0/enc/encdb.so
b6fc8000-b6fcc000 rw-p 00000000 00:00 0 
b6fcd000-b6fcf000 rw-p 00000000 00:00 0 
b6fd0000-b6ff7000 r-xp 00000000 b3:02 2540       /usr/lib/arm-linux-gnueabihf/ld-linux-armhf.so.3
b6ff7000-b6ff8000 r--p 00027000 b3:02 2540       /usr/lib/arm-linux-gnueabihf/ld-linux-armhf.so.3
b6ff8000-b6ff9000 rw-p 00028000 b3:02 2540       /usr/lib/arm-linux-gnueabihf/ld-linux-armhf.so.3
be74c000-bef4b000 rw-p 00000000 00:00 0          [stack]
befb4000-befb5000 r-xp 00000000 00:00 0          [sigpage]
ffff0000-ffff1000 r-xp 00000000 00:00 0          [vectors]


Aborted
```

Output from running ```rails server```

https://gist.github.com/Vokda/5cfec28e7ba64972b4f4a036c28f568a

**Comment by flavorjones** [comment]
Thanks for the report, and apologies for my slow response. I'll take a look and try to reproduce.

**Comment by flavorjones** [comment]
Can you tell me more about the system you're on? Are you on a system with an armv6 processor? That issue is described here: https://github.com/sparklemotion/nokogiri/issues/2861

The precompiled gem only supports armv7, but you can still build from source to support your CPU if that's the case.

**Comment by Vokda** [comment]
Yes, my system runs on an armv6 processor. Then I'll compile it for my armv6. 
Thank you very much! :)
