### ISSUE TITLE
[install] - fail in compilation - MacOS Sonoma, ruby 2.7.5.

### ISSUE THREAD

**Issue by mgurican** [sparklemotion/nokogiri#3149]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [*] Yes!

**What is the complete output of `gem install` or `bundle install`?**

```
/Users/guri/.rbenv/versions/2.7.5/bin/ruby -I /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0 -r ./siteconf20240315-87384-5gp5is.rb extconf.rb --use-system-libraries --with-xml2-include\=/usr/local/opt/libxml2/include/libxml2
checking if the C compiler accepts  -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using system libraries.
checking for xmlParseDoc() in libxml/parser.h... yes
checking for xsltParseStylesheetDoc() in libxslt/xslt.h... yes
checking for exsltFuncRegister() in libexslt/exslt.h... yes
checking for xmlHasFeature()... yes
checking for xmlFirstElementChild()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetValidStructuredErrors()... yes
checking for xmlSchemaSetValidStructuredErrors()... yes
checking for xmlSchemaSetParserStructuredErrors()... yes
creating Makefile

current directory: /Users/guri/Documents/workspace/git/mdts/mdts-dg3/dg3/.bundle/ruby/2.7.0/gems/nokogiri-1.10.10/ext/nokogiri
make "DESTDIR=" clean

current directory: /Users/guri/Documents/workspace/git/mdts/mdts-dg3/dg3/.bundle/ruby/2.7.0/gems/nokogiri-1.10.10/ext/nokogiri
make "DESTDIR="
compiling html_document.c
html_document.c:49:49: error: incompatible function pointer types passing 'void (void *, xmlErrorPtr)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
  xmlSetStructuredErrorFunc((void *)error_list, Nokogiri_error_array_pusher);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/libxml2/include/libxml2/libxml/xmlerror.h:898:29: note: passing argument to parameter 'handler' here
                                 xmlStructuredErrorFunc handler);
                                                        ^
html_document.c:78:11: warning: assigning to 'xmlErrorPtr' (aka 'struct _xmlError *') from 'const xmlError *' (aka 'const struct _xmlError *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    error = xmlGetLastError();
          ^ ~~~~~~~~~~~~~~~~~
html_document.c:114:49: error: incompatible function pointer types passing 'void (void *, xmlErrorPtr)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
  xmlSetStructuredErrorFunc((void *)error_list, Nokogiri_error_array_pusher);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/libxml2/include/libxml2/libxml/xmlerror.h:898:29: note: passing argument to parameter 'handler' here
                                 xmlStructuredErrorFunc handler);
                                                        ^
html_document.c:124:11: warning: assigning to 'xmlErrorPtr' (aka 'struct _xmlError *') from 'const xmlError *' (aka 'const struct _xmlError *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    error = xmlGetLastError();
          ^ ~~~~~~~~~~~~~~~~~
2 warnings and 2 errors generated.
make: *** [html_document.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/guri/Documents/workspace/git/mdts/mdts-dg3/dg3/.bundle/ruby/2.7.0/gems/nokogiri-1.10.10 for inspection.
Results logged to /Users/guri/Documents/workspace/git/mdts/mdts-dg3/dg3/.bundle/ruby/2.7.0/extensions/x86_64-darwin-23/2.7.0/nokogiri-1.10.10/gem_make.out

  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:99:in `run'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:51:in `block in make'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:43:in `each'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:43:in `make'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/tempfile.rb:291:in `open'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:30:in `build'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:169:in `block in build_extension'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `synchronize'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `build_extension'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:210:in `block in build_extensions'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `each'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `build_extensions'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/2.7.0/rubygems/installer.rb:844:in `build_extensions'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/source/rubygems.rb:207:in `install'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/worker.rb:62:in `apply_func'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `loop'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `process_queue'
  /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing nokogiri (1.10.10), and Bundler cannot continue.

In Gemfile:
  release was resolved to 0.0.1, which depends on
    markdown2confluence was resolved to 0.0.4, which depends on
      nokogiri
```

**If installation failed during compilation, what are the complete contents of the `mkmf.log` file generated during the failed installation?**

```
have_func: checking for xmlSchemaSetParserStructuredErrors()... -------------------- yes

"clang -o conftest -I/Users/guri/.rbenv/versions/2.7.5/include/ruby-2.7.0/x86_64-darwin23 -I/Users/guri/.rbenv/versions/2.7.5/include/ruby-2.7.0/ruby/backward -I/Users/guri/.rbenv/versions/2.7.5/include/ruby-2.7.0 -I.   -I/usr/local/opt/libxml2/include/libxml2 -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe  -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2   conftest.c  -L. -L/Users/guri/.rbenv/versions/2.7.5/lib -L. -fstack-protector-strong -L/usr/local/lib       -lxslt -lxml2 -lz -lpthread -licucore -lm -lxml2 -lexslt -lxslt -lxml2 -lz -lpthread -licucore -lm -lxml2 -lruby.2.7  -lxslt -lxml2 -lz -lpthread -licucore -lm -lxml2 -lexslt -lxslt -lxml2 -lz -lpthread -licucore -lm -lxml2   "
conftest.c:14:57: error: use of undeclared identifier 'xmlSchemaSetParserStructuredErrors'
int t(void) { void ((*volatile p)()); p = (void ((*)()))xmlSchemaSetParserStructuredErrors; return !p; }
                                                        ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11:
12:   return !!argv[argc];
13: }
14: int t(void) { void ((*volatile p)()); p = (void ((*)()))xmlSchemaSetParserStructuredErrors; return !p; }
/* end */

"clang -o conftest -I/Users/guri/.rbenv/versions/2.7.5/include/ruby-2.7.0/x86_64-darwin23 -I/Users/guri/.rbenv/versions/2.7.5/include/ruby-2.7.0/ruby/backward -I/Users/guri/.rbenv/versions/2.7.5/include/ruby-2.7.0 -I.   -I/usr/local/opt/libxml2/include/libxml2 -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -g -O2 -fno-common -pipe  -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2   conftest.c  -L. -L/Users/guri/.rbenv/versions/2.7.5/lib -L. -fstack-protector-strong -L/usr/local/lib       -lxslt -lxml2 -lz -lpthread -licucore -lm -lxml2 -lexslt -lxslt -lxml2 -lz -lpthread -licucore -lm -lxml2 -lruby.2.7  -lxslt -lxml2 -lz -lpthread -licucore -lm -lxml2 -lexslt -lxslt -lxml2 -lz -lpthread -licucore -lm -lxml2   "
ld: warning: ignoring duplicate libraries: '-lexslt', '-licucore', '-lm', '-lpthread', '-lxml2', '-lxslt', '-lz'
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11:
12:   return !!argv[argc];
13: }
14: extern void xmlSchemaSetParserStructuredErrors();
15: int t(void) { xmlSchemaSetParserStructuredErrors(); return 0; }
/* end */
```

**Tell us about your system!**

What is the output from `ruby -v`?
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin23]
What is the output from `gem -v`?
3.1.6
What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.6
  - RUBY VERSION: 2.7.5 (2021-11-24 patchlevel 203) [x86_64-darwin23]
  - INSTALLATION DIRECTORY: /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0
  - USER INSTALLATION DIRECTORY: /Users/guri/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /Users/guri/.rbenv/versions/2.7.5/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/guri/.rbenv/versions/2.7.5/bin
  - SPEC CACHE DIRECTORY: /Users/guri/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/guri/.rbenv/versions/2.7.5/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-23
  - GEM PATHS:
     - /Users/guri/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0
     - /Users/guri/.gem/ruby/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/guri/.rbenv/versions/2.7.5/bin
     - /usr/local/Cellar/rbenv/1.2.0/libexec
     - /usr/local/opt/libxml2/bin
     - /usr/local/sbin
     - /Users/guri/.rbenv/shims
     - /Users/guri/bin
     - /Applications/Postgres.app/Contents/Versions/13/bin
     - /Applications/Docker.app/Contents/Resources/bin/
     - /usr/local/sbin
     - /Users/guri/.rbenv/shims
     - /Users/guri/bin
     - /Applications/Postgres.app/Contents/Versions/13/bin
     - /Applications/Docker.app/Contents/Resources/bin/
     - /usr/local/sbin
     - /Users/guri/.rbenv/shims
     - /Users/guri/bin
     - /Applications/Postgres.app/Contents/Versions/13/bin
     - /Applications/Docker.app/Contents/Resources/bin/docker
     - /usr/local/sbin
     - /Users/guri/.nvm/versions/node/v10.16.3/bin
     - /Users/guri/.rbenv/shims
     - /Users/guri/bin
     - /Applications/Postgres.app/Contents/Versions/13/bin
     - /usr/local/bin
     - /System/Cryptexes/App/usr/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
     - /opt/X11/bin
     - /Applications/Wireshark.app/Contents/MacOS
     - /Users/guri/Applications/flyway
     - /Applications/maven/maven-current/bin
     - /Applications/Postgres.app/Contents/Versions/9.5/bin
```

If you're using Bundler:
- what is the output from `bundle version`?
Bundler version 2.3.26 (2022-11-17 commit 23ec5b8501)
- what is the output from `bundle config`? (Take care to redact any credentials)

```
Settings are listed in order of priority. The top value will be used.
build.nokogiri
Set for your local app (/Users/guri/Documents/workspace/git/mdts/mdts-dg3/dg3/.bundle/config): "--use-system-libraries --with-xml2-include=/usr/local/opt/libxml2/include/libxml2"

force_ruby_platform
Set for your local app (/Users/guri/Documents/workspace/git/mdts/mdts-dg3/dg3/.bundle/config): true

path
Set for your local app (/Users/guri/Documents/workspace/git/mdts/mdts-dg3/dg3/.bundle/config): ".bundle"
```

If you're on MacOS, please note:
- the version of XCode you have installed (if you know)
15.3 
- the output of `gcc -v` or `clang -v`
```
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by flavorjones** [comment]
Moving to discussion as nokogiri 1.10.10 and ruby 2.7 are no longer supported.
