### ISSUE TITLE
[bug] on JRuby, Loofah subclasses are broken

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#3370]
**Please describe the bug**

On JRuby, running Loofah's test suite:

```

  1) Error:
IntegrationTestHtml::html4 fragment::#to_text#test_0001_add newlines before and after html4 block elements:
NoMethodError: undefined method `scrub!' for #<Loofah::HTML4::DocumentFragment:0x6ac4f31d>
    lib/loofah/concerns.rb:121:in `to_text'
    test/integration/test_html.rb:58:in `block in IntegrationTestHtml'

  2) Error:
IntegrationTestHtml::html4 fragment::#to_text#test_0003_remove extraneous whitespace:
NoMethodError: undefined method `scrub!' for #<Loofah::HTML4::DocumentFragment:0x13bf5fd>
    lib/loofah/concerns.rb:121:in `to_text'
    test/integration/test_html.rb:76:in `block in IntegrationTestHtml'

  3) Error:
IntegrationTestHtml::html4 fragment::#to_text#test_0002_add newlines before and after html5 block elements:
NoMethodError: undefined method `scrub!' for #<Loofah::HTML4::DocumentFragment:0x138d978e>
    lib/loofah/concerns.rb:121:in `to_text'
    test/integration/test_html.rb:67:in `block in IntegrationTestHtml'

  4) Error:
IntegrationTestHtml::html4 fragment::#to_text#test_0004_replaces <br> with newlines:
NoMethodError: undefined method `scrub!' for #<Loofah::HTML4::DocumentFragment:0x7a22302c>
    lib/loofah/concerns.rb:121:in `to_text'
    test/integration/test_html.rb:85:in `block in IntegrationTestHtml'

1055 runs, 2084 assertions, 0 failures, 4 errors, 0 skips
```

**Additional context**

I'm pretty sure this is due to changes made in https://github.com/sparklemotion/nokogiri/pull/3117 to fix https://github.com/sparklemotion/nokogiri/issues/316.

**Comment by flavorjones** [comment]
This was closed by #3372 and that fix shipped in v1.17.2.
