### ISSUE TITLE
LoadError with ruby-2.0.0-p247

### ISSUE THREAD

**Issue by alexkravets** [sparklemotion/nokogiri#934]
/Users/akravets/.rvm/gems/ruby-2.0.0-p247/gems/nokogiri-1.6.0/lib/nokogiri.rb:28:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from /Users/akravets/.rvm/gems/ruby-2.0.0-p247/gems/nokogiri-1.6.0/lib/nokogiri.rb:28:in `<top (required)>'

**Comment by Phrogz** [comment]
I'm seeing this same issue on Windows x64 with Ruby 2.2 from RubyInstaller.org

~~~
C:\>gem install nokogiri
Fetching: nokogiri-1.6.6.2-x64-mingw32.gem (100%)
Nokogiri is built with the packaged libraries: libxml2-2.9.2, libxslt-1.1.28, zlib-1.2.8, libiconv-1.14.
Successfully installed nokogiri-1.6.6.2-x64-mingw32
1 gem installed

C:\>ruby -v -e "require 'nokogiri'"
ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]
C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2-x64-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from -e:1:in `<main>'
~~~

**Comment by flavorjones** [comment]
Closing, as I'm not clear on how to reproduce the original issue.
