### ISSUE TITLE
Nokogiri doesn't support the xpath function - "tokenize"

### ISSUE THREAD

**Issue by aruprakshit** [sparklemotion/nokogiri#957]
```
require 'nokogiri'

doc = Nokogiri::HTML::Document.parse <<-EOT
<div class="total_count">
    <b>Returned:</b>&nbsp;97&nbsp;results
</div>
EOT

doc.xpath("normalize-space(//div[@class='total_count'])")
# => "Returned: 97 results"
doc.xpath("tokenize(normalize-space(//div[@class='total_count']),'\w+')")
# => 
# ~> /home/kirti/.rvm/gems/ruby-2.0.0-p0/gems/nokogiri-1.6.0/lib/nokogiri/xml/node.rb:159:in `evaluate': xmlXPathCompOpEval: function tokenize not found (RuntimeError)
# ~>    from /home/kirti/.rvm/gems/ruby-2.0.0-p0/gems/nokogiri-1.6.0/lib/nokogiri/xml/node.rb:159:in `block in xpath'
# ~>    from /home/kirti/.rvm/gems/ruby-2.0.0-p0/gems/nokogiri-1.6.0/lib/nokogiri/xml/node.rb:150:in `map'
# ~>    from /home/kirti/.rvm/gems/ruby-2.0.0-p0/gems/nokogiri-1.6.0/lib/nokogiri/xml/node.rb:150:in `xpath'
# ~>    from -:9:in `<main>'
```

**Comment by andhapp** [comment]
Can we make this fact - only supports `XPath 1.0` - obvious in documentation somewhere please?

**Comment by aruprakshit** [comment]
@andhapp It is mentioned [here](https://github.com/sparklemotion/nokogiri#features)

**Comment by jvshahid** [comment]
closing since this fact is documented in the [features section](https://www.rubydoc.info/github/sparklemotion/nokogiri#Features) on the docs page as well as in the repo's [README](https://github.com/sparklemotion/nokogiri#features)
